const currentUser=getCurrentUser();
function enforceAdminViewport(){const finePointer=matchMedia("(hover: hover) and (pointer: fine)").matches,desktop=innerWidth>=701||finePointer,root=document.documentElement,body=document.body,shell=document.querySelector(".admin-shell"),sidebar=document.querySelector(".admin-sidebar"),brand=sidebar?.querySelector(".brand"),nav=sidebar?.querySelector("nav"),adminUser=sidebar?.querySelector(".admin-user"),main=document.querySelector(".admin-main");if(!shell||!sidebar||!main)return;const set=(element,name,value)=>element&&element.style.setProperty(name,value,"important"),clear=(element,names)=>element&&names.forEach(name=>element.style.removeProperty(name));if(desktop){set(root,"height","100%");set(root,"overflow","hidden");set(body,"height","100%");set(body,"overflow","hidden");set(shell,"display","block");set(shell,"height","100vh");set(shell,"min-height","0");set(shell,"overflow","hidden");set(sidebar,"position","fixed");set(sidebar,"inset","0 auto 0 0");set(sidebar,"z-index","60");set(sidebar,"display","flex");set(sidebar,"width","270px");set(sidebar,"height","100vh");set(sidebar,"max-height","100vh");set(sidebar,"padding","24px 18px");set(sidebar,"overflow","hidden");set(sidebar,"transform","none");set(brand,"display","flex");set(nav,"display","flex");set(nav,"min-height","0");set(nav,"margin","6px 0 82px");set(nav,"overflow-x","hidden");set(nav,"overflow-y","auto");set(nav,"flex","1");set(nav,"flex-direction","column");set(adminUser,"display","flex");set(main,"width","auto");set(main,"height","100vh");set(main,"margin-left","270px");set(main,"overflow-x","hidden");set(main,"overflow-y","scroll");}else{clear(root,["height","overflow"]);clear(body,["height","overflow"]);clear(shell,["display","height","min-height","overflow"]);clear(sidebar,["position","inset","z-index","display","width","height","max-height","padding","overflow","transform"]);clear(brand,["display"]);clear(nav,["display","min-height","margin","overflow-x","overflow-y","flex","flex-direction"]);clear(adminUser,["display"]);clear(main,["width","height","margin-left","overflow-x","overflow-y"]);}}
enforceAdminViewport();const adminLayoutMedia=matchMedia("(hover: hover) and (pointer: fine)");if(adminLayoutMedia.addEventListener)adminLayoutMedia.addEventListener("change",enforceAdminViewport);else adminLayoutMedia.addListener(enforceAdminViewport);addEventListener("resize",enforceAdminViewport,{passive:true});
if(!currentUser||!localStorage.getItem("wiki-auth-token")){location.replace("login.html");throw new Error("需要重新登录以启用安全会话");}
if(!["admin","super_admin"].includes(currentUser.role)){location.replace("index.html");throw new Error("需要管理员权限");}

const tableBody=document.querySelector("#adminArticleList");
const userTableBody=document.querySelector("#adminUserList");
const modal=document.querySelector("#articleModal");
const form=document.querySelector("#articleForm");
const search=document.querySelector("#adminSearch");
const userSearch=document.querySelector("#userSearch");
const suggestionList=document.querySelector("#suggestionAdminList");
const trashList=document.querySelector("#trashList");
const logList=document.querySelector("#auditLogList");
const searchGapList=document.querySelector("#searchGapList");
document.querySelector('.admin-sidebar nav a[href="index.html"]').insertAdjacentHTML("beforebegin",'<a class="admin-nav" href="#pushPanel">✉ 消息推送</a>');
document.querySelector("#usersPanel").insertAdjacentHTML("afterend",`<section class="admin-table-card users-card" id="pushPanel"><div class="table-toolbar"><div><h2>消息推送</h2><span>向全体用户或指定用户发送系统通知和管理员私信</span></div></div><form class="admin-push-form" id="adminPushForm"><div class="form-grid"><label>消息类型<select name="mode"><option value="system">系统通知</option><option value="direct_message">管理员私信</option></select></label><label>发送范围<select name="audience" id="pushAudience"><option value="all">全体用户</option><option value="selected">指定用户</option></select></label></div><label id="pushUsersLabel" hidden>选择用户<select name="userIds" id="pushUsers" multiple></select><small>电脑可按住 Ctrl 选择多个用户</small></label><label>通知标题<input name="title" maxlength="80" placeholder="例如：Smart Wiki 功能更新"></label><label>通知内容<textarea name="content" maxlength="1000" rows="5" required placeholder="输入要推送给用户的内容…"></textarea></label><div class="admin-push-actions"><small>全体推送不会发送给当前管理员自己。</small><button class="submit-button compact" type="submit">发送消息</button></div></form></section>`);
let articlePage=1;const ARTICLES_PER_PAGE=15;
document.querySelectorAll(".admin-table-card").forEach((panel,index)=>{panel.classList.add("collapsible-admin-panel");if(index>0)panel.classList.add("panel-collapsed");const toolbar=panel.querySelector(".table-toolbar");if(toolbar){const toggle=document.createElement("button");toggle.type="button";toggle.className="panel-toggle";toggle.textContent=index===0?"收起":"展开";toggle.addEventListener("click",()=>{panel.classList.toggle("panel-collapsed");toggle.textContent=panel.classList.contains("panel-collapsed")?"展开":"收起";});toolbar.appendChild(toggle);}});
document.querySelectorAll(".admin-nav[href^='#']").forEach(link=>link.addEventListener("click",()=>{const panel=document.querySelector(link.getAttribute("href"));if(panel){panel.classList.remove("panel-collapsed");const toggle=panel.querySelector(".panel-toggle");if(toggle)toggle.textContent="收起";}document.querySelectorAll(".admin-nav").forEach(item=>item.classList.remove("active"));link.classList.add("active");}));
const articlePager=document.createElement("div");articlePager.className="admin-pager";document.querySelector(".article-table-wrap").after(articlePager);
form.elements.category.innerHTML=[...CATEGORY_ORDER,"其他"].map(value=>`<option value="${value}">${value}</option>`).join("");

function safeText(text){const node=document.createElement("div");node.textContent=text??"";return node.innerHTML;}
function showToast(message){const toast=document.querySelector("#toast");toast.textContent=message;toast.hidden=false;setTimeout(()=>toast.hidden=true,1800);}
function renderPushUsers(){const select=document.querySelector("#pushUsers");if(select)select.innerHTML=getUsers().filter(user=>user.id!==currentUser.id).map(user=>`<option value="${user.id}">${safeText(user.name)} · ${safeText(user.email)}</option>`).join("");}
function formatDate(value){return value||new Date().toISOString().slice(0,10);}

function renderArticles(){
  const all=getArticles();const keyword=search.value.trim().toLowerCase();const items=all.filter(item=>`${item.title} ${item.category} ${item.summary}`.toLowerCase().includes(keyword)),pages=Math.max(1,Math.ceil(items.length/ARTICLES_PER_PAGE));articlePage=Math.min(articlePage,pages);const visible=items.slice((articlePage-1)*ARTICLES_PER_PAGE,articlePage*ARTICLES_PER_PAGE);
  tableBody.innerHTML=visible.map(item=>`<tr><td><div class="table-title"><span class="card-icon ${item.color}">${safeText(item.icon)}</span><div><strong>${safeText(item.title)}</strong><small>${safeText(item.summary)}</small></div></div></td><td><span class="category-badge">${safeText(item.category)}</span> <span class="status-badge ${item.status}">${item.status==="published"?"已发布":item.status==="draft"?"草稿":"已归档"}</span></td><td>${formatDate(item.updatedAt)}</td><td><div class="row-actions"><button data-edit="${item.id}" title="编辑">✎</button><a href="article.html?id=${item.id}" title="预览">↗</a><button class="danger" data-delete="${item.id}" title="移到回收站">⌫</button></div></td></tr>`).join("");articlePager.innerHTML=items.length>ARTICLES_PER_PAGE?`<button ${articlePage===1?"disabled":""} data-page="${articlePage-1}">← 上一页</button><span>第 ${articlePage} / ${pages} 页 · 每页 ${ARTICLES_PER_PAGE} 条</span><button ${articlePage===pages?"disabled":""} data-page="${articlePage+1}">下一页 →</button>`:"";
  document.querySelector("#adminArticleCount").textContent=all.length;document.querySelector("#categoryCount").textContent=new Set(all.map(item=>item.category)).size;document.querySelector("#adminResultCount").textContent=`共 ${items.length} 个条目`;document.querySelector("#adminEmpty").hidden=items.length!==0;document.querySelector(".article-table-wrap").hidden=items.length===0;
}

function renderUsers(){
  const all=getUsers();const keyword=userSearch.value.trim().toLowerCase();const users=all.filter(user=>`${user.name} ${user.email} ${user.role}`.toLowerCase().includes(keyword));
  userTableBody.innerHTML=users.map(user=>{const isSelf=user.id===currentUser.id;const isSuperAdmin=user.role==="super_admin";const canEdit=currentUser.role==="super_admin"&&!isSelf&&!isSuperAdmin;const roleName=isSuperAdmin?"超级管理员":user.role==="admin"?"Admin":"普通用户";const roleControl=canEdit?`<select class="role-select" data-role-user="${user.id}"><option value="user" ${user.role==="user"?'selected':''}>普通用户</option><option value="admin" ${user.role==="admin"?'selected':''}>Admin</option></select>`:`<span class="role-badge ${isSuperAdmin?'super-role':''}">${roleName}</span>`;const note=isSelf?'<small>当前账号</small>':isSuperAdmin?'<small>最高权限账号</small>':user.mustChangePassword?'<small>等待修改临时密码</small>':'';return `<tr><td><div class="user-table-name"><span class="avatar">${safeText(user.name.slice(0,1))}</span><div><strong>${safeText(user.name)}</strong>${note}</div></div></td><td>${safeText(user.email)}</td><td>${roleControl}</td><td><div class="row-actions">${canEdit?`<button data-reset-password="${user.id}" title="重置密码为 123456">↺</button>`:""}<button class="danger" data-delete-user="${user.id}" ${(!canEdit)?'disabled title="无权删除此账号"':'title="删除用户"'}>⌫</button></div></td></tr>`;}).join("");
  document.querySelector("#adminUserCount").textContent=all.length;document.querySelector("#userResultCount").textContent=`共 ${users.length} 个用户`;document.querySelector("#userEmpty").hidden=users.length!==0;document.querySelector(".user-table-wrap").hidden=users.length===0;
}

function adminMarkdownHtml(text){return safeText(text||"").replace(/^### (.+)$/gm,"<h3>$1</h3>").replace(/^## (.+)$/gm,"<h2>$1</h2>").replace(/^# (.+)$/gm,"<h1>$1</h1>").replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>").replace(/\n\n/g,"</p><p>").replace(/^[-*] (.+)$/gm,"<li>$1</li>");}
function updateEditorPreview(){document.querySelector("#adminMarkdownPreview").innerHTML=`<p>${adminMarkdownHtml(form.elements.content.value)}</p>`;}
function openEditor(item){form.reset();document.querySelector("#modalTitle").textContent=item?"编辑条目":"新建条目";if(item)Object.keys(item).forEach(key=>{if(form.elements[key])form.elements[key].value=key==="tags"?(item.tags||[]).join(", "):item[key];});else form.elements.status.value="draft";const versions=item?(getVersions()[item.id]||[]):[];document.querySelector("#versionInfo").textContent=versions.length?`已有 ${versions.length} 个历史版本`:`保存时会自动记录历史版本`;document.querySelector("#restoreVersionButton").hidden=versions.length===0;modal.hidden=false;document.body.classList.add("modal-open");updateEditorPreview();form.elements.title.focus();}
function closeEditor(){modal.hidden=true;document.body.classList.remove("modal-open");}

document.querySelector("#userName").textContent=currentUser.name;document.querySelector("#userEmail").textContent=currentUser.email;document.querySelector("#userAvatar").textContent=currentUser.name.slice(0,1);
document.querySelector("#logoutButton").addEventListener("click",logout);document.querySelector("#newArticleButton").addEventListener("click",()=>openEditor());document.querySelectorAll("[data-close-modal]").forEach(button=>button.addEventListener("click",closeEditor));search.addEventListener("input",()=>{articlePage=1;renderArticles();});articlePager.addEventListener("click",event=>{const button=event.target.closest("[data-page]");if(button&&!button.disabled){articlePage=Number(button.dataset.page);renderArticles();document.querySelector("#articlesPanel").scrollIntoView({behavior:"smooth"});}});userSearch.addEventListener("input",renderUsers);

tableBody.addEventListener("click",event=>{const editButton=event.target.closest("[data-edit]");const deleteButton=event.target.closest("[data-delete]");if(editButton)openEditor(getArticles().find(item=>item.id===Number(editButton.dataset.edit)));if(deleteButton){const item=getArticles().find(article=>article.id===Number(deleteButton.dataset.delete));if(item&&confirm(`将“${item.title}”移到回收站吗？`)){saveTrash([{...item,deletedAt:new Date().toISOString(),deletedBy:currentUser.name},...getTrash()]);saveArticles(getArticles().filter(article=>article.id!==item.id));addLog("移到回收站",item.title);renderArticles();renderManagement();showToast("条目已移到回收站");}}});

userTableBody.addEventListener("change",event=>{const select=event.target.closest("[data-role-user]");if(!select||currentUser.role!=="super_admin")return;const users=getUsers();const user=users.find(item=>item.id===Number(select.dataset.roleUser));if(!user||user.role==="super_admin")return;user.role=select.value;saveUsers(users);addLog("修改用户身份",`${user.name} → ${user.role}`);renderUsers();renderManagement();showToast(`${user.name} 已设为${user.role==="admin"?" Admin":"普通用户"}`);});
userTableBody.addEventListener("click",async event=>{const reset=event.target.closest("[data-reset-password]"),button=event.target.closest("[data-delete-user]");if(reset&&currentUser.role==="super_admin"){const users=getUsers(),user=users.find(item=>item.id===Number(reset.dataset.resetPassword));if(user&&confirm(`确定把“${user.name}”的密码重置为临时密码 123456 吗？用户下次登录必须修改密码。`)){const response=await fetch(wikiApiUrl(`/api/users/${user.id}/reset-password`),{method:"POST",headers:apiHeaders()});const result=await response.json();if(!response.ok)return showToast(result.error||"重置失败");user.mustChangePassword=true;localStorage.setItem("wiki-users",JSON.stringify(users));addLog("重置用户密码",user.name);renderUsers();showToast("密码已重置为 123456");}return;}if(!button||button.disabled||currentUser.role!=="super_admin")return;const users=getUsers();const user=users.find(item=>item.id===Number(button.dataset.deleteUser));if(user&&user.role!=="super_admin"&&confirm(`确定删除用户“${user.name}”吗？此操作不会删除知识条目。`)){saveUsers(users.filter(item=>item.id!==user.id));addLog("删除用户",user.name);renderUsers();renderManagement();showToast("用户已删除");}});

form.addEventListener("submit",event=>{event.preventDefault();const data=new FormData(form);const items=getArticles();const id=Number(data.get("id"));const index=items.findIndex(item=>item.id===id);const existing=index>=0?items[index]:{};const article={...existing,id:id||Date.now(),title:data.get("title").trim(),category:data.get("category"),status:data.get("status"),tags:data.get("tags").split(/[,，]/).map(tag=>tag.trim()).filter(Boolean),icon:data.get("icon").trim(),color:data.get("color"),summary:data.get("summary").trim(),content:data.get("content").trim(),author:currentUser.name,updatedAt:new Date().toISOString().slice(0,10)};if(index>=0){addArticleVersion(items[index]);items[index]=article;}else items.unshift(article);saveArticles(items);addLog(index>=0?"编辑文章":"创建文章",article.title);closeEditor();renderArticles();renderManagement();showToast(index>=0?"条目已更新":"条目已创建");});
function renderManagement(){
  const gaps=getSearchGaps();const openGaps=gaps.filter(item=>item.status!=="resolved");document.querySelector("#searchGapCount").textContent=`${openGaps.length} 个待补充主题 · 按最近搜索排序`;searchGapList.innerHTML=gaps.length?gaps.map(item=>`<div class="management-row search-gap-row ${item.status}"><div><strong>${safeText(item.keyword)}</strong><span>搜索 ${item.count||1} 次 · 最近 ${new Date(item.lastSearchedAt).toLocaleString("zh-CN")}${item.users?.length?` · ${item.users.map(user=>safeText(user.name)).join("、")}`:" · 匿名用户"}</span><p>${item.status==="resolved"?"已处理":"知识库暂无覆盖，用户已获得 Google 专项搜索入口"}</p></div><div><a class="secondary-button" href="https://www.google.com/search?q=${encodeURIComponent(item.keyword+" 详细介绍 科普")}" target="_blank" rel="noopener noreferrer">Google ↗</a>${item.status!=="resolved"?`<button class="secondary-button" data-gap-create="${item.id}">创建草稿</button><button class="secondary-button" data-gap-resolve="${item.id}">标记完成</button>`:`<button class="secondary-button" data-gap-reopen="${item.id}">重新打开</button>`}<button class="secondary-button danger-text" data-gap-delete="${item.id}">删除</button></div></div>`).join(""):'<div class="profile-empty">暂无内容缺口报告</div>';
  const suggestions=getSuggestions();suggestionList.innerHTML=suggestions.length?suggestions.map(item=>`<div class="management-row"><div><strong>${safeText(item.articleTitle)}</strong><span>${safeText(item.userName)} · ${new Date(item.createdAt).toLocaleString("zh-CN")}</span><p>${safeText(item.message)}</p></div><div><span class="suggestion-status ${item.status}">${item.status==="pending"?"待处理":item.status==="accepted"?"已采纳":"已关闭"}</span>${item.status==="pending"?`<button class="secondary-button" data-suggestion="${item.id}" data-result="accepted">采纳</button><button class="secondary-button" data-suggestion="${item.id}" data-result="closed">关闭</button>`:""}</div></div>`).join(""):'<div class="profile-empty">暂无用户建议</div>';
  const trash=getTrash();trashList.innerHTML=trash.length?trash.map(item=>`<div class="management-row"><div><strong>${safeText(item.title)}</strong><span>${safeText(item.deletedBy)} 删除于 ${new Date(item.deletedAt).toLocaleString("zh-CN")}</span></div><div><button class="secondary-button" data-restore="${item.id}">恢复</button><button class="secondary-button danger-text" data-purge="${item.id}">永久删除</button></div></div>`).join(""):'<div class="profile-empty">回收站为空</div>';
  const logs=getLogs();logList.innerHTML=logs.length?logs.map(log=>`<div class="management-row"><div><strong>${safeText(log.action)}</strong><span>${safeText(log.user)} · ${new Date(log.createdAt).toLocaleString("zh-CN")}</span></div><p>${safeText(log.target)}</p></div>`).join(""):'<div class="profile-empty">暂无操作记录</div>';
}
searchGapList.addEventListener("click",event=>{const create=event.target.closest("[data-gap-create]"),resolve=event.target.closest("[data-gap-resolve]"),reopen=event.target.closest("[data-gap-reopen]"),remove=event.target.closest("[data-gap-delete]");const button=create||resolve||reopen||remove;if(!button)return;const id=Number(button.dataset.gapCreate||button.dataset.gapResolve||button.dataset.gapReopen||button.dataset.gapDelete);const items=getSearchGaps();const item=items.find(entry=>entry.id===id);if(!item)return;if(create){openEditor();form.elements.title.value=item.keyword;form.elements.summary.value=`关于“${item.keyword}”的基础介绍与科普。`;form.elements.content.value=`# ${item.keyword}\n\n请根据可靠来源补充详细正文、核心概念、常见误区和实际应用。`;form.elements.icon.value="知";form.elements.category.value="其他";updateEditorPreview();item.status="drafting";saveSearchGaps(items);renderManagement();return;}if(resolve){item.status="resolved";item.resolvedAt=new Date().toISOString();item.resolvedBy=currentUser.name;addLog("处理内容缺口",item.keyword);}if(reopen){item.status="open";delete item.resolvedAt;delete item.resolvedBy;}if(remove){if(!confirm(`删除“${item.keyword}”的搜索报告吗？`))return;saveSearchGaps(items.filter(entry=>entry.id!==id));renderManagement();showToast("报告已删除");return;}saveSearchGaps(items);renderManagement();showToast("内容缺口状态已更新");});
suggestionList.addEventListener("click",event=>{const button=event.target.closest("[data-suggestion]");if(!button)return;const items=getSuggestions();const item=items.find(entry=>entry.id===Number(button.dataset.suggestion));if(!item)return;item.status=button.dataset.result;item.reviewedBy=currentUser.name;item.reviewedAt=new Date().toISOString();saveSuggestions(items);addLog(item.status==="accepted"?"采纳建议":"关闭建议",item.articleTitle);renderManagement();showToast("建议状态已更新");});
trashList.addEventListener("click",event=>{const restore=event.target.closest("[data-restore]");const purge=event.target.closest("[data-purge]");if(restore){const trash=getTrash();const item=trash.find(entry=>entry.id===Number(restore.dataset.restore));if(item){const {deletedAt,deletedBy,...article}=item;saveArticles([article,...getArticles().filter(entry=>entry.id!==article.id)]);saveTrash(trash.filter(entry=>entry.id!==item.id));addLog("恢复文章",article.title);renderArticles();renderManagement();showToast("文章已恢复");}}if(purge&&confirm("永久删除后无法恢复，确定继续吗？")){const trash=getTrash();const item=trash.find(entry=>entry.id===Number(purge.dataset.purge));saveTrash(trash.filter(entry=>entry.id!==Number(purge.dataset.purge)));addLog("永久删除文章",item?.title||String(purge.dataset.purge));renderManagement();showToast("文章已永久删除");}});
form.elements.content.addEventListener("input",updateEditorPreview);
document.querySelector("#restoreVersionButton").addEventListener("click",()=>{const id=Number(form.elements.id.value);const version=(getVersions()[id]||[])[0];if(!version)return;Object.keys(version).forEach(key=>{if(form.elements[key])form.elements[key].value=key==="tags"?(version.tags||[]).join(", "):version[key];});updateEditorPreview();showToast("已载入上一版本，点击保存后生效");});
document.querySelector("#exportBackup").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(exportWikiData(),null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`smart-wiki-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);addLog("导出数据备份","JSON 备份");renderManagement();});
document.querySelector("#importBackup").addEventListener("change",async event=>{const file=event.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!confirm("导入会覆盖当前文章及相关数据，确定继续吗？"))return;importWikiData(data);addLog("导入数据备份",file.name);renderArticles();renderUsers();renderManagement();showToast("备份导入成功");}catch(error){showToast(error.message||"备份文件无效");}event.target.value="";});
document.querySelector("#pushAudience").addEventListener("change",event=>document.querySelector("#pushUsersLabel").hidden=event.target.value!=="selected");document.querySelector("#adminPushForm").addEventListener("submit",async event=>{event.preventDefault();const pushForm=event.currentTarget,audience=pushForm.elements.audience.value,userIds=[...document.querySelector("#pushUsers").selectedOptions].map(option=>Number(option.value));if(audience==="selected"&&!userIds.length){showToast("请至少选择一个用户");return;}const button=pushForm.querySelector("button[type=submit]");button.disabled=true;try{const response=await fetch(wikiApiUrl("/api/admin/push"),{method:"POST",headers:apiHeaders(),body:JSON.stringify({mode:pushForm.elements.mode.value,audience,userIds,title:pushForm.elements.title.value,content:pushForm.elements.content.value})}),data=await response.json();if(!response.ok)throw new Error(data.error||"发送失败");addLog(pushForm.elements.mode.value==="system"?"推送系统通知":"发送管理员私信",`${data.count} 位用户`);pushForm.reset();document.querySelector("#pushUsersLabel").hidden=true;showToast(`已成功发送给 ${data.count} 位用户`);}catch(error){showToast(error.message);}finally{button.disabled=false;}});document.addEventListener("keydown",event=>{if(event.key==="Escape"&&!modal.hidden)closeEditor();});renderArticles();renderUsers();renderPushUsers();renderManagement();Promise.all([syncArticlesWithProject(),syncUsersWithProject(),syncSearchGapsWithProject()]).then(()=>{renderArticles();renderUsers();renderPushUsers();renderManagement();});
