let articles=getArticles();
const articleList=document.querySelector("#articleList");
function escapeHtml(text){const node=document.createElement("div");node.textContent=text;return node.innerHTML;}
function mountKnowledgeBackToTop(){if(document.querySelector("#backToTop"))return;document.body.insertAdjacentHTML("beforeend",'<button class="back-to-top show" id="backToTop" type="button" aria-label="回到页面顶部" title="回到顶部"><span>↑</span><small>顶部</small></button>');document.querySelector("#backToTop").addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}));}
function initTheme(){const saved=localStorage.getItem("wiki-theme"),prefersDark=globalThis.matchMedia?.("(prefers-color-scheme: dark)").matches;if(!saved)document.documentElement.classList.toggle("dark",Boolean(prefersDark));else document.documentElement.classList.toggle("dark",saved==="dark");const button=document.querySelector("#themeButton");if(!button)return;const update=()=>{const dark=document.documentElement.classList.contains("dark");button.textContent=dark?"☀":"☾";button.setAttribute("aria-label",dark?"切换为浅色模式":"切换为深色模式");};update();button.addEventListener("click",()=>{document.documentElement.classList.toggle("dark");localStorage.setItem("wiki-theme",document.documentElement.classList.contains("dark")?"dark":"light");document.documentElement.dataset.themeSource="manual";update();});}
function initUserMenu(){const area=document.querySelector("#userActions");if(!area)return;const user=getCurrentUser();if(!user){area.innerHTML=`<a class="login-button" href="login.html">登录 / 注册</a>`;return;}const canManage=user.role==="admin"||user.role==="super_admin";const roleLabel=user.role==="super_admin"?"超级管理员":user.role==="admin"?"Admin":"";const label=roleLabel?`${escapeHtml(user.name)} · ${roleLabel}`:escapeHtml(user.name);area.innerHTML=`<a class="user-chip" href="profile.html" title="个人中心"><span>${avatarMarkup(user)}</span>${label}</a>${canManage?'<a class="manage-link" href="admin.html">后台</a>':''}<button class="text-button" id="homeLogout">退出</button>`;document.querySelector("#homeLogout").addEventListener("click",logout);}
async function initHome(){if(!articleList)return;articles=await syncArticlesWithProject();let featured=[];try{const response=await fetch(wikiApiUrl("/api/featured")),data=await response.json();if(response.ok&&Array.isArray(data.items))featured=data.items;}catch{}const topInput=document.querySelector("#searchInput"),heroInput=document.querySelector("#heroSearchInput"),resultCount=document.querySelector("#resultCount"),empty=document.querySelector("#emptyState"),externalActions=document.querySelector("#externalSearchActions"),googleLink=document.querySelector("#googleSearchLink"),emptyMessage=document.querySelector("#emptyMessage");let category="全部",gapTimer=null,lastReported="";
  function searchableText(item){return `${item.title} ${item.summary} ${item.category} ${(item.tags||[]).join(" ")}`.toLowerCase();}
  function scheduleGapReport(keyword){clearTimeout(gapTimer);if(keyword.length<2||keyword===lastReported)return;gapTimer=setTimeout(()=>{reportSearchGap(keyword);lastReported=keyword;},900);}
  function render(){const rawKeyword=heroInput.value.trim(),keyword=rawKeyword.toLowerCase(),isHome=document.body.dataset.page==="home";const published=articles.filter(item=>item.status==="published").sort(articleSort);const globalMatches=published.filter(item=>searchableText(item).includes(keyword));const items=globalMatches.filter(item=>category==="全部"||item.category===category).sort(articleSort);const visibleItems=isHome&&!rawKeyword&&category==="全部"?(featured.length?featured:items.slice(0,6)):items;articleList.innerHTML=visibleItems.map(item=>`<a class="article-card" href="article.html?id=${item.id}"><div class="card-icon ${item.color}">${escapeHtml(item.icon)}</div><div class="card-meta"><span>${escapeHtml(item.category)}</span><span>${item.tags?.slice(0,2).map(tag=>`#${escapeHtml(tag)}`).join(" ")||"精选"}</span></div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.summary)}</p><span class="read-more">阅读条目 <b>→</b></span></a>`).join("");resultCount.textContent=isHome&&!rawKeyword&&category==="全部"?`每小时更新 · ${visibleItems.length} 篇精选`:`共 ${items.length} 个条目`;const articleCount=document.querySelector("#homeArticleCount"),categoryCount=document.querySelector("#homeCategoryCount");if(articleCount)articleCount.textContent=published.length;if(categoryCount)categoryCount.textContent=new Set(published.map(item=>item.category)).size;const uncovered=rawKeyword.length>=2&&globalMatches.length===0;empty.hidden=visibleItems.length!==0;articleList.hidden=visibleItems.length===0;externalActions.hidden=!uncovered;emptyMessage.textContent=uncovered?`Smart Wiki 暂未收录“${rawKeyword}”，你可以继续在 Google 查找。`:rawKeyword?"当前分类没有匹配内容，请选择“全部条目”查看。":"试试更短的关键词，或者选择其他分类。";if(uncovered){googleLink.href=`https://www.google.com/search?q=${encodeURIComponent(rawKeyword+" 详细介绍 科普")}`;scheduleGapReport(rawKeyword);}else clearTimeout(gapTimer);}
  function selectCategory(value,shouldScroll=false){category=value;document.querySelectorAll("[data-category]").forEach(button=>button.classList.toggle("active",button.dataset.category===value));render();if(shouldScroll)document.querySelector(".content-section").scrollIntoView({behavior:"smooth",block:"start"});const menu=document.querySelector("#sidebar"),shade=document.querySelector("#overlay");menu?.classList.remove("open");shade?.classList.remove("show");}
  document.querySelectorAll("[data-category]").forEach(button=>button.addEventListener("click",()=>selectCategory(button.dataset.category,button.classList.contains("category-nav"))));
  heroInput.addEventListener("input",()=>{topInput.value=heroInput.value;render();});topInput.addEventListener("input",()=>{heroInput.value=topInput.value;render();});
  document.querySelectorAll(".hero-suggestions [data-query]").forEach(button=>button.addEventListener("click",()=>{heroInput.value=button.dataset.query;topInput.value=button.dataset.query;render();heroInput.focus();}));
  const heroCards=[document.querySelector(".panel-feature"),...document.querySelectorAll(".panel-row")],heroItems=(featured.length?featured:articles.filter(item=>[31,36,34].includes(Number(item.id)))).slice(0,3);heroCards.forEach((card,index)=>{const item=heroItems[index];if(!card||!item)return;if(index===0)card.querySelector("div").innerHTML=`<small>${escapeHtml(item.category)}</small><strong>${escapeHtml(item.title)}</strong><p>${escapeHtml(item.summary)}</p>`;else card.innerHTML=`<span><i>${escapeHtml(item.icon||"•")}</i>${escapeHtml(item.title)}</span><b>${escapeHtml(item.category)}</b>`;card.classList.add("featured-link-card");card.tabIndex=0;card.setAttribute("role","link");card.setAttribute("aria-label",`阅读精选文章：${item.title}`);const open=()=>location.href=`article.html?id=${item.id}`;card.addEventListener("click",open);card.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();open();}});});
  document.querySelector("#searchButton")?.addEventListener("click",()=>document.querySelector(".content-section").scrollIntoView({behavior:"smooth"}));document.addEventListener("keydown",event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();topInput.focus();}});
  const sidebar=document.querySelector("#sidebar"),overlay=document.querySelector("#overlay"),menuButton=document.querySelector("#menuButton");menuButton?.addEventListener("click",()=>{sidebar?.classList.add("open");overlay?.classList.add("show");});overlay?.addEventListener("click",()=>{sidebar?.classList.remove("open");overlay.classList.remove("show");});render();}
async function initArticle(){
  const container=document.querySelector("#articleContent");if(!container)return;articles=await syncArticlesWithProject();
  const id=Number(new URLSearchParams(location.search).get("id"))||1;
  const item=articles.find(article=>article.id===id)||articles[0];
  const viewer=getCurrentUser();const canPreview=viewer&&["admin","super_admin"].includes(viewer.role);
  if(item.status!=="published"&&!canPreview){container.innerHTML='<div class="empty-state"><h2>该文章暂未发布</h2><p>请返回知识库浏览其他内容。</p><a class="primary-link" href="index.html">返回首页</a></div>';return;}
  const paragraphs=item.content.split(/\n\s*\n/).filter(Boolean);
  const related=articles.filter(article=>article.category===item.category&&article.id!==item.id).slice(0,3);
  const formattedDate=new Date(item.updatedAt||Date.now()).toLocaleDateString("zh-CN",{year:"numeric",month:"long",day:"numeric"});
  document.title=`${item.title} · Smart Wiki`;
  container.innerHTML=`
    <div class="article-breadcrumb">首页 / ${escapeHtml(item.category)} / ${escapeHtml(item.title)}</div>
    <div class="article-title-row"><div class="card-icon ${item.color}">${escapeHtml(item.icon)}</div><div><span class="article-category">${escapeHtml(item.category)}</span><h1>${escapeHtml(item.title)}</h1></div></div>
    <p class="article-lead">${escapeHtml(item.summary)}</p>
    <div class="article-info"><span>更新于 ${formattedDate}</span><span>约 ${Math.max(3,Math.ceil(item.content.length/180))} 分钟阅读</span><span>${item.status==="published"?"已发布":"预览 · "+item.status}</span></div>
    <div class="article-actions"><button id="favoriteButton">☆ 收藏文章</button><button id="suggestButton">✎ 提交纠错建议</button></div>
    ${item.image?`<figure class="article-cover"><img src="${escapeHtml(item.image)}" alt="${escapeHtml(item.title)}配图"><figcaption>Smart Wiki 原创知识配图</figcaption></figure>`:""}
    <section id="intro"><h2>概念简介</h2><p>${escapeHtml(paragraphs[0]||item.content)}</p></section>
    <section id="details"><h2>深入理解</h2>${paragraphs.slice(1).map(paragraph=>`<p>${escapeHtml(paragraph)}</p>`).join("")}<div class="callout"><strong>学习建议</strong><p>尝试用自己的语言复述这个概念，并找一个生活或项目中的例子验证理解。</p></div></section>
    <section id="keypoints"><h2>核心要点</h2><div class="knowledge-points">${(item.keyPoints||[]).map((point,index)=>`<div><span>${String(index+1).padStart(2,"0")}</span><p>${escapeHtml(point)}</p></div>`).join("")}</div></section>
    <section id="sources"><h2>参考资料</h2><p class="source-note">本文由 Smart Wiki 根据以下权威公开资料整理，内容为中文归纳介绍，并非原文转载。</p><div class="source-list">${(item.sources||[]).map(source=>`<a href="${escapeHtml(source.url)}" target="_blank" rel="noopener noreferrer"><span>↗</span><strong>${escapeHtml(source.title)}</strong><small>${escapeHtml(new URL(source.url).hostname)}</small></a>`).join("")}</div></section>
    <section id="next"><h2>延伸阅读</h2><div class="related-list">${related.filter(article=>article.status==="published").map(article=>`<a href="article.html?id=${article.id}"><span class="card-icon ${article.color}">${escapeHtml(article.icon)}</span><span><strong>${escapeHtml(article.title)}</strong><small>${escapeHtml(article.summary)}</small></span><b>→</b></a>`).join("")}</div><a class="primary-link" href="index.html">返回知识库 →</a></section>`;
  fetch(wikiApiUrl(`/api/articles/${item.id}/view`),{method:"POST",headers:apiHeaders(),keepalive:true}).catch(()=>{});
  if(viewer){addReadingHistory(item.id);const favoriteButton=document.querySelector("#favoriteButton");const updateFavorite=()=>{const active=(getMyState().favorites||[]).includes(item.id);favoriteButton.textContent=active?"★ 已收藏":"☆ 收藏文章";favoriteButton.classList.toggle("active",active);};updateFavorite();favoriteButton.addEventListener("click",()=>{toggleFavorite(item.id);updateFavorite();});document.querySelector("#suggestButton").addEventListener("click",()=>{const message=prompt("请描述需要纠正或补充的内容：");if(!message?.trim())return;const suggestions=getSuggestions();suggestions.unshift({id:Date.now(),articleId:item.id,articleTitle:item.title,message:message.trim(),userId:viewer.id,userName:viewer.name,status:"pending",createdAt:new Date().toISOString()});saveSuggestions(suggestions);alert("建议已提交，感谢你的帮助！");});}else{document.querySelector("#favoriteButton").addEventListener("click",()=>location.href="login.html");document.querySelector("#suggestButton").addEventListener("click",()=>location.href="login.html");}
  document.body.insertAdjacentHTML("beforeend",'<button class="back-to-top" id="backToTop" type="button" aria-label="回到页面顶部" title="回到顶部"><span>↑</span><small>顶部</small></button>');const backToTop=document.querySelector("#backToTop"),updateBackToTop=()=>backToTop.classList.toggle("show",scrollY>520);addEventListener("scroll",updateBackToTop,{passive:true});backToTop.addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}));updateBackToTop();
}
function actionIcon(type){const icons={lock:'<svg viewBox="0 0 24 24"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>',admin:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19 13.5v-3l-2-.7-.7-1.7.9-1.9-2.1-2.1-1.9.9-1.7-.7L10.5 2h-3l-.7 2-1.7.7-1.9-.9-2.1 2.1.9 1.9-.7 1.7-2 .7v3l2 .7.7 1.7-.9 1.9 2.1 2.1 1.9-.9 1.7.7.7 2h3l.7-2 1.7-.7 1.9.9 2.1-2.1-.9-1.9.7-1.7z" transform="translate(2.25 0) scale(.8)"/></svg>',message:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></svg>',logout:'<svg viewBox="0 0 24 24"><path d="M10 5H5v14h5M14 8l4 4-4 4M9 12h9"/></svg>'};return `<span class="action-symbol" aria-hidden="true">${icons[type]}</span>`;}
function enhanceUserActions(){const area=document.querySelector("#userActions");if(!area)return;const password=area.querySelector(".password-link"),admin=area.querySelector('a[href="admin.html"]'),messages=area.querySelector('a[href="messages.html"]'),logoutButton=area.querySelector("#homeLogout"),themeButton=document.querySelector("#themeButton");if(password){password.querySelector("b")?.remove();password.querySelector("span").className="action-label";password.insertAdjacentHTML("afterbegin",actionIcon("lock"));password.title="修改密码";}if(admin){admin.innerHTML=`${actionIcon("admin")}<span class="action-label">后台</span>`;admin.title="管理后台";}if(messages){messages.innerHTML=`${actionIcon("message")}<span class="action-label">消息</span>`;messages.title="消息中心";}if(logoutButton){logoutButton.innerHTML=`${actionIcon("logout")}<span class="action-label">退出</span>`;logoutButton.title="退出登录";if(themeButton)area.append(themeButton);area.append(logoutButton);}}
function initDailyTip(){const tip=document.querySelector("#dailyTip"),close=document.querySelector("#dailyTipClose");if(!tip||!close)return;if(sessionStorage.getItem("smart-wiki-daily-tip-closed")==="1"){tip.hidden=true;return;}close.addEventListener("click",()=>{sessionStorage.setItem("smart-wiki-daily-tip-closed","1");tip.classList.add("is-closing");setTimeout(()=>{tip.hidden=true;},200);});}
async function bootSmartWiki(){await syncCurrentUserWithServer();initTheme();initUserMenu();if(getCurrentUser()&&document.querySelector("#userActions"))document.querySelector("#userActions").insertAdjacentHTML("beforeend",'<a class="manage-link" href="messages.html">消息</a>');enhanceUserActions();initDailyTip();if(document.body.dataset.page==="knowledge")mountKnowledgeBackToTop();initHome();initArticle();}
bootSmartWiki();
if(new URLSearchParams(location.search).get("migrate")==="1"){
  Promise.all([syncUsersWithProject(),syncSearchGapsWithProject()]).then(([users,gaps])=>alert(`迁移完成：${users.length} 个用户，${gaps.length} 条搜索缺口。现在可以使用 localhost 页面。`));
}else{syncUsersWithProject();syncSearchGapsWithProject();}
