const dinoCanvas=document.querySelector("#dinoCanvas"),dctx=dinoCanvas.getContext("2d"),dinoOverlay=document.querySelector("#dinoOverlay"),dinoStart=document.querySelector("#dinoStart"),dinoUser=getCurrentUser();
const ds={running:false,score:0,best:Number(localStorage.getItem("smart-dino-best")||0),level:1,speed:330,last:0,spawn:1.3,sound:true,duck:false,obstacles:[],clouds:[],dust:[],dino:{x:95,y:337,w:58,h:64,vy:0,grounded:true}};
document.querySelector("#dinoUser").innerHTML=dinoUser?`正在以 <strong>${safe(dinoUser.name)}</strong> 的身份奔跑`:`<strong>设备玩家</strong> · 无需登录即可上榜`;
function safe(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function resizeDino(){const r=dinoCanvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2);dinoCanvas.width=Math.round(r.width*ratio);dinoCanvas.height=Math.round(r.height*ratio);dctx.setTransform(dinoCanvas.width/900,0,0,dinoCanvas.height/450,0,0);drawDino();}
function hud(){document.querySelector("#dinoScore").textContent=String(Math.floor(ds.score)).padStart(5,"0");document.querySelector("#dinoBest").textContent=String(Math.max(ds.best,Math.floor(ds.score))).padStart(5,"0");document.querySelector("#dinoLevel").textContent=ds.level;}
function startDino(){Object.assign(ds,{running:true,score:0,level:1,speed:330,last:performance.now(),spawn:1.15,duck:false,obstacles:[],dust:[]});Object.assign(ds.dino,{y:337,vy:0,grounded:true,h:64});dinoOverlay.hidden=true;hud();requestAnimationFrame(dinoLoop);}
function jump(){if(!ds.running){startDino();return;}if(ds.dino.grounded){ds.dino.vy=-700;ds.dino.grounded=false;toneDino(480);}}
function setDuck(on){ds.duck=on;if(ds.dino.grounded){ds.dino.h=on?38:64;ds.dino.y=401-ds.dino.h;}}
function spawnObstacle(){const bird=ds.level>=2&&Math.random()<.31;if(bird){const high=Math.random()<.48;ds.obstacles.push({type:"bird",x:930,y:high?292:350,w:58,h:32,phase:0});}else{const count=Math.random()<Math.min(.18+ds.level*.025,.43)?2:1;ds.obstacles.push({type:"cactus",x:930,y:count===2?342:354,w:count===2?62:34,h:count===2?59:47,count});}ds.spawn=Math.max(.62,1.42-ds.level*.055)+Math.random()*.62;}
function hit(a,b){const ax=a.x+9,ay=a.y+6,aw=a.w-18,ah=a.h-8;return ax<b.x+b.w-5&&ax+aw>b.x+5&&ay<b.y+b.h-4&&ay+ah>b.y+4;}
function updateDino(dt){ds.score+=dt*10*(1+ds.level*.12);ds.level=1+Math.floor(ds.score/120);ds.speed=330+ds.level*34;ds.spawn-=dt;if(ds.spawn<=0)spawnObstacle();const d=ds.dino;d.vy+=1900*dt;d.y+=d.vy*dt;if(d.y+d.h>=401){d.y=401-d.h;d.vy=0;d.grounded=true;}ds.obstacles.forEach(o=>{o.x-=ds.speed*dt;o.phase=(o.phase||0)+dt*12;if(hit(d,o))finishDino();});ds.obstacles=ds.obstacles.filter(o=>o.x>-90);if(d.grounded&&Math.random()<.3)ds.dust.push({x:d.x+8,y:400,vx:-40-Math.random()*60,life:1});ds.dust.forEach(p=>{p.x+=p.vx*dt;p.life-=dt*2});ds.dust=ds.dust.filter(p=>p.life>0);hud();}
function rect(x,y,w,h,color){dctx.fillStyle=color;dctx.fillRect(x,y,w,h);}
function drawDino(){const night=Math.floor(ds.score/450)%2===1,sky=night?"#152039":"#f9fbfa",ink=night?"#dce9e2":"#263b31",soft=night?"#6d7b87":"#afc1b7";rect(0,0,900,450,sky);dctx.globalAlpha=.55;for(let i=0;i<5;i++){const x=(i*223-ds.score*2*(i%2+1))%1050;rect(x,80+i%2*38,58,9,soft);rect(x+12,70+i%2*38,35,12,soft);}dctx.globalAlpha=1;if(night){dctx.fillStyle="#f5edb5";dctx.beginPath();dctx.arc(785,75,27,0,Math.PI*2);dctx.fill();}else{dctx.fillStyle="#f5cf69";dctx.beginPath();dctx.arc(785,75,24,0,Math.PI*2);dctx.fill();}rect(0,401,900,3,ink);for(let i=0;i<22;i++)rect((i*67-ds.score*5)%950,417+(i%3)*7,20,2,soft);
 const d=ds.dino;dctx.fillStyle="#2f9c69";dctx.fillRect(d.x,d.y+10,d.w-13,d.h-10);dctx.fillRect(d.x+25,d.y,d.w-10,27);dctx.fillRect(d.x-9,d.y+23,18,11);dctx.fillStyle="#fff";dctx.fillRect(d.x+39,d.y+7,6,6);dctx.fillStyle=ink;dctx.fillRect(d.x+42,d.y+8,3,3);if(!ds.duck){rect(d.x+8,d.y+d.h-3,12,12,"#2f9c69");rect(d.x+34,d.y+d.h-3,12,12,"#2f9c69");}
 ds.obstacles.forEach(o=>{if(o.type==="cactus"){rect(o.x,o.y,o.w,o.h,"#347e58");rect(o.x-7,o.y+15,10,8,"#347e58");rect(o.x+o.w-3,o.y+25,10,8,"#347e58");}else{const wing=Math.sin(o.phase)>0?9:-3;rect(o.x,o.y+12,o.w,17,ink);rect(o.x+40,o.y+4,24,16,ink);dctx.fillStyle=ink;dctx.beginPath();dctx.moveTo(o.x+18,o.y+18);dctx.lineTo(o.x+2,o.y+wing);dctx.lineTo(o.x+34,o.y+18);dctx.fill();dctx.fillStyle="#fff";dctx.fillRect(o.x+52,o.y+8,4,4);}});ds.dust.forEach(p=>{dctx.globalAlpha=p.life;rect(p.x,p.y,4,4,soft)});dctx.globalAlpha=1;}
function dinoLoop(t){if(!ds.running)return;const dt=Math.min((t-ds.last)/1000,.032);ds.last=t;updateDino(dt);drawDino();if(ds.running)requestAnimationFrame(dinoLoop);}
async function finishDino(){if(!ds.running)return;ds.running=false;toneDino(110);const score=Math.floor(ds.score);if(score>ds.best){ds.best=score;localStorage.setItem("smart-dino-best",score);}hud();document.querySelector("#dinoTitle").textContent=`本局 ${score} 分`;document.querySelector("#dinoText").textContent="正在提交这台设备的最佳成绩…";dinoStart.textContent="再跑一局";dinoOverlay.hidden=false;try{const response=await fetch(wikiApiUrl("/api/game/score"),{method:"POST",headers:apiHeaders(),credentials:"same-origin",body:JSON.stringify({game:"dino-run",score,level:ds.level,playerName:dinoUser?.name||""})}),result=await response.json();if(!response.ok)throw new Error(response.status===405?"请重新启动 Smart Wiki 服务器":"成绩提交失败");document.querySelector("#dinoText").textContent=result.isNewBest?`新纪录！当前全站第 ${result.rank} 名。`:`设备最高分 ${result.bestScore}，继续挑战！`;loadDinoBoard();}catch(error){document.querySelector("#dinoText").textContent=error.message;}}
async function loadDinoBoard(){const list=document.querySelector("#dinoLeaderboard");try{const r=await fetch(wikiApiUrl("/api/game/leaderboard?game=dino-run")),data=await r.json();if(!data.items?.length){list.innerHTML='<li class="empty">还没有成绩，快来成为第一名！</li>';return;}list.innerHTML=data.items.slice(0,20).map((x,i)=>`<li><span class="rank">${i+1}</span><span class="avatar">${safe(x.name).slice(0,1)}</span><span class="name">${safe(x.name)}</span><span class="points">${x.score}</span></li>`).join("");}catch{list.innerHTML='<li class="empty">排行榜暂时无法连接</li>';}}
function toneDino(f){if(!ds.sound)return;try{const a=new (AudioContext||webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.setValueAtTime(.04,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.1);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.1);}catch{}}
addEventListener("keydown",e=>{if([" ","ArrowUp","ArrowDown"].includes(e.key))e.preventDefault();if(e.key===" "||e.key==="ArrowUp")jump();if(e.key==="ArrowDown")setDuck(true)});addEventListener("keyup",e=>{if(e.key==="ArrowDown")setDuck(false)});dinoCanvas.addEventListener("pointerdown",e=>{e.preventDefault();jump()});document.querySelector("#dinoJump").addEventListener("pointerdown",jump);const duck=document.querySelector("#dinoDuck");duck.addEventListener("pointerdown",()=>setDuck(true));["pointerup","pointercancel","pointerleave"].forEach(n=>duck.addEventListener(n,()=>setDuck(false)));dinoStart.addEventListener("click",startDino);document.querySelector("#dinoRefresh").addEventListener("click",loadDinoBoard);document.querySelector("#dinoSound").addEventListener("click",e=>{ds.sound=!ds.sound;e.currentTarget.textContent=`声音：${ds.sound?"开":"关"}`});addEventListener("resize",resizeDino);resizeDino();hud();loadDinoBoard();
