const canvas=document.querySelector("#gameCanvas"),ctx=canvas.getContext("2d"),overlay=document.querySelector("#gameOverlay"),startButton=document.querySelector("#startButton");
const scoreValue=document.querySelector("#scoreValue"),levelValue=document.querySelector("#levelValue"),livesValue=document.querySelector("#livesValue"),comboValue=document.querySelector("#comboValue"),currentUser=getCurrentUser();
const state={running:false,score:0,lives:3,level:1,combo:0,lastTime:0,spawnTimer:0,waveTimer:8,shake:0,items:[],particles:[],keys:{},sound:true,player:{x:332,y:667,w:56,h:56,speed:455}};
document.querySelector("#gameUser").innerHTML=currentUser?`正在以 <strong>${escapeHtml(currentUser.name)}</strong> 的身份挑战`:`<strong>设备玩家</strong> · 无需登录也可参与排名`;
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));}
function resizeCanvas(){const ratio=Math.min(devicePixelRatio||1,2),rect=canvas.getBoundingClientRect();canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);ctx.setTransform(canvas.width/720,0,0,canvas.height/760,0,0);}
function reset(){delete startButton.dataset.login;Object.assign(state,{running:true,score:0,lives:3,level:1,combo:0,lastTime:performance.now(),spawnTimer:0,waveTimer:8,shake:0,items:[],particles:[]});state.player.x=332;updateHud();overlay.hidden=true;requestAnimationFrame(loop);}
function updateHud(){scoreValue.textContent=state.score;levelValue.textContent=state.level;livesValue.textContent="♥ ".repeat(state.lives).trim()||"—";comboValue.textContent=`×${Math.min(1+Math.floor(state.combo/5),5)}`;}
function spawn(options={}){const bad=options.bad??Math.random()<Math.min(.27+state.level*.025,.55),gold=!bad&&Math.random()<.1,size=bad?(options.elite?54:42):gold?37:30,x=options.x??25+Math.random()*(670-size);state.items.push({x,y:options.y??-size,size,bad,gold,elite:!!options.elite,spin:Math.random()*6,speed:options.speed??190+state.level*25+Math.random()*85,vx:bad?(Math.random()-.5)*(45+state.level*8):0,tracking:bad&&Math.random()<Math.min(.12+state.level*.035,.48)});}
function dangerWave(){const gap=80+Math.random()*430;for(let i=0;i<6;i++){const x=12+i*118;if(Math.abs(x-gap)>82)spawn({bad:true,elite:i%2===0,x,y:-50-i*18,speed:245+state.level*22});}state.shake=8;showToast("⚠ 故障风暴：寻找缺口！");}
function collide(a,b){const inset=7;return a.x+inset<b.x+b.size&&a.x+a.w-inset>b.x&&a.y+inset<b.y+b.size&&a.y+a.h-inset>b.y;}
function burst(item,color){for(let i=0;i<9;i++)state.particles.push({x:item.x+item.size/2,y:item.y+item.size/2,vx:(Math.random()-.5)*190,vy:(Math.random()-.5)*190,life:1,color});}
function tone(freq){if(!state.sound)return;try{const ac=new (window.AudioContext||window.webkitAudioContext)(),osc=ac.createOscillator(),gain=ac.createGain();osc.frequency.value=freq;gain.gain.setValueAtTime(.045,ac.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.12);osc.connect(gain).connect(ac.destination);osc.start();osc.stop(ac.currentTime+.12);}catch{}}
function update(dt){const p=state.player;if(state.keys.left)p.x-=p.speed*dt;if(state.keys.right)p.x+=p.speed*dt;p.x=Math.max(6,Math.min(658,p.x));state.level=1+Math.floor(state.score/75);state.spawnTimer-=dt;state.waveTimer-=dt;if(state.spawnTimer<=0){spawn();if(state.level>=3&&Math.random()<.2)spawn({y:-105});state.spawnTimer=Math.max(.14,.56-state.level*.024);}if(state.waveTimer<=0){dangerWave();state.waveTimer=Math.max(5,10-state.level*.35);}
 state.items.forEach(item=>{if(item.tracking){const target=p.x+p.w/2-item.x-item.size/2;item.vx+=Math.sign(target)*38*dt;item.vx=Math.max(-120,Math.min(120,item.vx));}item.x+=item.vx*dt;if(item.x<0||item.x+item.size>720)item.vx*=-1;item.x=Math.max(0,Math.min(720-item.size,item.x));item.y+=item.speed*dt;item.spin+=dt*(item.elite?6:3);if(!item.hit&&collide(p,item)){item.hit=true;if(item.bad){state.lives--;state.combo=0;state.shake=14;burst(item,"#ff5576");tone(120);}else{state.combo++;const multiplier=Math.min(1+Math.floor(state.combo/5),5);state.score+=(item.gold?25:10)*multiplier;burst(item,item.gold?"#ffd95a":"#55e6ff");tone(item.gold?720:520);}}if(!item.bad&&!item.hit&&item.y>760){item.hit=true;state.combo=0;}});state.items=state.items.filter(item=>!item.hit&&item.y<790);state.particles.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt*2.2});state.particles=state.particles.filter(q=>q.life>0);state.shake=Math.max(0,state.shake-35*dt);updateHud();if(state.lives<=0)finish();}
function rounded(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function draw(){ctx.save();if(state.shake)ctx.translate((Math.random()-.5)*state.shake,(Math.random()-.5)*state.shake);const gradient=ctx.createLinearGradient(0,0,0,760);gradient.addColorStop(0,"#090d26");gradient.addColorStop(1,"#111948");ctx.fillStyle=gradient;ctx.fillRect(-12,-12,744,784);for(let i=0;i<60;i++){const x=(i*97)%720,y=(i*151+performance.now()*.012*(i%3+1))%760;ctx.globalAlpha=.18+(i%4)*.12;ctx.fillStyle=i%7?"#fff":"#55e6ff";ctx.fillRect(x,y,i%5===0?2:1,i%5===0?2:1);}ctx.globalAlpha=1;
 state.items.forEach(item=>{ctx.save();ctx.translate(item.x+item.size/2,item.y+item.size/2);ctx.rotate(item.spin);if(item.bad){ctx.shadowBlur=item.elite?24:0;ctx.shadowColor="#ff315c";ctx.fillStyle=item.elite?"#b625ff":"#ff4f72";rounded(-item.size/2,-item.size/2,item.size,item.size,item.elite?16:11);ctx.fill();ctx.strokeStyle="#fff";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-9,-9);ctx.lineTo(9,9);ctx.moveTo(9,-9);ctx.lineTo(-9,9);ctx.stroke();}else{ctx.shadowBlur=22;ctx.shadowColor=item.gold?"#ffd95a":"#55e6ff";ctx.fillStyle=item.gold?"#ffd95a":"#55e6ff";ctx.beginPath();for(let n=0;n<10;n++){const a=-Math.PI/2+n*Math.PI/5,r=n%2?item.size*.22:item.size*.5;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r);}ctx.closePath();ctx.fill();}ctx.restore();});
 state.particles.forEach(q=>{ctx.globalAlpha=q.life;ctx.fillStyle=q.color;ctx.fillRect(q.x,q.y,4,4)});ctx.globalAlpha=1;const p=state.player;ctx.shadowBlur=28;ctx.shadowColor="#7559ff";const pg=ctx.createLinearGradient(p.x,p.y,p.x+p.w,p.y+p.h);pg.addColorStop(0,"#55e6ff");pg.addColorStop(1,"#7559ff");ctx.fillStyle=pg;rounded(p.x,p.y,p.w,p.h,17);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#fff";ctx.font="800 24px system-ui";ctx.textAlign="center";ctx.fillText("S",p.x+p.w/2,p.y+36);ctx.restore();}
function loop(time){if(!state.running)return;const dt=Math.min((time-state.lastTime)/1000,.034);state.lastTime=time;update(dt);draw();if(state.running)requestAnimationFrame(loop);}
async function finish(){state.running=false;draw();document.querySelector("#overlayTitle").textContent=`本局 ${state.score} 分`;document.querySelector("#overlayText").textContent="正在提交你的最佳成绩…";startButton.textContent="再次挑战";overlay.hidden=false;try{const response=await fetch(wikiApiUrl("/api/game/score"),{method:"POST",headers:apiHeaders(),credentials:"same-origin",body:JSON.stringify({score:state.score,level:state.level,playerName:currentUser?.name||""})}),result=await response.json();if(!response.ok)throw new Error(response.status===405?"服务器版本尚未更新，请重新启动 Smart Wiki":"提交失败："+(result.error||response.status));document.querySelector("#overlayText").textContent=result.isNewBest?`新纪录！当前全站第 ${result.rank} 名。`:`已完成，这台设备的最佳成绩是 ${result.bestScore} 分。`;loadBoard();}catch(error){document.querySelector("#overlayText").textContent=error.message;}}
async function loadBoard(){const list=document.querySelector("#leaderboard");try{const response=await fetch(wikiApiUrl("/api/game/leaderboard")),data=await response.json();if(!data.items?.length){list.innerHTML='<li class="leader-loading">还没有成绩，成为第一名吧！</li>';return;}list.innerHTML=data.items.slice(0,20).map((item,index)=>`<li class="${currentUser&&item.userId===currentUser.id?"me":""}"><span class="leader-rank">${index+1}</span><span class="leader-avatar">${escapeHtml(item.name).slice(0,1).toUpperCase()}</span><span class="leader-name"><strong>${escapeHtml(item.name)}</strong><small>等级 ${item.level}</small></span><span class="leader-score"><strong>${item.score}</strong><small>分数</small></span></li>`).join("");}catch{list.innerHTML='<li class="leader-loading">排行榜暂时无法连接</li>';}}
function setDirection(direction,on){state.keys[direction]=on;}function showToast(text){const toast=document.querySelector("#gameToast");toast.textContent=text;toast.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.hidden=true,1700);}
addEventListener("keydown",event=>{if(["ArrowLeft","ArrowRight","a","d","A","D"].includes(event.key))event.preventDefault();if(["ArrowLeft","a","A"].includes(event.key))setDirection("left",true);if(["ArrowRight","d","D"].includes(event.key))setDirection("right",true);});addEventListener("keyup",event=>{if(["ArrowLeft","a","A"].includes(event.key))setDirection("left",false);if(["ArrowRight","d","D"].includes(event.key))setDirection("right",false);});
function bindHold(id,direction){const el=document.querySelector(id);el.addEventListener("pointerdown",event=>{event.preventDefault();setDirection(direction,true)});["pointerup","pointercancel","pointerleave"].forEach(name=>el.addEventListener(name,()=>setDirection(direction,false)));}bindHold("#leftButton","left");bindHold("#rightButton","right");
canvas.addEventListener("pointermove",event=>{if(!state.running||event.pointerType==="mouse"&&event.buttons===0)return;const rect=canvas.getBoundingClientRect();state.player.x=Math.max(6,Math.min(658,(event.clientX-rect.left)/rect.width*720-state.player.w/2));});canvas.addEventListener("pointerdown",event=>{if(state.running)canvas.setPointerCapture(event.pointerId)});
startButton.addEventListener("click",reset);document.querySelector("#refreshBoard").addEventListener("click",loadBoard);document.querySelector("#soundButton").addEventListener("click",event=>{state.sound=!state.sound;event.currentTarget.textContent=`声音：${state.sound?"开":"关"}`;});addEventListener("resize",resizeCanvas);resizeCanvas();draw();loadBoard();
