const byId=id=>document.getElementById(id);
document.querySelectorAll("[data-copy]").forEach(button=>button.addEventListener("click",async()=>{const field=byId(button.dataset.copy);if(!field)return;await navigator.clipboard.writeText(field.value||field.textContent||"");showToolToast("已复制到剪贴板");}));

document.querySelectorAll("[data-json]").forEach(button=>button.addEventListener("click",()=>{const input=byId("jsonInput"),status=byId("jsonStatus");try{const value=JSON.parse(input.value);input.value=button.dataset.json==="format"?JSON.stringify(value,null,2):JSON.stringify(value);status.textContent=`JSON 有效 · ${Array.isArray(value)?value.length+" 个数组项目":Object.keys(value||{}).length+" 个顶级字段"}`;status.style.color="#087443";}catch(error){status.textContent=`格式错误：${error.message}`;status.style.color="#b42318";}}));

function diffLines(left,right){const a=left.split("\n"),b=right.split("\n"),dp=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=a.length-1;i>=0;i--)for(let j=b.length-1;j>=0;j--)dp[i][j]=a[i]===b[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);const out=[];let i=0,j=0;while(i<a.length||j<b.length){if(i<a.length&&j<b.length&&a[i]===b[j]){out.push([" ",a[i]]);i++;j++;}else if(j<b.length&&(i===a.length||dp[i][j+1]>=dp[i+1][j])){out.push(["+",b[j++]]);}else out.push(["-",a[i++]]);}return out;}
byId("compareText").addEventListener("click",()=>{const result=byId("diffResult"),rows=diffLines(byId("diffLeft").value,byId("diffRight").value);result.innerHTML=rows.map(([type,line])=>`<div class="${type==="+"?"diff-add":type==="-"?"diff-remove":""}">${type} ${escapeHtml(line)||" "}</div>`).join("");});
byId("clearDiff").addEventListener("click",()=>{byId("diffLeft").value="";byId("diffRight").value="";byId("diffResult").textContent="对比结果显示在这里";});

let qrCode=null;byId("generateQr").addEventListener("click",()=>{const text=byId("qrInput").value.trim(),output=byId("qrOutput");if(!text)return showToolToast("请先输入网址或文字");if(typeof QRCode==="undefined")return showToolToast("二维码组件加载失败，请检查网络");output.innerHTML="";qrCode=new QRCode(output,{text,width:220,height:220,colorDark:"#111827",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.M});});
byId("downloadQr").addEventListener("click",()=>{const canvas=byId("qrOutput").querySelector("canvas"),image=byId("qrOutput").querySelector("img");const url=canvas?.toDataURL("image/png")||image?.src;if(!url)return showToolToast("请先生成二维码");const link=document.createElement("a");link.href=url;link.download="smart-wiki-qr.png";link.click();});

byId("timestampToDate").addEventListener("click",()=>{let value=Number(byId("timestampInput").value);if(!Number.isFinite(value))return showToolToast("请输入有效时间戳");if(Math.abs(value)<1e12)value*=1000;const date=new Date(value);if(Number.isNaN(date.getTime()))return showToolToast("时间戳无效");const local=new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);byId("datetimeInput").value=local;byId("timeStatus").textContent=`本地：${date.toLocaleString("zh-CN")} · UTC：${date.toISOString()}`;});
byId("dateToTimestamp").addEventListener("click",()=>{const date=new Date(byId("datetimeInput").value);if(Number.isNaN(date.getTime()))return showToolToast("请选择有效日期");byId("timestampInput").value=Math.floor(date.getTime()/1000);byId("timeStatus").textContent=`毫秒时间戳：${date.getTime()}`;});
byId("useNow").addEventListener("click",()=>{const now=new Date();byId("timestampInput").value=Math.floor(now.getTime()/1000);byId("datetimeInput").value=new Date(now-now.getTimezoneOffset()*60000).toISOString().slice(0,16);byId("timeStatus").textContent=`当前本地时间：${now.toLocaleString("zh-CN")}`;});

byId("runCodec").addEventListener("click",()=>{const value=byId("codecInput").value,type=byId("codecType").value,action=byId("codecAction").value;try{let result;if(type==="url")result=action==="encode"?encodeURIComponent(value):decodeURIComponent(value);else result=action==="encode"?btoa(unescape(encodeURIComponent(value))):decodeURIComponent(escape(atob(value.trim())));byId("codecOutput").value=result;}catch{showToolToast("转换失败，请检查输入格式");}});

const lengthInput=byId("passwordLength");lengthInput.addEventListener("input",()=>byId("passwordLengthValue").textContent=lengthInput.value);
byId("generatePassword").addEventListener("click",()=>{const sets=[];if(byId("useUpper").checked)sets.push("ABCDEFGHJKLMNPQRSTUVWXYZ");if(byId("useLower").checked)sets.push("abcdefghijkmnopqrstuvwxyz");if(byId("useNumber").checked)sets.push("23456789");if(byId("useSymbol").checked)sets.push("!@#$%&*+-_=?.");if(!sets.length)return showToolToast("请至少选择一种字符");const all=sets.join(""),length=Number(lengthInput.value),bytes=new Uint32Array(length),pick=chars=>chars[crypto.getRandomValues(new Uint32Array(1))[0]%chars.length];crypto.getRandomValues(bytes);const chars=sets.map(pick);while(chars.length<length)chars.push(all[bytes[chars.length]%all.length]);for(let i=chars.length-1;i>0;i--){const r=crypto.getRandomValues(new Uint32Array(1))[0]%(i+1);[chars[i],chars[r]]=[chars[r],chars[i]];}byId("passwordOutput").value=chars.join("");});byId("generatePassword").click();
