const profileUser=getCurrentUser();if(!profileUser){location.replace("login.html");throw new Error("需要登录");}
const profileArticles=getArticles(),myState=getMyState(),$=selector=>document.querySelector(selector);
const avatarStyles=document.createElement("link");avatarStyles.rel="stylesheet";avatarStyles.href="avatar-settings.css?v=1.0.3";document.head.appendChild(avatarStyles);
function profileEscape(text){const node=document.createElement("div");node.textContent=text??"";return node.innerHTML;}
function renderAvatar(user){const box=$("#profileAvatar");box.innerHTML=user.avatar?`<img src="${user.avatar}" alt="${profileEscape(user.name)} 的头像">`:profileEscape(user.name.slice(0,1));}
function saveProfileUser(user){const users=getUsers(),index=users.findIndex(item=>Number(item.id)===Number(user.id));if(index>=0)users[index]={...users[index],...user};else users.push(user);localStorage.setItem("wiki-users",JSON.stringify(users));setCurrentUser(user);Object.assign(profileUser,user);renderAvatar(user);}
renderAvatar(profileUser);$("#profileName").textContent=profileUser.name;$("#profileEmail").textContent=profileUser.email;

const avatarButton=document.createElement("button");avatarButton.className="secondary-button";avatarButton.textContent="更换头像";
const nameButton=document.createElement("button");nameButton.className="secondary-button profile-name-button";nameButton.textContent="修改昵称";
const passwordButton=document.createElement("a");passwordButton.className="secondary-button profile-password-button";passwordButton.href="change-password.html";passwordButton.textContent="修改密码";
$("#profileLogout").before(avatarButton,nameButton,passwordButton);$("#profileLogout").addEventListener("click",logout);

document.body.insertAdjacentHTML("beforeend",`<div class="avatar-modal" id="avatarModal" hidden><button class="avatar-backdrop" type="button" data-close-avatar aria-label="关闭"></button><section role="dialog" aria-modal="true" aria-labelledby="avatarTitle"><header><div><span class="section-kicker">PROFILE AVATAR</span><h2 id="avatarTitle">选择你的头像</h2><p>选择预设头像，或上传 JPG、PNG 图片。</p></div><button type="button" data-close-avatar aria-label="关闭">×</button></header><div class="avatar-presets">${Array.from({length:8},(_,i)=>`<button type="button" data-avatar="/assets/avatars/avatar-${i+1}.svg"><img src="/assets/avatars/avatar-${i+1}.svg" alt="预设头像 ${i+1}"></button>`).join("")}</div><label class="avatar-upload"><input id="avatarFile" type="file" accept="image/jpeg,image/png"><span>上传 JPG / PNG</span><small>图片会在浏览器中裁剪为正方形，不上传原始文件</small></label><div class="avatar-preview"><span>预览</span><div id="avatarPreview">${avatarMarkup(profileUser,"preview-avatar")}</div></div><footer><button class="secondary-button" type="button" data-close-avatar>取消</button><button class="submit-button compact" id="saveAvatar" type="button" disabled>保存头像</button></footer><p class="avatar-credit">预设头像来自 DiceBear Pixel Art（CC0）。</p></section></div>`);
let selectedAvatar="";
function openAvatar(){selectedAvatar="";$("#saveAvatar").disabled=true;$("#avatarModal").hidden=false;document.body.classList.add("modal-open");}
function closeAvatar(){$("#avatarModal").hidden=true;document.body.classList.remove("modal-open");}
function chooseAvatar(value){selectedAvatar=value;$("#avatarPreview").innerHTML=`<img class="preview-avatar" src="${value}" alt="头像预览">`;$("#saveAvatar").disabled=false;document.querySelectorAll("[data-avatar]").forEach(button=>button.classList.toggle("selected",button.dataset.avatar===value));}
avatarButton.onclick=openAvatar;document.querySelectorAll("[data-close-avatar]").forEach(button=>button.onclick=closeAvatar);document.querySelectorAll("[data-avatar]").forEach(button=>button.onclick=()=>chooseAvatar(button.dataset.avatar));
$("#avatarFile").onchange=async event=>{const file=event.target.files[0];if(!file)return;if(!["image/jpeg","image/png"].includes(file.type)||file.size>3*1024*1024){alert("请选择小于 3 MB 的 JPG 或 PNG 图片");event.target.value="";return;}try{chooseAvatar(await cropAvatar(file));}catch{alert("图片读取失败，请更换一张图片");}};
function cropAvatar(file){return new Promise((resolve,reject)=>{const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{const size=Math.min(image.naturalWidth,image.naturalHeight),canvas=document.createElement("canvas");canvas.width=canvas.height=256;canvas.getContext("2d").drawImage(image,(image.naturalWidth-size)/2,(image.naturalHeight-size)/2,size,size,0,0,256,256);URL.revokeObjectURL(url);resolve(canvas.toDataURL("image/jpeg",.86));};image.onerror=reject;image.src=url;});}
$("#saveAvatar").onclick=async()=>{if(!selectedAvatar)return;const button=$("#saveAvatar");button.disabled=true;try{const response=await fetch(wikiApiUrl("/api/auth/avatar"),{method:"POST",headers:apiHeaders(),body:JSON.stringify({avatar:selectedAvatar})}),result=await response.json();if(!response.ok)throw new Error(result.error||"头像保存失败");saveProfileUser(result.user);closeAvatar();alert("头像已更新");}catch(error){alert(error.message);}finally{button.disabled=false;}};

nameButton.addEventListener("click",async()=>{const latest=getCurrentUser(),newName=prompt("请输入新昵称（2–24 个字符，每 24 小时只能修改一次）：",latest.name);if(newName===null)return;try{const response=await fetch(wikiApiUrl("/api/auth/change-name"),{method:"POST",headers:apiHeaders(),body:JSON.stringify({name:newName})}),result=await response.json();if(!response.ok)throw new Error(result.error||"修改失败");saveProfileUser(result.user);$("#profileName").textContent=result.user.name;alert(`昵称修改成功。下次可修改时间：${new Date(result.nextAllowedAt).toLocaleString("zh-CN")}`);}catch(error){alert(error.message);}});
function renderProfile(){const favorites=(myState.favorites||[]).map(id=>profileArticles.find(item=>item.id===id)).filter(Boolean),history=(myState.history||[]).map(record=>({...record,article:profileArticles.find(item=>item.id===record.id)})).filter(item=>item.article),suggestions=getSuggestions().filter(item=>item.userId===profileUser.id);$("#favoriteCount").textContent=favorites.length;$("#historyCount").textContent=history.length;$("#suggestionCount").textContent=suggestions.length;$("#favoriteList").innerHTML=favorites.length?favorites.map(item=>`<a class="profile-card" href="article.html?id=${item.id}"><span class="card-icon ${item.color}">${profileEscape(item.icon)}</span><div><strong>${profileEscape(item.title)}</strong><small>${profileEscape(item.category)} · ${profileEscape(item.summary)}</small></div><b>→</b></a>`).join(""):'<div class="profile-empty">还没有收藏文章</div>';$("#historyList").innerHTML=history.length?history.map(item=>`<a href="article.html?id=${item.id}"><span><strong>${profileEscape(item.article.title)}</strong><small>${new Date(item.viewedAt).toLocaleString("zh-CN")}</small></span><b>继续阅读 →</b></a>`).join(""):'<div class="profile-empty">还没有阅读记录</div>';$("#suggestionList").innerHTML=suggestions.length?suggestions.map(item=>`<div><span><strong>${profileEscape(item.articleTitle)}</strong><small>${profileEscape(item.message)}</small></span><span class="suggestion-status ${item.status}">${item.status==="pending"?"待处理":item.status==="accepted"?"已采纳":"已关闭"}</span></div>`).join(""):'<div class="profile-empty">还没有提交建议</div>';}
$("#clearHistory").addEventListener("click",()=>{myState.history=[];saveMyState(myState);renderProfile();});renderProfile();
