const lessons=[
 {title:"认识 print()",meta:"输出第一句话",task:"把文字改成 <code>Hello, Python!</code>，然后运行。",explain:"<p><code>print()</code> 会把括号里的内容显示在输出区。文字需要放在英文引号里。</p><pre>print(\"你好\")</pre>",starter:'print("你好，Smart Wiki！")',hints:["print(\"Hello, Python!\")","文字要放在引号里"],check:(code,out)=>out.includes("Hello, Python!")},
 {title:"变量",meta:"保存和使用数据",task:"创建变量 <code>name</code>，值为你的昵称，并用 <code>print(name)</code> 输出。",explain:"<p>变量像一个有名字的盒子。使用等号把值保存进去，不需要提前声明类型。</p><pre>city = \"Singapore\"\nprint(city)</pre>",starter:'name = "小明"\nprint(name)',hints:["修改引号中的昵称","确保保留 print(name)"],check:(code,out)=>/name\s*=/.test(code)&&/print\s*\(\s*name\s*\)/.test(code)&&out.trim().length>0},
 {title:"数字与计算",meta:"让 Python 做数学",task:"计算 <code>12 * 8</code>，并输出结果 <code>96</code>。",explain:"<p>Python 支持 <code>+ - * /</code>。数字不需要引号，否则会被当成文字。</p>",starter:'answer = 10 + 5\nprint(answer)',hints:["把表达式改为 12 * 8","输出 answer"],check:(code,out)=>out.split(/\s+/).includes("96")},
 {title:"条件判断",meta:"让程序做选择",task:"把 <code>score</code> 设为 85，让程序输出“通过”。",explain:"<p><code>if</code> 判断条件是否成立。冒号和四个空格缩进都很重要。</p>",starter:'score = 60\n\nif score >= 80:\n    print("通过")\nelse:\n    print("继续努力")',hints:["修改 score 的数值","85 >= 80 会成立"],check:(code,out)=>out.includes("通过")},
 {title:"列表",meta:"一次保存多个值",task:"在水果列表中加入 <code>\"橙子\"</code>，输出完整列表。",explain:"<p>列表用方括号表示，多个元素用逗号分开。<code>append()</code> 可以在末尾添加元素。</p>",starter:'fruits = ["苹果", "香蕉"]\n# 在下一行添加橙子\n\nprint(fruits)',hints:['fruits.append("橙子")',"代码写在 print 前面"],check:(code,out)=>out.includes("橙子")},
 {title:"for 循环",meta:"重复执行代码",task:"使用循环依次输出 1、2、3。",explain:"<p><code>range(1, 4)</code> 会产生从 1 到 3 的数字。循环内部需要缩进。</p>",starter:'for number in range(1, 4):\n    print(number)',hints:["直接运行并观察结果","range 的结尾数字不包含在内"],check:(code,out)=>/1\s+2\s+3/.test(out.replace(/\r/g,""))},
 {title:"函数",meta:"封装可重复的操作",task:"调用 <code>greet(\"Python\")</code>，让输出包含“你好，Python”。",explain:"<p>函数用 <code>def</code> 定义，参数让同一个函数处理不同数据。</p>",starter:'def greet(name):\n    print("你好，" + name)\n\n# 在这里调用函数\n',hints:['greet("Python")',"函数定义后才可以调用"],check:(code,out)=>out.includes("你好，Python")},
 {title:"小项目：猜数字",meta:"组合所学知识",task:"补全代码：当 <code>guess</code> 等于答案时输出“猜对了！”。",explain:"<p>把变量、条件判断和输出组合起来，完成一个迷你程序。</p>",starter:'answer = 7\nguess = 7\n\nif guess == answer:\n    print("猜对了！")',hints:["先比较 guess 和 answer","比较相等使用两个等号 =="],check:(code,out)=>out.includes("猜对了")},
 {title:"字符串处理",meta:"切片与常用方法",task:"把变量 <code>message</code> 转成大写，并输出 <code>PYTHON</code>。",explain:"<p>字符串提供 <code>upper()</code>、<code>lower()</code>、<code>strip()</code> 和切片等工具。</p>",starter:'message = "python"\nresult = message.upper()\nprint(result)',hints:["使用 message.upper()","把结果交给 print"],check:(code,out)=>out.includes("PYTHON")},
 {title:"用户输入",meta:"让程序与人对话",task:"使用 <code>input()</code> 获取名字，并输出欢迎语。",explain:"<p><code>input()</code> 会暂停程序并等待用户输入，返回的结果是字符串。</p>",starter:'name = input("请输入名字：")\nprint("欢迎你，" + name)',hints:["运行时会弹出输入框","使用 + 连接文字和变量"],check:(code,out)=>/欢迎/.test(out)&&/input\s*\(/.test(code)},
 {title:"字典",meta:"用键值组织资料",task:"创建学生字典并输出其中的 <code>score</code>，结果应为 90。",explain:"<p>字典使用键值对保存资料，通过方括号和键名读取值。</p>",starter:'student = {"name": "小林", "score": 90}\nprint(student["score"])',hints:['使用 student["score"]',"键名也需要引号"],check:(code,out)=>out.split(/\s+/).includes("90")&&/\{/.test(code)},
 {title:"while 循环",meta:"满足条件时持续执行",task:"使用 while 输出 1 到 5，并确保循环能够结束。",explain:"<p><code>while</code> 会在条件为真时反复执行。必须更新控制变量，避免无限循环。</p>",starter:'number = 1\nwhile number <= 5:\n    print(number)\n    number += 1',hints:["初始值是 1","循环内部让 number 加 1"],check:(code,out)=>/1\s+2\s+3\s+4\s+5/.test(out)},
 {title:"返回值与作用域",meta:"让函数产生结果",task:"编写 <code>add(a, b)</code> 并返回两数之和，输出结果 15。",explain:"<p><code>return</code> 把函数计算结果交还给调用位置。函数内部变量通常只在函数中有效。</p>",starter:'def add(a, b):\n    return a + b\n\nresult = add(7, 8)\nprint(result)',hints:["函数内部使用 return","调用 add(7, 8)"],check:(code,out)=>out.split(/\s+/).includes("15")&&/return/.test(code)},
 {title:"异常处理",meta:"应对运行时错误",task:"使用 try/except 捕获除零错误，并输出“不能除以零”。",explain:"<p><code>try</code> 放可能失败的代码，<code>except</code> 负责出现错误后的处理。</p>",starter:'try:\n    result = 10 / 0\nexcept ZeroDivisionError:\n    print("不能除以零")',hints:["捕获 ZeroDivisionError","except 后面需要冒号"],check:(code,out)=>out.includes("不能除以零")&&/except/.test(code)},
 {title:"模块",meta:"使用标准库",task:"导入 <code>math</code>，计算并输出 81 的平方根 9.0。",explain:"<p>模块提供已经写好的功能。标准库随 Python 提供，可以直接 <code>import</code>。</p>",starter:'import math\nanswer = math.sqrt(81)\nprint(answer)',hints:["import math","使用 math.sqrt(81)"],check:(code,out)=>out.includes("9.0")&&/import\s+math/.test(code)},
 {title:"列表推导式",meta:"简洁地生成列表",task:"生成 1 到 5 的平方列表，输出应包含 1、4、9、16、25。",explain:"<p>列表推导式把循环和表达式写进方括号，适合清晰、简单的转换。</p>",starter:'squares = [number ** 2 for number in range(1, 6)]\nprint(squares)',hints:["使用 ** 2 计算平方","range(1, 6)"],check:(code,out)=>["1","4","9","16","25"].every(n=>out.includes(n))},
 {title:"集合与去重",meta:"处理不重复的数据",task:"使用 <code>set</code> 对列表去重，并输出 3 个不同元素。",explain:"<p>集合只保留不重复元素，适合成员检查和去重，但不保证原始顺序。</p>",starter:'numbers = [1, 1, 2, 2, 3]\nunique = set(numbers)\nprint(len(unique))',hints:["set(numbers)","使用 len() 统计数量"],check:(code,out)=>out.split(/\s+/).includes("3")&&/set\s*\(/.test(code)},
 {title:"类与对象",meta:"描述数据与行为",task:"创建 <code>Student</code> 对象，并调用方法输出“Lina 正在学习”。",explain:"<p>类是对象的蓝图，<code>__init__</code> 设置初始资料，<code>self</code> 代表当前对象。</p>",starter:'class Student:\n    def __init__(self, name):\n        self.name = name\n\n    def study(self):\n        print(self.name + " 正在学习")\n\nstudent = Student("Lina")\nstudent.study()',hints:["类名通常使用大写开头","方法第一个参数是 self"],check:(code,out)=>out.includes("Lina 正在学习")&&/class\s+Student/.test(code)},
 {title:"项目：成绩统计",meta:"组合列表、函数与循环",task:"编写函数计算成绩平均值，并输出 85.0。",explain:"<p>综合使用函数、列表、<code>sum()</code> 和 <code>len()</code>，把计算逻辑封装起来。</p>",starter:'def average(scores):\n    return sum(scores) / len(scores)\n\nscores = [80, 90, 85]\nprint(average(scores))',hints:["总和除以数量","sum(scores) / len(scores)"],check:(code,out)=>out.includes("85.0")&&/def\s+average/.test(code)},
 {title:"项目：词频统计",meta:"把文字变成数据",task:"统计句子中 Python 出现的次数，并输出 2。",explain:"<p>先用 <code>split()</code> 拆分文字，再用字典或 <code>count()</code> 统计。</p>",starter:'text = "Python makes learning Python fun"\nwords = text.split()\nprint(words.count("Python"))',hints:["text.split()","words.count(\"Python\")"],check:(code,out)=>out.split(/\s+/).includes("2")},
 {title:"项目：待办清单",meta:"实现增删与展示",task:"创建待办列表，加入两项任务并逐项编号输出。",explain:"<p>这个项目组合列表、<code>append()</code>、循环和 <code>enumerate()</code>。</p>",starter:'todos = []\ntodos.append("学习 Python")\ntodos.append("完成练习")\n\nfor index, task in enumerate(todos, start=1):\n    print(index, task)',hints:["使用 append 添加任务","enumerate 可以提供编号"],check:(code,out)=>out.includes("学习 Python")&&out.includes("完成练习")&&/enumerate/.test(code)},
 {title:"毕业项目：文字冒险",meta:"设计一个完整程序",task:"编写至少两个选择分支，让程序根据 <code>choice</code> 输出不同结局。",explain:"<p>毕业项目需要你自己设计变量、输入、条件分支和输出。先画出选择流程，再开始编码。</p>",starter:'print("你来到一座森林。")\nchoice = "左边"\n\nif choice == "左边":\n    print("你发现了一座宝库！")\nelse:\n    print("你安全回到了营地。")',hints:["先设定 choice 进行测试","使用 if / elif / else 设计分支"],check:(code,out)=>/宝库|营地|结局/.test(out)&&/if\s+/.test(code)&&/else\s*:/.test(code)}
];
let lessonIndex=0,pyodideInstance=null,outputLines=[],cloudRecord={history:[]},completed=new Set(JSON.parse(localStorage.getItem("python-course-completed")||"[]"));const pythonUser=getCurrentUser(),code=document.querySelector("#pythonCode"),highlight=document.querySelector("#codeHighlight"),lineNumbers=document.querySelector("#lineNumbers"),output=document.querySelector("#pythonOutput"),runButton=document.querySelector("#runPython");
function escapeCode(value){return String(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");}
function syntaxHighlight(value){
  const keywords=new Set(["def","if","else","elif","for","while","in","range","return","True","False","None","and","or","not","import","from","as","class","try","except"]),builtins=new Set(["print","len","str","int","float","list","dict","input","append","sum","enumerate"]),pattern=/(&quot;.*?&quot;|&#39;.*?&#39;|#.*$|\b\d+(?:\.\d+)?\b|\b(?:def|if|else|elif|for|while|in|range|return|True|False|None|and|or|not|import|from|as|class|try|except|print|len|str|int|float|list|dict|input|append|sum|enumerate)\b)/g;
  return String(value).split("\n").map(line=>escapeCode(line).replace(pattern,token=>{const plain=token.replace(/&quot;/g,'"').replace(/&#39;/g,"'");const type=token.startsWith("#")?"comment":/^\d/.test(token)?"number":keywords.has(plain)?"keyword":builtins.has(plain)?"builtin":"string";return `<span class="tok-${type}">${token}</span>`;})).join("\n");
}
function updateEditor(){highlight.innerHTML=syntaxHighlight(code.value)+"\n";lineNumbers.textContent=Array.from({length:code.value.split("\n").length},(_,i)=>i+1).join("\n");const before=code.value.slice(0,code.selectionStart),lines=before.split("\n");document.querySelector("#editorPosition").textContent=`第 ${lines.length} 行，第 ${lines.at(-1).length+1} 列`;document.querySelector("#editorGuide").textContent=guideForCode(code.value);}
function guideForCode(value){if(/\t/.test(value))return"Python 建议使用 4 个空格缩进，而不是 Tab。";if(/^(if|for|while|def).*[^:]$/m.test(value))return"if、for、while 和 def 语句末尾通常需要冒号 :";if(/print（|）/.test(value))return"请使用英文半角括号 ()，不要使用中文括号。";if(/“|”|‘|’/.test(value))return"字符串请使用英文引号 \" \" 或 ' '。";return"提示会根据你输入的代码自动变化。按 Ctrl + Enter 可以运行。";}
function renderLessons(){document.querySelector("#lessonList").innerHTML=lessons.map((item,i)=>`<button class="lesson-button ${i===lessonIndex?"active":""} ${completed.has(i)?"done":""}" data-lesson="${i}"><span class="lesson-index">${completed.has(i)?"✓":i+1}</span><span><strong>${item.title}</strong><small>${item.meta}</small></span></button>`).join("");document.querySelector("#courseProgress").textContent=`${completed.size} / ${lessons.length}`;document.querySelector("#courseProgressBar").style.width=`${completed.size/lessons.length*100}%`;}
function loadLesson(index,keepCode=false){lessonIndex=Math.max(0,Math.min(lessons.length-1,index));const item=lessons[lessonIndex];document.querySelector("#lessonNumber").textContent=`LESSON ${String(lessonIndex+1).padStart(2,"0")}`;document.querySelector("#lessonTitle").textContent=item.title;document.querySelector("#lessonExplanation").innerHTML=`${item.explain}<ol class="lesson-steps"><li>先读懂本课概念和语法结构。</li><li>逐行观察下面的完整示例，理解每一行的作用。</li><li>不要复制粘贴，在右侧编辑器亲手输入并运行。</li></ol><strong class="lesson-example-label">完整代码示例（请自行输入）</strong><pre>${escapeCode(item.starter)}</pre>`;document.querySelector("#lessonTask").innerHTML=item.task;document.querySelector("#lessonHints").innerHTML=item.hints.map((hint,i)=>`<button type="button" data-hint="${i}">提示 ${i+1}</button>`).join("");document.querySelector("#previousLesson").disabled=lessonIndex===0;document.querySelector("#nextLesson").disabled=lessonIndex===lessons.length-1;if(!keepCode)code.value="";document.querySelector("#taskResult").hidden=true;output.textContent="等待运行代码…";renderLessons();updateEditor();}
async function ensurePython(){if(pyodideInstance)return pyodideInstance;if(typeof loadPyodide!=="function")throw new Error("Python 运行组件加载失败，请检查网络后刷新页面。");runButton.disabled=true;runButton.textContent="正在加载 Python…";document.querySelector("#pythonRuntime").innerHTML="<i></i>正在加载运行环境…";pyodideInstance=await loadPyodide({stdout:text=>outputLines.push(text),stderr:text=>outputLines.push("错误: "+text),stdin:()=>prompt("Python 程序正在等待输入：")||""});document.querySelector("#pythonRuntime").classList.add("ready");document.querySelector("#pythonRuntime").innerHTML="<i></i>Python 已就绪";return pyodideInstance;}
async function runCode(){runButton.disabled=true;outputLines=[];output.textContent="正在运行…";try{const py=await ensurePython();await py.runPythonAsync(code.value);const text=outputLines.join("\n");output.textContent=text||"程序运行完成（没有输出）";showResult(lessons[lessonIndex].check(code.value,text));}catch(error){output.textContent=String(error).replace(/^PythonError:\s*/,"");showResult(false,"代码还没有运行成功，请根据错误信息检查行号、冒号和缩进。");}finally{runButton.disabled=false;runButton.innerHTML="<span>▶</span> 运行代码";}}
function showResult(success,message=""){const box=document.querySelector("#taskResult");box.hidden=false;box.classList.toggle("fail",!success);document.querySelector("#taskResultIcon").textContent=success?"✓":"!";document.querySelector("#taskResultTitle").textContent=success?"任务完成":"再检查一下";document.querySelector("#taskResultText").textContent=message||(success?`做得很好！进度已保存${pythonUser?"到本机和服务器":"在这台设备"}。`:"程序运行了，但还没有达到本课目标。");document.querySelector("#resultNext").hidden=!success||lessonIndex===lessons.length-1;if(success){completed.add(lessonIndex);localStorage.setItem("python-course-completed",JSON.stringify([...completed]));renderLessons();if(pythonUser)savePythonCloud(false);}}
function pythonToast(message){const toast=document.querySelector("#pythonToast");toast.textContent=message;toast.hidden=false;clearTimeout(pythonToast.timer);pythonToast.timer=setTimeout(()=>toast.hidden=true,1900);}
async function savePythonCloud(saveSnapshot=true){if(!pythonUser){if(saveSnapshot)pythonToast("请先登录，再使用云端保存与历史记录");return null;}try{const response=await fetch(wikiApiUrl("/api/python/progress"),{method:"PUT",headers:apiHeaders(),body:JSON.stringify({lessonIndex,completed:[...completed],code:code.value,output:output.textContent,saveSnapshot})}),data=await response.json();if(response.status===405){if(saveSnapshot)pythonToast("云端功能需要重启 Smart Wiki 服务器后使用");return null;}if(!response.ok)throw new Error(data.error||"保存失败");cloudRecord=data.record;if(saveSnapshot)pythonToast("代码与学习进度已保存到服务器");return cloudRecord;}catch(error){if(saveSnapshot)pythonToast(error.message);return null;}}
async function loadPythonCloud(showHistory=false){if(!pythonUser){if(showHistory)pythonToast("登录后才能查看服务器历史");return;}try{const response=await fetch(wikiApiUrl("/api/python/progress"),{headers:apiHeaders()}),data=await response.json();if(!response.ok)throw new Error(data.error||"读取失败");cloudRecord=data.record||{history:[]};(cloudRecord.completed||[]).forEach(value=>completed.add(value));localStorage.setItem("python-course-completed",JSON.stringify([...completed]));renderLessons();if(showHistory)renderPythonHistory();}catch(error){pythonToast(error.message);}}
function downloadCode(value=code.value,name=`python-lesson-${lessonIndex+1}.py`){const blob=new Blob([value],{type:"text/x-python;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function deletePythonHistory(id){if(!confirm("确定删除这条云端历史吗？删除后无法恢复。"))return;try{const response=await fetch(wikiApiUrl(`/api/python/progress/history/${id}`),{method:"DELETE",headers:apiHeaders()}),data=await response.json();if(!response.ok)throw new Error(data.error||"删除失败");cloudRecord=data.record||{history:[]};renderPythonHistory();pythonToast("云端历史已删除");}catch(error){pythonToast(error.message);}}
function renderPythonHistory(){const modal=document.querySelector("#pythonHistoryModal"),list=document.querySelector("#pythonHistoryList"),items=cloudRecord.history||[];list.innerHTML=items.length?items.map(item=>`<article class="history-entry"><div><strong>第 ${Number(item.lessonIndex)+1} 课 · ${escapeCode(lessons[item.lessonIndex]?.title||"代码练习")}</strong><small>${new Date(item.savedAt).toLocaleString("zh-CN")}</small></div><div><button data-restore-code="${item.id}">恢复</button><button data-download-code="${item.id}">下载</button><button class="history-delete" data-delete-code="${item.id}">删除</button></div><pre>${escapeCode(item.code||"")}</pre></article>`).join(""):'<div class="profile-empty">服务器上还没有保存记录</div>';modal.hidden=false;}
code.addEventListener("input",updateEditor);code.addEventListener("click",updateEditor);code.addEventListener("keyup",updateEditor);code.addEventListener("scroll",()=>{highlight.scrollTop=code.scrollTop;highlight.scrollLeft=code.scrollLeft;lineNumbers.scrollTop=code.scrollTop;});code.addEventListener("keydown",event=>{if(event.key==="Tab"){event.preventDefault();const start=code.selectionStart;code.setRangeText("    ",start,code.selectionEnd,"end");updateEditor();}if(event.key==="Enter"&&event.ctrlKey){event.preventDefault();runCode();}});document.querySelector("#lessonList").addEventListener("click",e=>{const button=e.target.closest("[data-lesson]");if(button)loadLesson(Number(button.dataset.lesson));});document.querySelector("#lessonHints").addEventListener("click",e=>{const button=e.target.closest("[data-hint]");if(button)document.querySelector("#editorGuide").textContent=lessons[lessonIndex].hints[Number(button.dataset.hint)];});document.querySelector("#previousLesson").addEventListener("click",()=>loadLesson(lessonIndex-1));document.querySelector("#nextLesson").addEventListener("click",()=>loadLesson(lessonIndex+1));document.querySelector("#resultNext").addEventListener("click",()=>loadLesson(lessonIndex+1));document.querySelector("#resetCode").addEventListener("click",()=>{code.value="";output.textContent="等待运行代码…";updateEditor();code.focus();});document.querySelector("#clearConsole").addEventListener("click",()=>output.textContent="");document.querySelector("#resetCourse").addEventListener("click",()=>{if(confirm("确定要清除本机的课程进度吗？")){completed.clear();localStorage.removeItem("python-course-completed");loadLesson(0);}});document.querySelector("#savePythonCloud").addEventListener("click",()=>savePythonCloud(true));document.querySelector("#pythonHistory").addEventListener("click",()=>loadPythonCloud(true));document.querySelector("#downloadPython").addEventListener("click",()=>downloadCode());document.querySelectorAll("[data-close-history]").forEach(item=>item.addEventListener("click",()=>document.querySelector("#pythonHistoryModal").hidden=true));document.querySelector("#pythonHistoryList").addEventListener("click",event=>{const restore=event.target.closest("[data-restore-code]"),download=event.target.closest("[data-download-code]"),remove=event.target.closest("[data-delete-code]"),id=Number(restore?.dataset.restoreCode||download?.dataset.downloadCode||remove?.dataset.deleteCode),item=(cloudRecord.history||[]).find(entry=>entry.id===id);if(!item)return;if(remove){deletePythonHistory(id);return;}if(restore){loadLesson(item.lessonIndex,true);code.value=item.code;output.textContent=item.output||"等待运行代码…";updateEditor();document.querySelector("#pythonHistoryModal").hidden=true;pythonToast("历史代码已恢复到编辑器");}if(download)downloadCode(item.code,`python-history-${item.id}.py`);});runButton.addEventListener("click",runCode);loadLesson(0);loadPythonCloud(false);
