const surfCanvas=document.querySelector("#surfCanvas"),sctx=surfCanvas.getContext("2d"),surfOverlay=document.querySelector("#surfOverlay"),surfStart=document.querySelector("#surfStart"),surfAccount=getCurrentUser();
const ss={running:false,score:0,level:1,lastLevel:1,lives:3,energy:35,speed:270,last:0,spawn:0,boosting:false,sound:true,hitTimer:0,objects:[],foam:[],keys:{},player:{x:348,y:650,w:54,h:76,speed:370}};
document.querySelector("#surfUser").innerHTML=surfAccount?`正在以 <strong>${esc(surfAccount.name)}</strong> 的身份冲浪`:`<strong>设备玩家</strong> · 无需登录即可上榜`;
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function resizeSurf(){const r=surfCanvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2);surfCanvas.width=Math.round(r.width*ratio);surfCanvas.height=Math.round(r.height*ratio);sctx.setTransform(surfCanvas.width/760,0,0,surfCanvas.height/800,0,0);drawSurf();}
function hudSurf(){document.querySelector("#surfScore").textContent=String(Math.floor(ss.score)).padStart(5,"0");document.querySelector("#surfLevel").textContent=ss.level;document.querySelector("#surfLives").textContent="♥ ".repeat(ss.lives).trim()||"—";document.querySelector("#surfBoost").style.width=`${ss.energy}%`;}
function startSurf(){Object.assign(ss,{running:true,score:0,level:1,lastLevel:1,lives:3,energy:35,speed:270,last:performance.now(),spawn:.25,boosting:false,hitTimer:0,objects:[],foam:[]});Object.assign(ss.player,{x:348,y:650});surfOverlay.hidden=true;hudSurf();requestAnimationFrame(surfLoop);}
function spawnSurf(){const roll=Math.random(),type=roll<.1?"energy":roll<.23?"buoy":roll<.5?"rock":roll<.7?"log":roll<.9?"whirlpool":"ramp",sizes={energy:[28,28],buoy:[30,45],rock:[54,46],log:[78,28],whirlpool:[62,42],ramp:[55,42]},[w,h]=sizes[type],make=(kind,x,y,width=w,height=h)=>ss.objects.push({type:kind,x,y,w:width,h:height,phase:Math.random()*6,hit:false,vx:(kind==="whirlpool"||kind==="buoy")&&ss.level>=4?(Math.random()<.5?-1:1)*(35+ss.level*4):0});make(type,22+Math.random()*(716-w),-h-10);
 if(ss.level>=3&&Math.random()<Math.min(.18+ss.level*.025,.52))make(Math.random()<.5?"rock":"buoy",22+Math.random()*670,-125,Math.random()<.5?48:30,Math.random()<.5?42:45);if(ss.level>=7&&Math.random()<.24){const gap=130+Math.random()*430;for(let x=20;x<740;x+=120)if(Math.abs(x-gap)>85)make("rock",x,-210-Math.random()*35,48,42);toastSurf("⚠ 礁石群来袭");}ss.spawn=Math.max(.16,.65-ss.level*.042)+Math.random()*Math.max(.16,.34-ss.level*.012);}
function collision(a,b){return a.x+9<b.x+b.w-5&&a.x+a.w-9>b.x+5&&a.y+10<b.y+b.h-5&&a.y+a.h-8>b.y+5;}
function damage(o){if(ss.hitTimer>0)return;ss.lives--;ss.hitTimer=1.3;o.hit=true;ss.boosting=false;toneSurf(115);toastSurf("撞上障碍，失去一颗生命");if(ss.lives<=0)finishSurf();}
function updateSurf(dt){const p=ss.player;if(ss.keys.left)p.x-=p.speed*dt;if(ss.keys.right)p.x+=p.speed*dt;if(ss.keys.up)p.y-=p.speed*.75*dt;if(ss.keys.down)p.y+=p.speed*.75*dt;p.x=Math.max(8,Math.min(698,p.x));p.y=Math.max(300,Math.min(710,p.y));ss.level=1+Math.floor(ss.score/75);if(ss.level>ss.lastLevel){ss.lastLevel=ss.level;toneSurf(740);toastSurf(`海域等级 ${ss.level} · 水流加速`);}const wantsBoost=ss.keys.boost&&ss.energy>0;if(wantsBoost){ss.boosting=true;ss.energy=Math.max(0,ss.energy-dt*30);}else{ss.boosting=false;ss.energy=Math.min(100,ss.energy+dt*2);}ss.speed=Math.min(760,270+ss.level*42)+(ss.boosting?190:0);ss.score+=dt*(15+ss.level*1.8)*(ss.boosting?1.7:1);ss.spawn-=dt;if(ss.spawn<=0)spawnSurf();ss.hitTimer=Math.max(0,ss.hitTimer-dt);
 ss.objects.forEach(o=>{o.y+=ss.speed*dt;o.x+=(o.vx||0)*dt;if(o.x<5||o.x+o.w>755)o.vx=-(o.vx||0);o.x=Math.max(5,Math.min(755-o.w,o.x));o.phase+=dt*(4+ss.level*.2);if(!o.hit&&collision(p,o)){if(o.type==="energy"){o.hit=true;ss.energy=Math.min(100,ss.energy+30);ss.score+=35;toneSurf(650);}else if(o.type==="ramp"){o.hit=true;ss.score+=60;ss.energy=Math.min(100,ss.energy+15);toneSurf(820);toastSurf("完美飞跃 +60");}else damage(o);}});ss.objects=ss.objects.filter(o=>!o.hit&&o.y<850);for(let i=0;i<(ss.boosting?3:1);i++)ss.foam.push({x:p.x+p.w/2+(Math.random()-.5)*28,y:p.y+p.h-5,vx:(Math.random()-.5)*45,life:1});ss.foam.forEach(f=>{f.x+=f.vx*dt;f.y+=ss.speed*.55*dt;f.life-=dt*2.5});ss.foam=ss.foam.filter(f=>f.life>0);hudSurf();}
function drawSurf(){const g=sctx.createLinearGradient(0,0,0,800);g.addColorStop(0,"#36cad3");g.addColorStop(.55,"#078dac");g.addColorStop(1,"#055e88");sctx.fillStyle=g;sctx.fillRect(0,0,760,800);for(let i=0;i<15;i++){const y=(i*83+ss.score*7)%900-60;sctx.globalAlpha=.18;sctx.strokeStyle="#d9ffff";sctx.lineWidth=3;sctx.beginPath();sctx.moveTo((i*139)%500-50,y);sctx.quadraticCurveTo(330,y-18,810,y+5);sctx.stroke();}sctx.globalAlpha=1;
 ss.objects.forEach(o=>{sctx.save();sctx.translate(o.x,o.y);if(o.type==="rock"){sctx.fillStyle="#526b72";sctx.beginPath();sctx.moveTo(0,o.h);sctx.lineTo(12,9);sctx.lineTo(34,0);sctx.lineTo(o.w,o.h);sctx.fill();}else if(o.type==="log"){sctx.fillStyle="#754a2d";sctx.beginPath();sctx.roundRect(0,5,o.w,o.h-5,12);sctx.fill();sctx.strokeStyle="#b98554";sctx.stroke();}else if(o.type==="buoy"){sctx.fillStyle="#ff566d";sctx.beginPath();sctx.arc(o.w/2,18,14,0,Math.PI*2);sctx.fill();sctx.fillStyle="#fff";sctx.fillRect(2,15,26,7);}else if(o.type==="energy"){sctx.shadowBlur=18;sctx.shadowColor="#ffe76b";sctx.fillStyle="#ffe76b";sctx.beginPath();sctx.arc(14,14,12,0,Math.PI*2);sctx.fill();sctx.fillStyle="#087f9b";sctx.font="800 16px system-ui";sctx.textAlign="center";sctx.fillText("⚡",14,20);}else if(o.type==="whirlpool"){sctx.strokeStyle="#bceef3";sctx.lineWidth=5;for(let r=8;r<30;r+=9){sctx.beginPath();sctx.arc(31,20,r,o.phase,o.phase+Math.PI*1.45);sctx.stroke();}}else{sctx.fillStyle="#f3a94d";sctx.beginPath();sctx.moveTo(0,o.h);sctx.lineTo(o.w/2,0);sctx.lineTo(o.w,o.h);sctx.fill();sctx.fillStyle="#fff";sctx.fillRect(13,28,29,5);}sctx.restore();});
 ss.foam.forEach(f=>{sctx.globalAlpha=f.life;sctx.fillStyle="#d9ffff";sctx.beginPath();sctx.arc(f.x,f.y,3,0,Math.PI*2);sctx.fill()});sctx.globalAlpha=ss.hitTimer>0&&Math.floor(ss.hitTimer*10)%2?0.25:1;const p=ss.player;sctx.save();sctx.translate(p.x+p.w/2,p.y+p.h/2);const tilt=ss.keys.left?-.22:ss.keys.right?.22:0;sctx.rotate(tilt);sctx.fillStyle="#f8fafc";sctx.beginPath();sctx.ellipse(0,8,18,39,0,0,Math.PI*2);sctx.fill();sctx.fillStyle="#734bd6";sctx.beginPath();sctx.arc(0,-17,13,0,Math.PI*2);sctx.fill();sctx.fillStyle="#102c4b";sctx.fillRect(-8,-6,16,25);sctx.strokeStyle="#ffe0bd";sctx.lineWidth=6;sctx.beginPath();sctx.moveTo(-5,1);sctx.lineTo(-20,15);sctx.moveTo(5,1);sctx.lineTo(20,15);sctx.stroke();sctx.restore();sctx.globalAlpha=1;}
function surfLoop(time){if(!ss.running)return;const dt=Math.min((time-ss.last)/1000,.033);ss.last=time;updateSurf(dt);drawSurf();if(ss.running)requestAnimationFrame(surfLoop);}
async function finishSurf(){if(!ss.running)return;ss.running=false;drawSurf();const score=Math.floor(ss.score);document.querySelector("#surfTitle").textContent=`航行 ${score} 分`;document.querySelector("#surfText").textContent="正在提交这台设备的最好成绩…";surfStart.textContent="再次冲浪";surfOverlay.hidden=false;try{const r=await fetch(wikiApiUrl("/api/game/score"),{method:"POST",headers:apiHeaders(),credentials:"same-origin",body:JSON.stringify({game:"surf-run",score,level:ss.level,playerName:surfAccount?.name||""})}),data=await r.json();if(!r.ok)throw new Error(r.status===405?"请重新启动 Smart Wiki 服务器":"成绩提交失败");document.querySelector("#surfText").textContent=data.isNewBest?`新纪录！当前全站第 ${data.rank} 名。`:`设备最高分 ${data.bestScore}，继续挑战！`;loadSurfBoard();}catch(e){document.querySelector("#surfText").textContent=e.message;}}
async function loadSurfBoard(){const list=document.querySelector("#surfLeaderboard");try{const r=await fetch(wikiApiUrl("/api/game/leaderboard?game=surf-run")),data=await r.json();if(!data.items?.length){list.innerHTML='<li class="empty">还没有成绩，成为第一位冲浪者吧！</li>';return;}list.innerHTML=data.items.slice(0,20).map((x,i)=>`<li><span class="rank">${i+1}</span><span class="avatar">${esc(x.name).slice(0,1)}</span><span class="name">${esc(x.name)}</span><span class="points">${x.score}</span></li>`).join("");}catch{list.innerHTML='<li class="empty">排行榜暂时无法连接</li>';}}
function toneSurf(f){if(!ss.sound)return;try{const a=new (AudioContext||webkitAudioContext)(),o=a.createOscillator(),v=a.createGain();o.frequency.value=f;v.gain.setValueAtTime(.04,a.currentTime);v.gain.exponentialRampToValueAtTime(.001,a.currentTime+.12);o.connect(v).connect(a.destination);o.start();o.stop(a.currentTime+.12);}catch{}}function toastSurf(t){const e=document.querySelector("#surfToast");e.textContent=t;e.hidden=false;clearTimeout(toastSurf.timer);toastSurf.timer=setTimeout(()=>e.hidden=true,1400);}
function keySurf(k,on){if(["ArrowLeft","a","A"].includes(k))ss.keys.left=on;if(["ArrowRight","d","D"].includes(k))ss.keys.right=on;if(["ArrowUp","w","W"].includes(k))ss.keys.up=on;if(["ArrowDown","s","S"].includes(k))ss.keys.down=on;if(k===" ")ss.keys.boost=on;}addEventListener("keydown",e=>{if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"," ","w","a","s","d","W","A","S","D"].includes(e.key))e.preventDefault();keySurf(e.key,true)});addEventListener("keyup",e=>keySurf(e.key,false));
function hold(id,key){const e=document.querySelector(id);e.addEventListener("pointerdown",x=>{x.preventDefault();ss.keys[key]=true});["pointerup","pointercancel","pointerleave"].forEach(n=>e.addEventListener(n,()=>ss.keys[key]=false));}hold("#surfLeft","left");hold("#surfRight","right");hold("#surfDash","boost");surfCanvas.addEventListener("pointermove",e=>{if(!ss.running||e.pointerType==="mouse"&&e.buttons===0)return;const r=surfCanvas.getBoundingClientRect();ss.player.x=Math.max(8,Math.min(698,(e.clientX-r.left)/r.width*760-27));ss.player.y=Math.max(300,Math.min(710,(e.clientY-r.top)/r.height*800-38));});surfCanvas.addEventListener("pointerdown",e=>{if(ss.running)surfCanvas.setPointerCapture(e.pointerId)});surfStart.addEventListener("click",startSurf);document.querySelector("#surfRefresh").addEventListener("click",loadSurfBoard);document.querySelector("#surfSound").addEventListener("click",e=>{ss.sound=!ss.sound;e.currentTarget.textContent=`声音：${ss.sound?"开":"关"}`});addEventListener("resize",resizeSurf);resizeSurf();hudSurf();loadSurfBoard();
