(()=>{const saved=localStorage.getItem("wiki-theme"),prefersDark=globalThis.matchMedia?.("(prefers-color-scheme: dark)").matches;document.documentElement.classList.toggle("dark",saved?saved==="dark":Boolean(prefersDark));document.documentElement.dataset.themeSource=saved?"manual":"system";})();
const CONTENT_VERSION=9;
const DEFAULT_ARTICLES=[
  {id:1,title:"HTML",category:"编程",icon:"<>",color:"blue",summary:"构建网页内容与语义结构的基础标记语言，是前端学习的第一站。",content:"HTML 的全称是 HyperText Markup Language（超文本标记语言）。它不负责复杂运算，而是通过标签描述网页中标题、段落、图片、链接和表格等内容的意义。\n\n一份结构良好的 HTML 文档通常包含 head 和 body。head 保存标题、编码和页面说明；body 则承载用户能够看到的主要内容。使用 header、main、article 等语义化标签，可以帮助搜索引擎和辅助阅读设备理解页面。\n\n学习 HTML 时，重点不是记住所有标签，而是理解内容结构。先判断一段内容是什么，再选择合适的标签表达它。",updatedAt:"2026-08-03"},
  {id:2,title:"CSS",category:"编程",icon:"#",color:"purple",summary:"控制网页颜色、字体、间距和布局，让结构清晰地呈现在用户面前。",content:"CSS 是层叠样式表，用于描述 HTML 元素应该如何显示。它通过选择器找到元素，再使用属性设置颜色、字号、边距、边框和布局。\n\n“层叠”表示多条规则可能同时影响一个元素。浏览器会结合规则来源、选择器优先级和书写顺序，决定最终采用哪一条样式。理解盒模型、继承和优先级，是掌握 CSS 的关键。\n\n现代网页布局常使用 Flexbox 和 Grid。前者适合一维排列，后者适合二维网格。响应式设计则通过媒体查询，让同一页面适应电脑、平板和手机。",updatedAt:"2026-08-03"},
  {id:3,title:"JavaScript",category:"编程",icon:"JS",color:"orange",summary:"让网页响应用户操作、处理数据并动态更新内容的编程语言。",content:"JavaScript 是浏览器原生支持的编程语言。它可以读取页面元素、处理按钮点击、验证表单，并在不刷新整个页面的情况下更新内容。\n\n变量用于保存数据，函数用于封装可重复执行的逻辑，条件与循环负责控制程序流程。数组和对象则是组织多条数据的常用方式。\n\n浏览器把网页表示为 DOM 树。JavaScript 可以通过 DOM API 查找和修改节点，也可以监听 click、input 等事件。学习时应先掌握基础语法，再逐步理解异步请求、模块和工程化工具。",updatedAt:"2026-08-03"},
  {id:4,title:"太阳系",category:"科学",icon:"☼",color:"yellow",summary:"由太阳及所有受其引力约束的行星、卫星和小天体组成的天体系统。",content:"太阳系形成于约 46 亿年前的一团星际气体和尘埃。物质在引力作用下聚集，中心区域形成太阳，周围盘状物质逐渐形成行星和其他小天体。\n\n八颗行星按距离太阳由近到远排列为水星、金星、地球、火星、木星、土星、天王星和海王星。前四颗主要由岩石构成，后四颗体积更大，以气体或冰物质为主。\n\n太阳占太阳系总质量的绝大部分，其引力维持天体轨道。研究太阳系不仅帮助我们理解地球环境，也为寻找太阳系外的宜居世界提供参照。",updatedAt:"2026-08-03"},
  {id:5,title:"光合作用",category:"科学",icon:"♧",color:"green",summary:"植物利用光能合成有机物，并向环境释放氧气的重要生命过程。",content:"光合作用主要发生在植物叶片细胞的叶绿体中。叶绿素吸收太阳光能，植物利用这些能量，把水和二氧化碳转化为葡萄糖，同时释放氧气。\n\n这一过程包含相互联系的两个阶段。光反应捕获能量并分解水；随后的碳反应利用能量固定二氧化碳，合成有机物。\n\n光合作用是多数生态系统能量的起点，也是地球大气中氧气的重要来源。光照强度、温度、水分和二氧化碳浓度都会影响其效率。",updatedAt:"2026-08-03"},
  {id:6,title:"丝绸之路",category:"历史",icon:"◇",color:"red",summary:"连接古代欧亚大陆的贸易和文化交流网络，而非单独的一条道路。",content:"丝绸之路由多条陆路与海路组成，连接东亚、中亚、西亚、欧洲和北非。丝绸是著名商品，但香料、玻璃器、金属、马匹和药材同样在网络中流通。\n\n商旅通常不会走完整条路线。货物会经过许多市场与中间商逐段转运，沿线城市因此成为商业和文化中心。\n\n丝绸之路传播的不只是商品，还包括宗教、艺术、技术和科学知识。它说明不同文明并非孤立发展，而是长期通过人员流动彼此影响。",updatedAt:"2026-08-03"},
  {id:7,title:"HTTP 与 HTTPS",category:"编程",icon:"//",color:"blue",summary:"浏览器与服务器交换网页数据时使用的核心通信协议。",content:"HTTP 规定了客户端和服务器交换信息的方式。浏览器发送请求，请求中包含方法、地址和相关信息；服务器处理后返回状态码、响应头和内容。\n\n常见方法包括 GET、POST、PUT 和 DELETE。状态码 200 表示请求成功，404 表示资源不存在，500 通常表示服务器内部发生错误。\n\nHTTPS 在 HTTP 外加入加密保护，可验证网站身份并降低通信内容被窃听或篡改的风险。涉及账号、支付或个人数据的网站都应使用 HTTPS。",updatedAt:"2026-08-03"},
  {id:8,title:"Git 版本控制",category:"编程",icon:"G",color:"orange",summary:"记录文件变化、支持协作开发，并让代码历史可以安全追踪。",content:"Git 是分布式版本控制系统。每次提交都会记录一组有意义的文件变化，并附带作者、时间和说明，因此开发者可以查看历史或恢复到过去状态。\n\n工作区保存正在编辑的文件，暂存区用于挑选下一次提交的内容，仓库则保存已经提交的历史。理解这三个区域，有助于掌握 add、commit 和 restore 等操作。\n\n分支允许开发者在不影响主线的情况下尝试新功能。多人协作时，应保持提交范围清晰，并通过代码审查合并变更。",updatedAt:"2026-08-03"},
  {id:9,title:"数据库基础",category:"编程",icon:"DB",color:"purple",summary:"以结构化方式保存、查询和管理大量持久数据的系统。",content:"数据库用于长期保存应用数据。关系型数据库把数据组织成表，通过行表示记录、列表示字段，并利用主键唯一识别每条记录。\n\nSQL 是操作关系型数据库的常用语言，可以查询、插入、更新和删除数据。设计表结构时，需要减少重复信息，同时保留实体之间清晰的关联。\n\n索引能加快查询，但也会占用空间并增加写入成本。真实项目还需要考虑备份、权限、事务和并发访问，避免数据丢失或出现不一致。",updatedAt:"2026-08-03"},
  {id:10,title:"API 接口",category:"编程",icon:"{}",color:"green",summary:"让不同软件按照约定交换数据和调用功能的一组规则。",content:"API 可以理解为软件之间的服务窗口。调用者不需要了解内部实现，只需按照文档提供参数，就能获得约定格式的结果。\n\nWeb API 常通过 HTTP 工作，并使用 JSON 传递数据。良好的接口会使用清晰的资源地址、合适的请求方法和准确的状态码，还会对输入进行验证。\n\n接口设计需要考虑身份认证、访问权限、错误说明和版本兼容。前端与后端分离的应用通常正是通过 API 进行通信。",updatedAt:"2026-08-03"},
  {id:11,title:"人工智能",category:"科学",icon:"AI",color:"purple",summary:"研究如何让机器完成感知、推理、学习和决策任务的领域。",content:"人工智能是一个广泛领域，目标是让计算机完成通常需要人类智能的任务，例如识别图像、理解语言、规划路线和辅助决策。\n\n机器学习是实现人工智能的重要方法。模型从数据中寻找规律，而不是由开发者写出每一条判断规则。深度学习则使用多层神经网络处理复杂模式。\n\n人工智能的结果受训练数据、目标设计和使用环境影响。评估系统时不仅要关注准确率，也要考虑偏差、隐私、可解释性和错误带来的后果。",updatedAt:"2026-08-03"},
  {id:12,title:"DNA 与遗传",category:"科学",icon:"∞",color:"green",summary:"DNA 储存生命遗传信息，并指导细胞制造维持生命所需的分子。",content:"DNA 是脱氧核糖核酸，由四种碱基组成。碱基排列顺序承载遗传信息，DNA 双螺旋的互补结构使其能够在细胞分裂前准确复制。\n\n基因是 DNA 上具有功能的片段，许多基因包含制造蛋白质的信息。蛋白质参与细胞结构、化学反应和信号传递，从而影响生物性状。\n\n性状通常由基因与环境共同决定，并非所有特征都能用单一基因解释。突变会改变 DNA 序列，它既可能有害或无明显影响，也为生物演化提供变异来源。",updatedAt:"2026-08-03"},
  {id:13,title:"板块构造",category:"科学",icon:"△",color:"red",summary:"解释大陆移动、山脉形成、地震和火山活动的地球科学理论。",content:"地球最外层并不是完整不动的外壳，而是由多个岩石圈板块组成。板块在较软的地幔上缓慢移动，每年速度通常只有几厘米。\n\n板块边界分为张裂、汇聚和转换三类。张裂边界产生新地壳，汇聚边界可能形成山脉或俯冲带，转换边界则常因板块水平错动引发地震。\n\n大陆轮廓、相同化石分布、海底扩张和地震带位置都为板块构造提供了证据。这一理论把许多地质现象联系成统一体系。",updatedAt:"2026-08-03"},
  {id:14,title:"牛顿运动定律",category:"科学",icon:"F",color:"blue",summary:"描述物体运动如何受到力影响的三条经典力学基本规律。",content:"第一定律指出，没有合外力时，物体会保持静止或匀速直线运动，这种性质称为惯性。第二定律说明物体的加速度取决于合力与质量，常写作 F=ma。\n\n第三定律指出，两个物体相互作用时，作用力与反作用力大小相等、方向相反，并分别作用在不同物体上。\n\n三条定律适合解释日常尺度和速度下的运动，从车辆加速到卫星轨道都能应用。接近光速或微观尺度时，则需要相对论或量子力学。",updatedAt:"2026-08-03"},
  {id:15,title:"工业革命",category:"历史",icon:"⚙",color:"orange",summary:"机器生产、能源利用和社会组织发生深刻变化的历史进程。",content:"工业革命首先在 18 世纪后期的英国明显发展。纺织机械、蒸汽动力和工厂制度提高了生产能力，并改变了商品制造方式。\n\n煤炭与蒸汽机推动矿业、铁路和轮船发展，运输成本下降，市场联系更加紧密。人口向城市集中，同时形成新的劳动关系和社会阶层。\n\n工业化带来物质增长，也造成恶劣劳动条件、城市污染和资源消耗。理解工业革命，需要同时观察技术创新、资本、制度和普通人的生活变化。",updatedAt:"2026-08-03"},
  {id:16,title:"古埃及文明",category:"历史",icon:"𓂀",color:"yellow",summary:"围绕尼罗河发展，并延续数千年的古代文明。",content:"尼罗河周期性泛滥为河谷带来肥沃泥土，使古埃及农业能够支持城市、政府和大型工程。法老既是政治统治者，也具有重要宗教地位。\n\n古埃及人发展了象形文字、历法、测量技术和复杂的宗教体系。金字塔是古王国时期王室墓葬工程，也反映了社会组织与资源调动能力。\n\n古埃及历史并非始终统一稳定，而是经历多个王国时期和分裂阶段。考古遗迹、铭文与纸草文献帮助现代人重建其社会生活。",updatedAt:"2026-08-03"},
  {id:17,title:"文艺复兴",category:"历史",icon:"R",color:"purple",summary:"欧洲文化、艺术和知识领域在中世纪后期发生的重要转变。",content:"文艺复兴大约从 14 世纪的意大利城市兴起，随后影响欧洲其他地区。学者重新研究古希腊罗马作品，并以新的方式讨论人、自然和社会。\n\n艺术家更加关注透视、人体结构和现实观察。印刷术的推广降低了书籍复制成本，使思想能够更快传播。\n\n文艺复兴不是与中世纪完全割裂的突然事件，而是长期变化的一部分。商业城市、赞助制度、古典文献流传和跨地区交流都推动了它的发展。",updatedAt:"2026-08-03"},
  {id:18,title:"活字印刷术",category:"历史",icon:"字",color:"red",summary:"使用可重复排列的单字印版，提高文字复制灵活性的印刷技术。",content:"活字印刷的核心是把单个文字制成可以重复使用的字模，排版完成后涂墨印刷，再拆开用于下一页。北宋毕昇使用胶泥活字，是早期重要实践。\n\n不同地区的文字系统、材料条件和市场需求，会影响活字印刷的推广方式。木版印刷在东亚长期保持优势，因为它适合保存整页版面并再次印刷。\n\n印刷技术降低了复制知识的成本，促进书籍传播、教育和公共讨论。技术影响社会的过程通常并非单一发明决定，而与制度和使用环境密切相关。",updatedAt:"2026-08-03"}
  ,{id:19,title:"网络安全入门",category:"编程",icon:"盾",color:"blue",summary:"理解常见网络威胁、防护原则与安全习惯，建立保护账户、设备和数据的基础意识。",content:"网络安全的目标不只是“防黑客”，还包括保护信息的机密性、完整性和可用性。机密性意味着只有获准的人能看到数据；完整性要求数据不被未授权修改；可用性则保证系统在需要时能够正常服务。\n\n常见风险包括钓鱼邮件、弱密码、恶意软件、软件漏洞和权限配置错误。攻击者往往利用人的疏忽，而不只依赖高深技术。因此，多因素认证、密码管理器、及时更新软件、谨慎点击链接和定期备份，都是有效的基础措施。\n\n安全不是一次设置就永久完成的任务，而是识别风险、实施保护、发现异常、响应事件和恢复业务的持续过程。开发网站时还要验证输入、限制权限、使用 HTTPS，并避免把密码和密钥直接写进前端代码。",updatedAt:"2026-08-03"},
  {id:20,title:"云计算",category:"编程",icon:"云",color:"purple",summary:"通过网络按需使用服务器、存储和软件服务，让计算资源能够弹性扩展。",content:"云计算把计算能力、存储空间、数据库和应用软件通过网络提供给用户。使用者不必为每个项目购买和维护实体服务器，而是可以按需要申请资源，并根据使用量付费。\n\n常见服务模式包括 IaaS、PaaS 和 SaaS。IaaS 提供虚拟机和网络等基础资源；PaaS 提供部署应用所需的平台；SaaS 则直接向用户提供可使用的软件。公有云、私有云和混合云描述的是资源由谁拥有、在哪里运行以及如何连接。\n\n云服务的优势是弹性、快速部署和全球访问，但并不意味着管理责任全部消失。用户仍需正确配置访问权限、加密敏感数据、规划备份与费用，并了解服务中断和供应商依赖等风险。",updatedAt:"2026-08-03"},
  {id:21,title:"算法与数据结构",category:"编程",icon:"A",color:"orange",summary:"用明确步骤解决问题，并用合适的结构组织数据，是编写高效程序的核心。",content:"算法是一组有限、明确并可执行的步骤，用于把输入转化为期望的输出。排序、搜索、路径规划和文本匹配都可以由不同算法完成；同一个问题往往存在多种解法。\n\n数据结构决定数据如何组织。数组适合按位置访问，链表便于连接节点，栈遵循后进先出，队列遵循先进先出，树和图则适合表达层级或网络关系。选择合适的数据结构，常常能让算法更简单、更高效。\n\n评价算法时要观察时间复杂度和空间复杂度。大 O 表示法描述输入规模增大时资源需求的增长趋势，而不是精确运行秒数。初学者可以先掌握线性查找、二分查找、常见排序以及栈、队列和哈希表。",updatedAt:"2026-08-03"},
  {id:22,title:"操作系统",category:"编程",icon:"OS",color:"green",summary:"管理处理器、内存、文件和设备，并为应用程序提供统一运行环境的系统软件。",content:"操作系统位于硬件与应用程序之间。它把处理器时间、内存、磁盘和外设等资源分配给程序，并提供文件、窗口、网络和权限等通用能力。Windows、macOS、Linux、Android 都属于操作系统。\n\n正在运行的程序称为进程，进程中的执行序列称为线程。操作系统通过调度让多个任务共享处理器，并用虚拟内存为程序提供相对独立的地址空间。文件系统则负责组织目录、文件内容和访问权限。\n\n内核是操作系统的核心部分，具有较高权限；普通应用通常运行在受限制的用户空间。这样的隔离能够降低一个程序故障影响整个系统的概率。理解进程、内存、文件系统和权限，是继续学习后端、性能与安全的重要基础。",updatedAt:"2026-08-03"},
  {id:23,title:"量子计算",category:"科学",icon:"Q",color:"purple",summary:"利用叠加、纠缠和干涉等量子现象处理信息的新型计算方式。",content:"普通计算机用比特表示 0 或 1，量子计算机使用量子比特。量子比特可以处于多个基础状态的叠加，但测量后会得到确定结果。量子算法通过精心控制干涉，使正确答案的概率增强。\n\n纠缠描述多个量子比特之间无法用彼此独立状态完整解释的关联。它与叠加一起为某些量子算法提供能力，但量子计算并不是“同时尝试所有答案后直接读出”，因为测量只能得到有限信息。\n\n量子设备很容易受到环境噪声影响，量子纠错因此十分关键。目前量子计算更适合研究特定问题，例如量子系统模拟、部分优化和密码学相关算法，并不会在所有任务上取代传统计算机。",updatedAt:"2026-08-03"},
  {id:24,title:"气候变化",category:"科学",icon:"℃",color:"red",summary:"理解温室效应、人类活动、观测证据，以及气候变化对自然与社会的影响。",content:"气候描述一个地区或全球在较长时间尺度上的平均天气状态。温室气体会吸收并重新辐射地表释放的红外能量，使地球保持适宜温度；当其浓度增加时，额外的温室效应会推动全球变暖。\n\n燃烧煤、石油和天然气，土地利用变化以及部分工业过程增加了二氧化碳、甲烷等温室气体。地表和海洋升温、冰川消退、海平面上升等多种独立观测共同构成证据，科学家还利用物理模型区分自然因素和人类影响。\n\n气候变化会改变极端高温、强降水、干旱和沿海风险。应对方式分为减缓与适应：减缓重在降低排放和增加碳汇，适应则通过基础设施、预警、农业和公共卫生措施降低已经出现或难以避免的影响。",updatedAt:"2026-08-03"},
  {id:25,title:"疫苗与免疫",category:"科学",icon:"V",color:"green",summary:"疫苗通过训练免疫系统识别病原体，降低感染后重症和传播造成的危害。",content:"免疫系统能够识别细菌、病毒等外来成分，并形成针对性的防御反应。疫苗向身体展示安全形式的抗原或相关信息，使免疫系统在不经历相应严重疾病的情况下建立记忆。\n\n接种后如果再次遇到病原体，记忆细胞可以更快启动抗体和细胞免疫反应。不同疫苗采用减毒、灭活、蛋白、病毒载体或 mRNA 等技术路线，但共同目标都是提前训练免疫系统。\n\n疫苗不能保证每个人完全不感染，不过通常能显著降低发病、重症或死亡风险。接种建议会根据年龄、健康状况和地区疾病流行情况调整；具体选择应参考当地卫生部门并咨询专业医务人员。",updatedAt:"2026-08-03"},
  {id:26,title:"黑洞",category:"科学",icon:"●",color:"blue",summary:"引力强到连光也无法从事件视界内逃出的天体，帮助研究极端时空环境。",content:"黑洞是物质被压缩到极高密度后形成的天体。事件视界是一个边界：一旦物质或光越过它，就无法再把信息传回外部观察者。事件视界并不是坚硬表面。\n\n许多恒星级黑洞来自大质量恒星演化末期的坍缩；星系中心还普遍存在质量更大的超大质量黑洞。黑洞本身不发光，天文学家通过周围恒星运动、吸积盘辐射和引力波等间接证据研究它们。\n\n黑洞并不会像宇宙吸尘器一样把远处一切吸走。在相同距离和质量条件下，它的引力作用与其他天体遵循同样规律。研究黑洞能够检验广义相对论，并帮助理解星系演化与高能天体物理过程。",updatedAt:"2026-08-03"},
  {id:27,title:"罗马帝国",category:"历史",icon:"R",color:"yellow",summary:"从地中海世界的扩张、治理和文化交流，理解一个古代帝国的形成与长期影响。",content:"公元前 27 年，屋大维获得“奥古斯都”称号，通常被视为罗马帝国时期的开始。帝国以地中海为核心扩张，通过军队、道路、港口和城市网络连接欧洲、北非与西亚的广大地区。\n\n罗马并非只靠武力维持统治。行省行政、税收、法律、公民权和地方精英合作共同构成治理体系。拉丁语与希腊语、各地宗教和生活方式长期并存，帝国内部也持续发生贸易、迁徙与文化融合。\n\n三世纪以后，帝国经历内战、边境压力和财政困难，并通过四帝共治等制度改革应对。西部帝国在五世纪失去统一政权，东部罗马帝国则以君士坦丁堡为中心延续近千年。罗马法、城市建设和政治观念对后世影响深远。",updatedAt:"2026-08-03"},
  {id:28,title:"海上丝绸之路",category:"历史",icon:"舟",color:"blue",summary:"连接东亚、东南亚、印度洋、西亚和非洲的古代海上贸易与文化交流网络。",content:"海上丝绸之路不是一条固定航线，而是由季风、港口和区域贸易连接起来的海上网络。商船在不同季节借助风向航行，货物往往经过多个港口分段转运。\n\n丝绸、瓷器、香料、玻璃、金属和药材在网络中流通。港口城市不仅是买卖货物的地点，也是语言、宗教、航海技术和饮食文化相遇的空间，商人群体常在海外形成长期社区。\n\n海路与陆上丝路彼此补充，重要性也随政治格局、造船技术和市场需求变化。研究沉船、陶瓷、钱币、港口遗址与旅行记录，可以帮助历史学家重建这张跨区域交流网络。",updatedAt:"2026-08-03"},
  {id:29,title:"启蒙运动",category:"历史",icon:"光",color:"orange",summary:"重视理性、经验、公开讨论和政治权利，对现代社会观念产生深刻影响的思想运动。",content:"启蒙运动主要发生在 17 至 18 世纪的欧洲，但它不是观点完全一致的单一组织。思想家讨论知识如何获得、政府权力从何而来，以及宗教宽容、教育和法律应如何改进。\n\n科学革命的发展增强了人们运用观察、实验和理性解释世界的信心。书籍、报刊、沙龙和通信网络扩大了公共讨论。自然权利、社会契约、权力制衡等观念逐渐进入政治辩论。\n\n启蒙思想影响了多场政治改革与革命，也存在明显局限：宣扬普遍权利的社会仍保留奴隶制、殖民统治和性别不平等。理解启蒙运动既要看到其解放性主张，也要分析理想与现实之间的矛盾。",updatedAt:"2026-08-03"},
  {id:30,title:"互联网发展史",category:"历史",icon:"@",color:"purple",summary:"从分组交换和 TCP/IP 到万维网与移动网络，理解全球网络如何逐步形成。",content:"互联网不是由某个人一次发明完成的。早期研究者探索分组交换，让数据被拆成小包并通过共享网络传输。ARPANET 等实验网络验证了计算机远距离互联的可能性。\n\n为了让结构不同的网络互相通信，研究者发展了 TCP/IP 协议族。1983 年 ARPANET 转向 TCP/IP，随后学术网络和商业网络不断连接，开放协议与公开技术文档促进了全球协作。\n\n互联网与万维网并不相同：互联网是连接网络的基础设施，万维网是运行其上的信息服务之一。浏览器、搜索引擎、宽带、智能手机和云服务让联网进入日常生活，同时也带来隐私、安全、数字鸿沟和平台治理等新问题。",updatedAt:"2026-08-03"},
  {id:31,title:"USDT：泰达币深度介绍",category:"金融科普",icon:"₮",color:"green",summary:"重点了解 USDT 的发行与储备机制、多链版本、转账流程，以及使用稳定币必须注意的风险。",content:"USDT 是由 Tether 相关发行方发行的美元稳定币。它的设计目标是让一个 USDT 尽量保持接近一美元的价值，以便在区块链网络中转移和结算美元计价价值。它不是美国政府发行的货币，也不是银行账户里的美元存款。\n\nUSDT 的发行与赎回建立在发行方及其储备资产之上。发行方接收符合条件客户的资金后可以铸造代币，赎回时则销毁相应代币并按条款处理法币支付。普通用户通常通过交易平台、钱包服务或兑换服务获得 USDT，不一定能直接向发行方赎回；资格、最低金额、费用和地区限制应以官方条款为准。\n\nUSDT 同时存在于多条区块链上，例如 Ethereum 上的 ERC-20 版本和 TRON 上的 TRC-20 版本。不同网络中的 USDT 不是可以随意混发的同一条链上资产。转账时，发送网络、接收地址支持的网络和平台入账网络必须完全一致；选错网络可能导致资产无法自动到账，甚至永久损失。\n\n链上手续费通常使用所在网络的原生资产支付，而不是直接用 USDT 支付。例如 Ethereum 常用 ETH 支付网络费，TRON 通常涉及 TRX、带宽和能量。兑换平台显示的“手续费”还可能包含平台服务费、网络费和汇率差价，比较方案时应查看最终预计到账数量，而不能只看宣传费率。\n\n稳定币的“稳定”是设计目标，不是无风险保证。USDT 仍存在短时价格偏离一美元、发行方与托管方、储备资产流动性、监管、智能合约、区块链拥堵和交易对手等风险。发行方还可能依据法律、条款或合规要求限制某些地址，因此链上代币并不等于完全不受控制的现金。\n\n实际收款前应先核对币种、网络、合约地址和收款地址，较大金额可先做小额测试。任何人索要助记词、私钥或远程控制权限都应立即停止操作。USDT 适合解释数字结算工具，但不应被描述为保本投资、储蓄账户或必然能按一美元随时兑现的产品。",updatedAt:"2026-08-03"},
  {id:32,title:"USDC：美元稳定币深度介绍",category:"金融科普",icon:"$",color:"blue",summary:"重点了解 USDC 的发行方、储备披露、原生与跨链版本，以及兑换和转账中的关键安全步骤。",content:"USDC 是 Circle 发行的美元稳定币，目标是维持一个 USDC 对应一美元的价值。Circle 官方说明其储备由高流动性的现金及现金等价资产支持，并公开储备和第三方鉴证资料。USDC 仍然是私人机构发行的数字资产，并非中央银行数字货币，也不等同于个人银行存款。\n\n在发行机制中，符合条件的 Circle Mint 客户可以存入美元铸造 USDC，或提交 USDC 申请按条款赁回美元；赎回时相关 USDC 会被销毁。个人用户通常通过交易所、钱包或兑换服务买卖，因此实际成交价格、费用、到账方式和对手方风险取决于所使用的平台。\n\nUSDC 在多条区块链上原生发行。用户必须区分官方原生 USDC、由第三方桥接产生的封装版本，以及名称或图标相似的假代币。即使地址格式看起来相同，平台也可能只支持部分网络。接入兑换服务时应使用官方网络列表和合约信息建立白名单，而不能只根据代币符号判断。\n\n跨链转移并不是普通转账。传统第三方跨链桥可能锁定一条链的资产并在另一条链发行映射资产；Circle 的 CCTP 等方案则可通过销毁和铸造在支持网络之间移动原生 USDC。不同方式具有不同的智能合约、桥接方、等待时间和故障风险，页面需要明确告诉用户当前采用哪一种。\n\nUSDC 也可能短时偏离一美元，并面临发行方、银行与托管、储备流动性、法规、网络拥堵、智能合约和平台经营等风险。官方的一比一赎回承诺受资格、条款、法律和可用渠道约束，不代表每一位用户都能在任意地点、任意时间无条件直接向 Circle 赎回。\n\n使用前应核对网络名称、官方合约、地址、Memo 或 Tag 要求、平台最低金额和预计到账数量。先做小额测试，不向任何人透露私钥或助记词。介绍 USDC 时应同时展示透明度资料与风险边界，避免使用“绝对安全”“零风险”或“永不脱锚”等误导表达。",updatedAt:"2026-08-03"},
  {id:33,title:"Changer+ 稳定币兑换前必读",category:"金融科普",icon:"↔",color:"orange",summary:"为未来接入 Changer+ 准备的用户指南：看懂币种、网络、报价、费用、到账与安全校验。",content:"稳定币兑换的第一步不是输入金额，而是确认兑换对象。例如 USDT 与 USDC 是不同发行方的资产，同一种稳定币还可能存在于多条网络。页面应同时展示币种全称、代币符号、区块链网络和必要的合约信息，避免用户仅凭图标操作。\n\n一次兑换通常包含输入金额、实时或限时汇率、平台服务费、区块链网络费、最低与最高限额以及预计到账数量。接入 Changer+ 时，应从正式接口动态读取这些数据，并标明报价有效期；知识文章不应写死会变化的费率、限额或到账时间。\n\n用户提交前需要再次确认接收地址和目标网络。某些网络或平台还要求 Memo、Tag 等附加标识，遗漏可能导致无法自动入账。较大金额建议先使用相同路线做小额测试，同时保存订单编号和交易哈希，便于查询链上状态和联系支持。\n\n兑换状态可分为等待入账、链上确认中、兑换处理中、已发送、已完成、失败或需要人工处理。前端应解释每个状态的含义，并把“平台已发送”和“接收平台已入账”区分开，因为后者还受目标平台确认规则影响。\n\n安全页面应显示 Changer+ 的官方域名与支持渠道，并提醒用户核对浏览器地址、拒绝屏幕共享、远程控制和索要助记词的请求。客服处理订单通常只需要订单号、交易哈希等公开信息，不需要私钥、助记词或钱包密码。\n\n本页是接入前的通用教育内容，不代表 Changer+ 已经在 Smart Wiki 中正式提供兑换服务。正式上线前还需补充经确认的运营主体、服务地区、支持资产与网络、费用规则、隐私政策、用户协议、风险披露和异常订单处理流程。",updatedAt:"2026-08-03"},
  {id:34,title:"VALORANT（无畏契约）入门与玩法科普",category:"游戏",icon:"V",color:"red",image:"assets/valorant-guide.svg",tags:["瓦洛兰特","无畏契约","FPS"],summary:"认识 Riot 的 5 对 5 战术射击游戏：胜负目标、特工职责、经济系统与新手训练路线。",content:"VALORANT 是 Riot Games 推出的 5 对 5 第一人称战术射击游戏，中文正式名称为《无畏契约》。“瓦洛兰特”是玩家对英文名 VALORANT 的常见音译。游戏把精确枪法、团队信息与拥有独特技能的特工结合起来，但技能的主要作用是创造机会、封锁视野和获取信息，基础射击与团队配合仍然决定多数交战结果。\n\n经典对战采用攻守轮换。进攻方需要携带爆能器进入指定区域并完成安装，防守方则要阻止安装、拆除已安装的爆能器，或消灭对方队伍。每回合只有一次生命，因此脚步声、地图控制、时间管理与队友之间的报点非常重要。不同模式的规则和时长可能不同，应以游戏客户端当前说明为准。\n\n特工通常按决斗、先锋、控场和哨卫等职责理解。决斗者擅长率先进入交战区域；先锋帮助侦察和突破；控场者使用烟雾等能力分割战场；哨卫偏向防守、预警与保护侧翼。职责不是死板的站位规定，而是帮助队伍形成互补。新手应先熟悉少量特工，再逐渐理解技能之间的组合。\n\n每局包含经济系统。玩家根据回合结果和个人行动获得资金，用来购买武器、护甲和技能。赢下一回合并不代表下一回合一定要花光资金；团队统一全买、节省或半买，通常比各自随意消费更有效。死亡后拾取武器、保存装备和判断对手经济，也属于战术的一部分。\n\n射击训练应从停止移动后开枪、准星保持在头部高度、控制短点射和熟悉常见角度开始。连续移动时多数武器精度会下降。不要只追求击杀数：主动报点、交换击杀、使用技能协助队友以及完成地图目标，同样是有效贡献。\n\n新手可以先在训练场调整灵敏度和准星，再通过普通模式熟悉地图。竞技模式存在段位与匹配规则，持续更新也可能改变地图、特工和武器平衡。保持友善沟通，不泄露个人信息，并合理安排游戏时间，能让学习过程更安全、更稳定。",updatedAt:"2026-08-03"},
  {id:35,title:"PUBG：绝地求生游戏机制与新手指南",category:"游戏",icon:"P",color:"orange",image:"assets/pubg-guide.svg",tags:["PUBG","绝地求生","大逃杀"],summary:"从跳伞、搜集、缩圈到决赛圈，系统了解 PUBG 的生存目标、装备机制与团队协作。",content:"PUBG: BATTLEGROUNDS 是以大逃杀为核心的多人战术射击游戏。玩家从飞机跳伞进入大型地图，搜集武器、护具、药品和其他物资，在不断缩小的安全区域中生存。个人或队伍的最终目标不是取得最多击杀，而是成为最后存活的一方。\n\n一局游戏通常经历跳伞、初期搜集、转移、区域控制和决赛圈。热门地点物资可能丰富，但早期交战风险更高；偏远落点相对安全，却可能带来载具和转移压力。航线、地形、安全区位置和可用时间共同决定路线，没有适用于每一局的固定答案。\n\n武器按照突击步枪、冲锋枪、精确射手步枪、狙击步枪、霰弹枪等类别呈现不同射程和后坐力。配件会影响瞄准、稳定性、弹匣容量或枪口表现。护甲与头盔具有等级和耐久度，药品也有使用时间；交战前检查弹药、治疗物资与装备状态，比盲目囤积更重要。\n\n蓝圈会迫使玩家持续进入安全区。在圈外停留会受到伤害，而且不同阶段的压力可能不同。转移时应提前观察地形、载具油量、桥梁和可能被敌人控制的路线。车辆可以快速移动并提供有限掩护，但声音会暴露位置，停车方式也会影响下车后的安全。\n\n组队模式重视信息共享。报点应尽量包含方向、距离、地标和敌人数量；被击倒不等于立即淘汰，队友可能救援。保持合理间距可以互相支援并避免同时被攻击。烟雾弹可用于救人、转移和遮挡视线，往往比多带一件武器更有战术价值。\n\n新手应先掌握键位、拾取设置、基础压枪和声音方向判断，然后再练习远距离弹道与复杂战术。PUBG 的地图、武器数值、模式和匹配规则会随版本更新，具体数据应以官方补丁说明为准。使用正规客户端，不购买来历不明的账号或外挂，并注意语音交流与个人隐私安全。",updatedAt:"2026-08-03"}
  ,{id:36,title:"AI 智能体：从聊天工具到任务执行者",category:"科技前沿",icon:"◎",color:"purple",image:"assets/ai-agents.svg",tags:["AI Agent","智能体","生成式AI"],summary:"理解 AI 智能体如何规划步骤、调用工具和执行任务，以及权限、验证与安全边界。",content:"AI 智能体通常指能够围绕目标持续执行多步任务的人工智能系统。与只回答一次问题的聊天工具相比，智能体会结合模型、记忆、工具和反馈循环，把“整理一份行业报告”拆成搜索资料、读取文件、比较信息、生成草稿和检查结果等步骤。\n\n智能体的核心不只是语言模型。它还需要知道可用工具及其参数、保存任务状态、判断何时继续或停止，并处理失败和重试。多个智能体也可以分工协作，但数量越多不代表效果越好；沟通成本、重复工作和错误传递都可能增加。\n\n真正落地时，权限设计比演示效果更重要。读取日历与发送邮件是不同风险等级，查看代码与部署生产环境也应分开授权。高风险操作需要明确确认、最小权限、操作日志和可撤销机制，不能让模型仅凭模糊指令执行不可逆操作。\n\n智能体可能误解目标、使用过期信息或在工具调用中犯错，因此输出必须能够追溯来源，并按任务风险设置人工复核。评价智能体不能只看回答是否流畅，还要测量任务完成率、成本、延迟、失败恢复和安全事件。\n\n对普通用户而言，适合从低风险、结果容易检查的任务开始，例如资料分类、会议摘要或草稿整理。把目标、限制条件和完成标准写清楚，往往比一句“帮我全部完成”更可靠。",updatedAt:"2026-08-03"}
  ,{id:37,title:"具身智能与人形机器人",category:"科技前沿",icon:"R",color:"orange",image:"assets/physical-ai.svg",tags:["具身智能","人形机器人","Physical AI"],summary:"了解机器人如何把感知、语言理解与动作控制连接起来，以及真实部署仍面临的难题。",content:"具身智能强调智能系统通过身体与真实环境交互。人形机器人是其中备受关注的一类，因为人类的工厂、仓库和家庭本来就围绕双手、楼梯和工具设计，但具身智能也可以运行在机械臂、轮式机器人或无人机上。\n\n机器人需要把摄像头、深度传感器、力传感器等信息转化为环境理解，再完成动作规划与电机控制。视觉语言模型可以帮助理解指令和物体，视觉—语言—动作模型则试图进一步输出动作。高层规划和毫秒级底层控制通常由不同模块承担。\n\n演示中的单次成功不等于可以稳定工作。光线变化、透明物体、柔软材料、拥挤空间和意外碰撞都会增加难度。真实部署要考察连续工作时长、成功率、故障恢复、维护成本和对人员的安全保护。\n\n训练数据是另一项挑战。互联网拥有大量文字与图片，却缺少覆盖各种机器人身体和动作的高质量轨迹。仿真、遥操作、合成数据和跨机器人迁移正在被用来扩大数据规模，但仿真与现实之间仍存在差距。\n\n近期更现实的方向是结构化场景中的重复任务，例如物料搬运、分拣和设备巡检。评价人形机器人时，应区分概念展示、试点部署与规模化商业运行，避免只根据视频中的短片段判断能力。",updatedAt:"2026-08-03"}
  ,{id:38,title:"后量子密码：提前保护未来数据",category:"科技前沿",icon:"Q",color:"blue",image:"assets/quantum-safe.svg",tags:["PQC","量子安全","网络安全"],summary:"为什么量子计算尚未破解互联网，机构却已开始迁移新的加密标准？",content:"今天的网络通信大量依赖 RSA 和椭圆曲线密码等公钥算法。足够强大的容错量子计算机理论上可使用量子算法削弱这些体系，但截至目前，并没有公开证据表明现有量子计算机已经能够破解互联网所用的大规模密钥。\n\n后量子密码并不是在量子计算机上运行的密码，而是在普通计算机和网络设备上运行、并被设计为抵抗经典与量子攻击的新算法。NIST 在 2024 年发布了首批正式标准，为密钥建立和数字签名提供迁移基础。\n\n迁移之所以现在开始，是因为大型系统更换密码算法需要多年。长期保密的数据还面临“现在收集、未来解密”的风险：攻击者可以先保存加密流量，等待未来能力提升后再尝试解密。软件、硬件、证书和供应链都需要盘点。\n\n新算法会改变密钥、签名和消息大小，也可能影响性能和兼容性。组织通常需要密码敏捷性，让系统未来能再次替换算法，并在迁移阶段测试混合方案。自行发明加密算法或只更换网页上的名称并不能获得量子安全。\n\n普通用户无需恐慌或立即更换所有设备，但应保持系统、浏览器和通信软件更新。开发者则应确认所用平台和依赖的迁移路线，避免在业务代码中写死某一种密码算法。",updatedAt:"2026-08-03"}
  ,{id:39,title:"Passkey：无密码登录如何工作",category:"科技前沿",icon:"K",color:"green",image:"assets/passkeys.svg",tags:["Passkey","身份认证","网络安全"],summary:"通过公钥密码与设备验证减少密码和钓鱼风险，同时理解同步、恢复和兼容性。",content:"Passkey 是一种基于公钥密码的登录凭证。注册时，设备为网站生成一对密钥：公钥交给网站保存，私钥留在用户设备或受保护的同步系统中。登录时设备对网站的挑战进行签名，网站验证签名，而不需要接收用户密码。\n\n用户通常通过指纹、面容识别、设备 PIN 或屏幕锁确认操作。这些本地验证方式用于解锁凭证，生物特征数据通常不直接发送给网站。因为凭证与网站域名绑定，仿冒网站难以诱骗浏览器为错误域名完成有效签名，因此能明显降低传统钓鱼风险。\n\nPasskey 可以保存在单台安全密钥或设备中，也可以通过平台账户同步到多台设备。同步提高便利性，但用户需要理解平台账户恢复、设备丢失和跨生态使用方式。网站仍应提供安全的账户恢复流程，避免恢复通道成为新的薄弱点。\n\nPasskey 不代表身份安全问题全部消失。已解锁设备被他人控制、恶意软件、错误授权以及不安全的客服恢复流程仍可能造成风险。重要账户应检查已登记设备和凭证，及时移除不再使用的设备。\n\n网站接入时常使用 WebAuthn 和 FIDO 相关标准。迁移阶段可以同时保留密码和 Passkey，但应避免强迫用户在不理解恢复方式时删除全部备用登录手段。",updatedAt:"2026-08-03"}
  ,{id:40,title:"端侧 AI：模型为什么开始在设备上运行",category:"科技前沿",icon:"N",color:"red",image:"assets/edge-ai.svg",tags:["端侧AI","NPU","隐私计算"],summary:"理解手机和电脑中的 NPU、本地推理、混合 AI，以及性能、隐私和能耗的取舍。",content:"端侧 AI 指在手机、电脑、汽车、摄像头或其他本地设备上执行模型推理，而不是把每次请求都发送到云端。现代设备加入 NPU 等专用计算单元，用更适合神经网络的方式提高吞吐量并降低部分任务的能耗。\n\n本地运行可以减少网络延迟，在离线环境中继续工作，并让部分敏感数据不离开设备。例如语音唤醒、照片分类、实时字幕和输入辅助都适合端侧处理。但“本地 AI”不自动等于完全私密，应用仍可能上传日志、模型输入或分析数据。\n\n设备的内存、电量和散热有限，因此端侧模型往往需要量化、剪枝、蒸馏等优化。参数更少或精度更低可能换来更快速度，但也可能影响输出质量。不同芯片和软件框架的兼容性也是部署成本的一部分。\n\n许多产品采用混合 AI：简单、私密或实时任务在本地完成，复杂任务再交给云端模型。系统需要清楚提示哪些数据会离开设备，并在断网、服务失败或权限被拒绝时提供合理降级。\n\n评价端侧 AI 不应只看宣传中的每秒运算次数。真实体验还取决于内存带宽、模型支持、持续性能、功耗、软件优化和具体任务。购买设备时，应结合实际应用和可用功能，而不是只根据“NPU”或“AI PC”标签判断。",updatedAt:"2026-08-03"}
  ,{id:41,title:"Minecraft：方块世界生存与创造指南",category:"游戏百科",icon:"M",color:"green",image:"assets/game-sandbox.svg",tags:["Minecraft","我的世界","沙盒"],summary:"从生存、合成与探索到创造模式，理解 Minecraft 开放式方块世界的核心玩法。",content:"Minecraft 是由方块构成的开放式沙盒游戏。玩家可以破坏、收集和放置方块，利用资源合成工具、建造建筑并探索程序生成的世界。它没有唯一的通关方式：有人专注生存，有人进行大型建筑，也有人研究红石装置或参与多人服务器。\n\n生存模式要求玩家管理生命、饥饿、装备和资源。新手进入世界后通常先收集木材，制作基础工具和庇护所，并准备照明与食物。夜间和黑暗区域可能出现敌对生物，因此探索洞穴前应携带火把、食物和备用装备。\n\n创造模式提供大量方块和飞行能力，更适合建筑、实验与地图制作。Java 版和基岩版在平台、联机方式、模组生态及部分机制上存在差异；跨平台游玩通常需要参与者使用兼容的版本和服务。\n\n多人游戏应选择可信服务器，了解社区规则，不向陌生人透露真实姓名、地址或账号验证码。下载模组、材质包和地图时应检查来源与版本兼容性，并为重要世界保存备份。",updatedAt:"2026-08-03"}
  ,{id:42,title:"英雄联盟：召唤师峡谷入门百科",category:"游戏百科",icon:"L",color:"blue",image:"assets/game-strategy.svg",tags:["英雄联盟","League of Legends","MOBA"],summary:"认识 5 对 5 MOBA 的线路、英雄职责、资源、视野与团队胜利条件。",content:"《英雄联盟》是一款团队策略游戏，最常见的召唤师峡谷模式由两支五人队伍对抗，目标是推进地图并摧毁对方基地中的水晶枢纽。击杀只是取得资源和地图优势的方式之一，不能代替最终目标。\n\n地图通常分为上路、中路、下路和野区。英雄具有不同技能与定位，队伍通过补刀获得金币、购买装备，并争夺防御塔、史诗野怪和视野。版本更新会改变英雄与装备强度，因此基础的地图理解和团队决策比记住某一套数值更持久。\n\n新手适合先固定一个位置和少量英雄，熟悉技能范围、补刀、回城时机与小地图观察。视野可以降低被偷袭风险；在没有队友支援时盲目追击，往往会把个人优势变成团队损失。\n\n团队游戏容易产生情绪压力。应使用清晰简短的信号沟通，遇到辱骂可使用屏蔽和举报功能。皮肤等付费内容通常不等于竞技优势，消费前应确认价格、退款规则与未成年人保护设置。",updatedAt:"2026-08-03"}
  ,{id:43,title:"Fortnite：大逃杀、零建造与创作平台",category:"游戏百科",icon:"F",color:"purple",image:"assets/game-sandbox.svg",tags:["Fortnite","堡垒之夜","大逃杀"],summary:"了解 Fortnite 如何从大逃杀扩展为包含零建造和玩家创作内容的游戏平台。",content:"Fortnite 不只是单一的大逃杀模式，也包含零建造、创意岛屿以及多种官方或创作者体验。经典大逃杀中，玩家在地图上收集物资和装备，在不断缩小的安全区域内移动，目标是成为最后存活的个人或队伍。\n\n建造模式允许玩家快速搭建墙体、地板和坡道，用于防御、移动与争夺高度；零建造模式移除这套核心建造机制，更强调掩体、移动与射击。不同岛屿可能拥有完全不同的规则，进入前应查看人数、类型和创作者说明。\n\nFortnite 的内容会频繁更新，地图、武器和活动可能发生变化，因此百科不应把某个赛季配置写成永久规则。新手可先调整灵敏度、学习物品栏管理和安全区路线，再逐步熟悉团队报点。\n\n游戏包含虚拟货币、外观和通行证等消费内容。用户应通过官方平台购买并启用账户保护，谨防“免费货币”、代充与账号交易骗局。家长可使用平台和 Epic 提供的家长控制管理聊天、好友与消费。",updatedAt:"2026-08-03"}
  ,{id:44,title:"Counter-Strike 2：战术射击基础",category:"游戏百科",icon:"C",color:"orange",image:"assets/game-action.svg",tags:["CS2","Counter-Strike 2","FPS"],summary:"理解攻防目标、经济管理、投掷物、枪械精度与团队信息在 CS2 中的作用。",content:"Counter-Strike 2 是 Valve 推出的团队战术射击游戏。经典竞技规则围绕恐怖分子方安装炸弹与反恐精英方阻止或拆除炸弹展开，双方轮换阵营。每回合生命有限，目标、时间和队伍存活情况共同决定胜负。\n\n经济系统让每回合决策相互关联。玩家根据结果获得资金购买枪械、护甲和投掷物，团队通常需要统一选择全买、半买或节省。只看个人击杀而忽略炸弹、装备保存和队伍经济，会影响后续多个回合。\n\n移动会影响多数武器的射击精度。新手应练习停止移动后开枪、控制短点射、保持准星高度，并学习烟雾弹、闪光弹和燃烧弹的基本用途。脚步声与信息传递同样重要。\n\nCS2 支持社区地图与创意工坊内容，但下载和交易应通过可信平台。武器皮肤具有虚拟市场属性，价格可能波动且存在诈骗风险；不要向他人提供 Steam 验证码，也不要点击陌生交易链接。",updatedAt:"2026-08-03"}
  ,{id:45,title:"Apex Legends：英雄大逃杀新手指南",category:"游戏百科",icon:"A",color:"red",image:"assets/game-action.svg",tags:["Apex Legends","英雄射击","大逃杀"],summary:"从英雄技能、护盾、移动和信号系统理解 Apex Legends 的小队协作节奏。",content:"Apex Legends 将大逃杀与英雄技能结合。玩家选择拥有不同能力的英雄组成小队，进入大型地图搜集武器、护盾和治疗物品，并在逐渐缩小的安全区域中争取成为最后存活的队伍。\n\n英雄技能会影响侦察、防守、移动或支援，但不能替代枪法、位置与资源管理。队伍选择应考虑能力互补，而不是只追逐当前版本最热门的角色。倒地队友可能被救起，特定条件下还可通过队伍系统重新加入战斗。\n\n游戏的信号系统可以标记敌人、地点和物资，即使不开语音也能交流。新手应与队友保持可支援距离，优先获得两把熟悉的武器和足够护盾，并提前规划进入安全区的路线。\n\n赛季更新会调整英雄、地图和装备。练习场适合熟悉后坐力与技能。外观、组合包和通行证属于可选消费，购买前应确认平台、地区和价格，不接受陌生人的代充或账号共享邀请。",updatedAt:"2026-08-03"}
  ,{id:46,title:"GTA Online：洛圣都线上世界入门",category:"游戏百科",icon:"G",color:"green",image:"assets/game-strategy.svg",tags:["GTA Online","侠盗猎车手 Online","开放世界"],summary:"认识 GTA Online 的自由模式、任务、产业与合作玩法，并建立安全的线上游戏习惯。",content:"GTA Online 是以洛圣都和布莱恩郡为舞台的持续更新线上开放世界。玩家创建角色后可探索自由模式，参与竞速、合作任务、抢劫任务和其他活动，并通过游戏内资金购买载具、房产与业务。\n\n不同活动对人数、装备和前置资产有不同要求。新手不必立刻购买昂贵物品，可以先完成教学和基础任务，熟悉地图、驾驶、战斗和任务匹配，再根据喜欢的玩法规划资金用途。\n\n公开战局允许大量玩家自由互动，也可能遇到干扰。邀请战局或好友战局更适合熟悉业务和合作任务。大型抢劫重视分工、沟通与失败后的复盘；昂贵装备并不能弥补团队目标不清。\n\nGTA Online 包含成熟主题与游戏内消费，适龄要求应以所在地区的评级为准。不要购买来源不明的游戏币、账号或修改服务，不向陌生人透露平台凭证。游戏更新和奖励会变化，具体活动应以 Rockstar 官方信息为准。",updatedAt:"2026-08-03"}
];

const ARTICLE_DETAILS={
  41:{keyPoints:["Minecraft 没有唯一目标，生存、创造、探索和社区玩法都可以成为重点","Java 版与基岩版在平台、联机和生态上存在差异","多人游戏与模组下载应选择可信来源并备份重要世界"],sources:[{title:"Minecraft 官方介绍",url:"https://www.minecraft.net/en-us/article/what-minecraft"},{title:"Minecraft 官方新手指南",url:"https://www.minecraft.net/en-us/minecraft-tips-for-beginners"}]},
  42:{keyPoints:["召唤师峡谷的最终目标是摧毁敌方水晶枢纽","线路、资源、视野和团队决策共同形成 MOBA 的战略层次","先熟悉少量英雄和一个位置更适合新手建立稳定理解"],sources:[{title:"英雄联盟官方玩法指南",url:"https://www.leagueoflegends.com/en-gb/how-to-play/"}]},
  43:{keyPoints:["Fortnite 同时包含大逃杀、零建造和大量创作者体验","赛季内容持续变化，安全区、资源和团队协作是更稳定的基础能力","虚拟货币与账号交易应通过官方平台，并启用账户保护"],sources:[{title:"Fortnite 官方常见问题",url:"https://www.fortnite.com/faq"},{title:"Epic：Fortnite Creative 介绍",url:"https://dev.epicgames.com/documentation/en-us/fortnite/lets-play-in-fortnite-creative"}]},
  44:{keyPoints:["CS2 经典竞技围绕炸弹目标与攻防轮换展开","团队经济会影响连续多个回合，购买决策需要协调","枪械皮肤交易存在诈骗和价格波动风险"],sources:[{title:"Counter-Strike 2 官方网站",url:"https://www.counter-strike.net/home"}]},
  45:{keyPoints:["Apex Legends 把英雄技能、大逃杀和高速移动结合起来","信号系统让不开语音的队伍也能传递关键信息","英雄能力需要与位置、射击和队伍支援配合"],sources:[{title:"Apex Legends 官方主页",url:"https://www.ea.com/en/games/apex-legends/apex-legends"},{title:"EA 官方新手指南",url:"https://www.ea.com/en/games/apex-legends/apex-legends/news/welcome-to-the-apex-games"}]},
  46:{keyPoints:["GTA Online 是包含自由模式、任务、产业与合作活动的线上开放世界","新手应先理解基础系统，再规划游戏内资金与资产","官方渠道、适龄评级和账号安全比短期奖励更重要"],sources:[{title:"GTA Online 官方网站",url:"https://www.rockstargames.com/gta-online"},{title:"Rockstar：GTA Online 指南",url:"https://www.rockstargames.com/gta-online/guides/"}]},
  36:{keyPoints:["AI 智能体把模型、工具、状态与反馈循环组合起来执行多步任务","高风险工具必须采用最小权限、明确确认、日志与可撤销设计","应以任务完成率、可验证性、成本和安全性评价，而不是只看语言是否流畅"],sources:[{title:"OpenAI：智能体如何改变工作",url:"https://openai.com/index/how-agents-are-transforming-work/"},{title:"IEEE：2026 科技趋势预测",url:"https://www.computer.org/press-room/2026-tech-predictions"}]},
  37:{keyPoints:["具身智能可以运行在人形、轮式、机械臂等不同机器人形态上","感知、规划、控制、数据和安全共同决定真实环境中的可靠性","应区分展示、试点与规模化部署，并关注连续成功率和维护成本"],sources:[{title:"Qualcomm：面向机器人与人形机器人的技术平台",url:"https://www.qualcomm.com/news/releases/2026/01/qualcomm-introduces-a-full-suite-of-robotics-technologies-power"},{title:"IEEE：2026 科技趋势预测",url:"https://www.computer.org/press-room/2026-tech-predictions"}]},
  38:{keyPoints:["后量子密码运行在经典计算机上，目标是抵抗经典和量子攻击","NIST 已发布首批正式标准，但大规模系统迁移仍需要多年","密码资产盘点、算法可替换性和兼容性测试是迁移关键"],sources:[{title:"NIST：什么是后量子密码",url:"https://www.nist.gov/cybersecurity-and-privacy/what-post-quantum-cryptography"},{title:"NCCoE：迁移到后量子密码",url:"https://www.nccoe.nist.gov/applied-cryptography/migration-to-pqc"}]},
  39:{keyPoints:["Passkey 使用网站保存的公钥与设备持有的私钥完成认证","凭证与网站域名绑定，能够降低密码泄漏与仿冒网站钓鱼风险","同步、设备丢失和账户恢复仍需要清晰安全的设计"],sources:[{title:"FIDO Alliance：Passkeys 介绍",url:"https://fidoalliance.org/passkeys/"},{title:"W3C：Web Authentication 标准",url:"https://www.w3.org/TR/webauthn-3/"}]},
  40:{keyPoints:["端侧 AI 在本地设备执行推理，可改善延迟、离线能力和部分隐私场景","模型压缩会在速度、能耗、内存和质量之间形成取舍","混合 AI 应明确说明何时使用云端以及哪些数据会被发送"],sources:[{title:"IEEE：2026 科技趋势预测",url:"https://www.computer.org/press-room/2026-tech-predictions"},{title:"NIST：边缘人工智能项目",url:"https://www.nist.gov/programs-projects/edge-artificial-intelligence"}]},
  34:{keyPoints:["VALORANT 是强调精确枪法、信息与技能配合的 5 对 5 战术射击游戏","经典模式围绕爆能器的安装与拆除展开，每回合只有一次生命","团队统一经济决策、清晰报点和完成地图目标比单纯追求击杀更重要"],sources:[{title:"VALORANT 官方游戏介绍",url:"https://playvalorant.com/zh-cn/"},{title:"VALORANT 官方新手指南",url:"https://playvalorant.com/zh-cn/news/announcements/beginners-guide/"}]},
  35:{keyPoints:["PUBG 的最终目标是成为最后存活的个人或队伍，而不是单纯取得最多击杀","安全区、地形、物资与时间共同决定每一局的转移策略","组队时准确报点、合理间距、烟雾掩护和资源分配非常关键"],sources:[{title:"PUBG: BATTLEGROUNDS 官方网站",url:"https://pubg.com/zh-cn/main"},{title:"PUBG 官方游戏指南",url:"https://pubg.com/zh-cn/game-info/guide"}]},
  31:{keyPoints:["USDT 是私人发行方提供的美元稳定币，不是政府货币或银行存款","同名 USDT 可运行于不同区块链，收发网络必须完全匹配","储备、赎回资格、脱锚、合规和平台对手方都是需要理解的风险"],sources:[{title:"Tether：透明度与流通数据",url:"https://tether.to/en/transparency/"},{title:"Tether：法律条款",url:"https://tether.to/en/legal/"}]},
  32:{keyPoints:["USDC 由 Circle 发行，并披露储备与第三方鉴证资料","原生 USDC、第三方桥接版本和仿冒代币不能混为一谈","一比一赎回受账户资格、适用条款、法律和渠道限制"],sources:[{title:"Circle：USDC 官方介绍",url:"https://www.circle.com/usdc"},{title:"Circle：透明度与储备",url:"https://www.circle.com/transparency"},{title:"Circle：USDC 条款",url:"https://www.circle.com/legal/usdc-terms"}]},
  33:{keyPoints:["兑换确认页必须同时展示币种、网络、费用和预计到账数量","费率、限额、支持网络和到账时间应由正式接口动态提供","上线前需要完成主体信息、条款、隐私、风险和异常流程说明"],sources:[{title:"Tether：USDT 官方信息",url:"https://tether.to/"},{title:"Circle：USDC 开发者文档",url:"https://developers.circle.com/stablecoins/what-is-usdc"}]},
  19:{keyPoints:["网络安全同时保护信息的机密性、完整性与可用性","多因素认证、更新、最小权限和备份是基础防线","安全管理是识别、保护、检测、响应和恢复的持续循环"],sources:[{title:"NIST：网络安全框架 2.0",url:"https://www.nist.gov/cyberframework"},{title:"MDN：Web 安全",url:"https://developer.mozilla.org/en-US/docs/Web/Security"}]},
  20:{keyPoints:["云计算通过网络按需提供共享计算资源","IaaS、PaaS、SaaS 对应不同管理边界","弹性便利之外仍需管理权限、数据、成本和可用性"],sources:[{title:"NIST：云计算的定义",url:"https://www.nist.gov/publications/nist-definition-cloud-computing"}]},
  21:{keyPoints:["算法是解决问题的明确有限步骤","数据结构影响数据的访问方式和算法效率","时间与空间复杂度描述资源需求随输入规模的增长"],sources:[{title:"NIST：算法与数据结构词典",url:"https://www.nist.gov/dads/"}]},
  22:{keyPoints:["操作系统负责抽象硬件并分配系统资源","进程、线程和调度共同支持多任务运行","内核与用户空间隔离有助于稳定性和安全性"],sources:[{title:"OpenStax：操作系统概述",url:"https://openstax.org/books/introduction-computer-science/pages/6-1-operating-systems"}]},
  23:{keyPoints:["量子比特可表现叠加，测量后得到确定结果","量子算法利用纠缠和干涉放大有用结果","噪声与量子纠错是实用量子计算的重要挑战"],sources:[{title:"美国能源部：量子信息科学",url:"https://www.energy.gov/topics/quantum-information-science"}]},
  24:{keyPoints:["增加的温室气体强化地球能量系统中的温室效应","多类独立观测与物理研究支持人类活动是近期变暖主因","减缓降低未来变化，适应减少已经存在的风险"],sources:[{title:"NOAA：温室气体为何重要",url:"https://www.climate.gov/ghg/what-are-greenhouse-gases-and-why-do-they-matter"},{title:"NOAA：气候变化证据",url:"https://www.climate.gov/news-features/climate-qa/what-evidence-exists-earth-warming-and-humans-are-main-cause"}]},
  25:{keyPoints:["疫苗让免疫系统在患严重疾病前建立识别能力","免疫记忆可在再次接触病原体时更快响应","接种决策应结合个人健康情况和当地卫生建议"],sources:[{title:"WHO：疫苗与免疫问答",url:"https://www.who.int/news-room/questions-and-answers/item/vaccines-and-immunization-what-is-vaccination"}]},
  26:{keyPoints:["事件视界以内的信息无法返回外部观察者","黑洞可通过吸积物质、天体轨道与引力波间接探测","在远处，黑洞的引力并不比同质量普通天体更特殊"],sources:[{title:"NASA：什么是黑洞",url:"https://www.nasa.gov/universe/what-are-black-holes/"},{title:"NASA：黑洞科学",url:"https://science.nasa.gov/universe/black-holes/"}]},
  27:{keyPoints:["罗马以地中海为中心建立跨洲帝国网络","军队之外，法律、行省和地方合作也是治理基础","西部政权瓦解后，东部罗马仍延续近千年"],sources:[{title:"大都会艺术博物馆：罗马历史概述",url:"https://www.metmuseum.org/-/media/files/learn/for-educators/publications-for-educators/roman.pdf"}]},
  28:{keyPoints:["海上丝路是由季风、港口与区域航线连接的网络","商品交流伴随宗教、技术、语言和生活方式传播","陆路和海路相互补充，并随时代不断改变"],sources:[{title:"UNESCO：认识丝绸之路",url:"https://www.unesco.org/en/silk-roads/about-silk-roads?hub=196704"}]},
  29:{keyPoints:["启蒙运动包含多样甚至互相矛盾的思想","理性、经验、权利和政治正当性是重要议题","普遍权利理想与奴隶制、殖民和性别不平等长期并存"],sources:[{title:"斯坦福哲学百科：启蒙运动",url:"https://plato.stanford.edu/entries/enlightenment/"}]},
  30:{keyPoints:["互联网由分组交换、开放网络和协议协作逐步发展","TCP/IP 让不同类型网络能够互联","互联网是基础网络，万维网只是运行其上的服务之一"],sources:[{title:"Internet Society：互联网简史",url:"https://www.internetsociety.org/internet/history-internet/brief-history-internet/"}]},
  1:{keyPoints:["HTML 用语义标签描述内容结构，而不是负责视觉样式","文档由元素、属性与文本节点共同组成","可访问性与搜索优化都依赖清晰的语义结构"],sources:[{title:"MDN：HTML 指南",url:"https://developer.mozilla.org/en-US/docs/Web/HTML"}]},
  2:{keyPoints:["层叠、继承和选择器优先级决定最终样式","盒模型描述内容、内边距、边框与外边距","Flexbox、Grid 与媒体查询构成现代响应式布局基础"],sources:[{title:"MDN：CSS 指南",url:"https://developer.mozilla.org/en-US/docs/Web/CSS"}]},
  3:{keyPoints:["JavaScript 为网页提供动态内容和交互行为","函数、对象、数组及异步流程是核心基础","DOM API 将程序逻辑与页面元素连接起来"],sources:[{title:"MDN：什么是 JavaScript",url:"https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/What_is_JavaScript"}]},
  4:{keyPoints:["太阳系约在 46 亿年前由气体尘埃云形成","八颗行星分为岩质行星、气态巨行星与冰巨行星","太阳引力维持行星、卫星、小行星和彗星的轨道"],sources:[{title:"NASA：太阳系概览",url:"https://science.nasa.gov/solar-system/solar-system-facts/"}]},
  5:{keyPoints:["光合作用把太阳辐射转化为糖分中的化学能","光反应与碳固定阶段在叶绿体中相互配合","这一过程支撑食物网，并产生许多生命所需的氧气"],sources:[{title:"OpenStax：光合作用概览",url:"https://openstax.org/books/biology-2e/pages/8-1-overview-of-photosynthesis"}]},
  6:{keyPoints:["丝绸之路是陆路和海路组成的网络","商品经多个商人与城市分段转运","宗教、技术、艺术与农作物也沿路线传播"],sources:[{title:"UNESCO：丝绸之路简史",url:"https://en.unesco.org/silkroad/publications/silk-roads-brief-history-documents"}]},
  7:{keyPoints:["HTTP 采用客户端请求、服务器响应的通信模式","方法、状态码和消息头共同表达请求语义","HTTPS 通过 TLS 提供加密、完整性与身份验证"],sources:[{title:"MDN：HTTP 概览",url:"https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview"}]},
  8:{keyPoints:["版本控制记录文件随时间发生的变化","Git 以项目快照而非简单差异来组织历史","工作区、暂存区和仓库对应修改、暂存与提交三种状态"],sources:[{title:"Pro Git：版本控制基础",url:"https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control.html"}]},
  9:{keyPoints:["关系数据库以表、行和列组织结构化数据","主键、外键与约束维持数据关系和正确性","事务确保一组操作全部成功或全部撤销"],sources:[{title:"PostgreSQL：数据库与 SQL 教程",url:"https://www.postgresql.org/docs/current/tutorial.html"}]},
  10:{keyPoints:["API 隐藏内部复杂性并公开稳定的调用契约","Web API 常用 HTTP 与 JSON 交换信息","身份验证、错误处理和版本设计决定接口可维护性"],sources:[{title:"MDN：Web API 入门",url:"https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Client-side_APIs/Introduction"}]},
  11:{keyPoints:["AI 系统根据人类设定目标进行预测、推荐或决策","机器学习通过数据训练模型，而非逐条编写规则","可靠 AI 还需关注偏差、隐私、安全和可解释性"],sources:[{title:"NIST：人工智能专题",url:"https://www.nist.gov/artificial-intelligence"}]},
  12:{keyPoints:["DNA 的碱基顺序储存遗传信息","基因通常通过 RNA 和蛋白质影响细胞功能","遗传性状由基因、环境及其相互作用共同形成"],sources:[{title:"NHGRI：DNA 基础资料",url:"https://www.genome.gov/about-genomics/fact-sheets/DNA-Fact-Sheet"}]},
  13:{keyPoints:["岩石圈被划分为持续缓慢运动的板块","张裂、汇聚和转换边界形成不同地质现象","地震、火山和山脉分布为板块理论提供证据"],sources:[{title:"USGS：动态地球与板块构造",url:"https://pubs.usgs.gov/gip/dynamic/dynamic.html"}]},
  14:{keyPoints:["第一定律描述物体保持运动状态的惯性","第二定律建立合力、质量和加速度的定量关系","第三定律说明相互作用力成对出现并作用于不同物体"],sources:[{title:"OpenStax：牛顿运动定律",url:"https://openstax.org/books/astronomy/pages/3-2-newtons-great-synthesis"}]},
  15:{keyPoints:["机器、蒸汽动力与工厂制度改变生产组织","铁路和轮船扩大市场并加速城市化","工业化同时带来增长、劳动问题与环境成本"],sources:[{title:"Britannica：工业革命",url:"https://www.britannica.com/event/Industrial-Revolution"}]},
  16:{keyPoints:["尼罗河农业为古埃及国家与城市提供物质基础","法老制度把政治权力与宗教秩序联系起来","文字、墓葬和考古遗物是理解其社会的重要证据"],sources:[{title:"大都会艺术博物馆：古埃及艺术",url:"https://www.metmuseum.org/toah/hd/egya/hd_egya.htm"}]},
  17:{keyPoints:["文艺复兴重新激活了欧洲对古典知识的研究","透视法、人体观察和赞助制度改变艺术生产","印刷、商业城市和跨区域交流推动思想扩散"],sources:[{title:"大都会艺术博物馆：意大利文艺复兴",url:"https://www.metmuseum.org/toah/hd/reni/hd_reni.htm"}]},
  18:{keyPoints:["毕昇在 11 世纪中国实践了早期活字印刷","活字可重新排列使用，但推广受到文字与材料条件影响","印刷降低知识复制成本并改变教育和公共传播"],sources:[{title:"Smithsonian：活字与印刷技术",url:"https://invention.si.edu/invention-stories/was-patent-application-typewriter-handwritten"}]}
};

const ALL_DEFAULT_ARTICLES=[...DEFAULT_ARTICLES,...(globalThis.EXTRA_ARTICLES||[])];
const CATEGORY_ORDER=["科技前沿","编程开发","网络与安全","自然科学","健康医学","地球环境","历史文明","社会经济","文化艺术","生活常识","数字金融","游戏百科"];
const ARTICLE_ORDER=[36,37,40,11,23,38,39,1,2,3,21,8,9,10,22,7,19,20,30,4,26,14,13,5,12,25,24,16,6,28,27,17,18,15,29,31,32,33,34,35,41,42,43,44,45,46];
const CATEGORY_BY_ID={
  36:"科技前沿",37:"科技前沿",40:"科技前沿",11:"科技前沿",23:"科技前沿",38:"科技前沿",39:"科技前沿",
  1:"编程开发",2:"编程开发",3:"编程开发",21:"编程开发",8:"编程开发",9:"编程开发",10:"编程开发",22:"编程开发",
  7:"网络与安全",19:"网络与安全",20:"网络与安全",30:"网络与安全",
  4:"自然科学",26:"自然科学",14:"自然科学",13:"自然科学",5:"自然科学",12:"自然科学",25:"自然科学",24:"自然科学",
  16:"历史文明",6:"历史文明",28:"历史文明",27:"历史文明",17:"历史文明",18:"历史文明",15:"历史文明",29:"历史文明",
  31:"数字金融",32:"数字金融",33:"数字金融",34:"游戏百科",35:"游戏百科",41:"游戏百科",42:"游戏百科",43:"游戏百科",44:"游戏百科",45:"游戏百科",46:"游戏百科"
};
const ARTICLE_IMAGES={1:"assets/coding-cover.svg",4:"assets/science-cover.svg",6:"assets/history-cover.svg",11:"assets/technology-cover.svg",19:"assets/security-cover.svg",23:"assets/technology-cover.svg",24:"assets/science-cover.svg",30:"assets/security-cover.svg",31:"assets/finance-cover.svg",32:"assets/finance-cover.svg",33:"assets/finance-cover.svg"};
function articleSort(a,b){const ai=ARTICLE_ORDER.indexOf(Number(a.id)),bi=ARTICLE_ORDER.indexOf(Number(b.id));return (ai<0?9999:ai)-(bi<0?9999:bi)||String(a.title).localeCompare(String(b.title),"zh-CN");}

function getArticles(){
  const saved=localStorage.getItem("wiki-articles");
  if(!saved){const initial=ALL_DEFAULT_ARTICLES.map(item=>normalizeArticle(item));localStorage.setItem("wiki-articles",JSON.stringify(initial));localStorage.setItem("wiki-content-version",String(CONTENT_VERSION));return initial;}
  try{
    const articles=JSON.parse(saved);
    const version=Number(localStorage.getItem("wiki-content-version")||1);
    if(version<CONTENT_VERSION){const ids=new Set(articles.map(item=>item.id));ALL_DEFAULT_ARTICLES.forEach(item=>{if(!ids.has(item.id))articles.push(item);});localStorage.setItem("wiki-articles",JSON.stringify(articles));localStorage.setItem("wiki-content-version",String(CONTENT_VERSION));}
    return articles.map(item=>normalizeArticle(item));
  }catch(error){return ALL_DEFAULT_ARTICLES.map(item=>normalizeArticle(item));}
}
const CATEGORY_ICONS={"科技前沿":"🚀","编程开发":"💻","网络与安全":"🛡️","自然科学":"🔬","健康医学":"🩺","地球环境":"🌍","历史文明":"🏛️","社会经济":"📈","文化艺术":"🎨","生活常识":"💡","数字金融":"₮","游戏百科":"🎮","其他":"📚"};
const ARTICLE_ICON_RULES=[
  [/HTML/i,"🌐"],[/CSS/i,"🎨"],[/JavaScript/i,"JS"],[/Git/i,"🌿"],[/数据库|SQL/i,"🗄️"],[/API/i,"🔌"],[/算法|数据结构/i,"🧩"],[/操作系统/i,"⚙️"],[/云计算/i,"☁️"],[/网络安全|零信任|防火墙/i,"🛡️"],[/密码|加密|Passkey/i,"🔐"],[/人工智能|\bAI\b|智能体/i,"🤖"],[/机器人|具身智能/i,"🦾"],[/量子/i,"⚛️"],[/芯片|处理器|半导体/i,"🧠"],[/虚拟现实|增强现实|元宇宙/i,"🥽"],[/区块链/i,"⛓️"],[/USDT/i,"₮"],[/USDC/i,"＄"],[/稳定币/i,"🪙"],[/比特币/i,"₿"],[/钱包|Changer/i,"👛"],[/太阳|恒星/i,"☀️"],[/月球|月亮/i,"🌙"],[/宇宙|太空|天文/i,"🌌"],[/地球|板块|地震/i,"🌍"],[/海洋/i,"🌊"],[/水循环/i,"💧"],[/气候|温室/i,"🌡️"],[/生态|生物多样性/i,"🌿"],[/进化|遗传|DNA/i,"🧬"],[/细胞|微生物|细菌/i,"🦠"],[/物理/i,"⚛️"],[/化学/i,"⚗️"],[/数学/i,"📐"],[/睡眠/i,"😴"],[/饮食|营养/i,"🥗"],[/运动|健身/i,"🏃"],[/心理|情绪/i,"🧠"],[/急救/i,"🚑"],[/疫苗|免疫/i,"💉"],[/抗生素|药物/i,"💊"],[/古埃及/i,"𓂀"],[/古希腊|罗马/i,"🏛️"],[/中国|丝绸之路/i,"🏮"],[/工业革命/i,"⚙️"],[/文艺复兴/i,"🖼️"],[/印刷/i,"📖"],[/经济|通货膨胀|市场/i,"📈"],[/金融|银行|利率/i,"🏦"],[/货币/i,"💵"],[/法律|法治/i,"⚖️"],[/媒体|新闻/i,"📰"],[/音乐/i,"🎵"],[/电影/i,"🎬"],[/文学|阅读/i,"📚"],[/摄影/i,"📷"],[/设计/i,"✏️"],[/安全用电|电力/i,"⚡"],[/火灾|消防/i,"🧯"],[/交通/i,"🚦"],[/食物|烹饪/i,"🍳"],[/Minecraft|我的世界/i,"⛏️"],[/英雄联盟|League of Legends/i,"⚔️"],[/无畏契约|VALORANT/i,"🎯"],[/绝地求生|PUBG/i,"🪂"],[/反恐精英|CS2/i,"💣"],[/堡垒之夜|Fortnite/i,"🏗️"],[/Apex/i,"🏆"],[/GTA/i,"🚗"],[/游戏/i,"🎮"]
];
function articleIcon(item,category){const title=String(item.title||"");for(const [pattern,icon] of ARTICLE_ICON_RULES)if(pattern.test(title))return icon;return CATEGORY_ICONS[category]||item.icon||"📚";}
function normalizeArticle(item){const details=ARTICLE_DETAILS[item.id]||{},category=CATEGORY_BY_ID[item.id]||item.category||"其他";return {...item,category,icon:articleIcon(item,category),image:item.image||ARTICLE_IMAGES[item.id]||"",content:(item.content||"").replace("赁回美元","赎回美元"),status:item.status||"published",tags:Array.isArray(item.tags)?item.tags:[],author:item.author||"Smart Wiki",keyPoints:item.keyPoints||details.keyPoints||[],sources:item.sources||details.sources||[]};}
function apiHeaders(){const token=localStorage.getItem("wiki-auth-token");return {"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})};}
function saveArticles(items){const clean=items.map(normalizeArticle);localStorage.setItem("wiki-articles",JSON.stringify(clean));fetch(wikiApiUrl("/api/articles"),{method:"PUT",headers:apiHeaders(),body:JSON.stringify({items:clean})}).catch(()=>{});}
function getUsers(){try{return JSON.parse(localStorage.getItem("wiki-users"))||[];}catch(error){return [];}}
function saveUsers(users){const safeUsers=users.map(({password,passwordHash,salt,...user})=>user);localStorage.setItem("wiki-users",JSON.stringify(safeUsers));fetch(wikiApiUrl("/api/users"),{method:"PUT",headers:apiHeaders(),body:JSON.stringify({users:safeUsers})}).catch(()=>{});}
function getCurrentUser(){try{const session=JSON.parse(localStorage.getItem("wiki-current-user"));if(!session)return null;const savedUser=getUsers().find(user=>user.id===session.id);if(!savedUser){localStorage.removeItem("wiki-current-user");return null;}const current={id:savedUser.id,name:savedUser.name,email:savedUser.email,role:savedUser.role,avatar:savedUser.avatar||session.avatar||""};localStorage.setItem("wiki-current-user",JSON.stringify(current));return current;}catch(error){return null;}}
function setCurrentUser(user){localStorage.setItem("wiki-current-user",JSON.stringify({id:user.id,name:user.name,email:user.email,role:user.role,avatar:user.avatar||""}));}
function avatarMarkup(user,className="user-avatar-image"){return user?.avatar?`<img class="${className}" src="${user.avatar}" alt="" loading="lazy">`:String(user?.name||"U").slice(0,1).toUpperCase();}
if(!document.querySelector('link[data-avatar-display]')){const avatarDisplay=document.createElement("link");avatarDisplay.rel="stylesheet";avatarDisplay.href="avatar-display.css?v=1.0.3";avatarDisplay.dataset.avatarDisplay="";document.head.appendChild(avatarDisplay);}
async function syncCurrentUserWithServer(){const token=localStorage.getItem("wiki-auth-token"),current=getCurrentUser();if(!token||!current)return current;try{const response=await fetch(wikiApiUrl("/api/auth/me"),{headers:apiHeaders()}),data=await response.json();if(!response.ok){if(response.status===401){localStorage.removeItem("wiki-auth-token");localStorage.removeItem("wiki-current-user");}return null;}const user=data.user,users=getUsers(),index=users.findIndex(item=>Number(item.id)===Number(user.id));if(index>=0)users[index]={...users[index],...user};else users.push(user);localStorage.setItem("wiki-users",JSON.stringify(users));setCurrentUser(user);document.dispatchEvent(new CustomEvent("wiki:user-synced",{detail:user}));return user;}catch{return current;}}
function logout(){localStorage.removeItem("wiki-current-user");localStorage.removeItem("wiki-auth-token");location.href="index.html";}

function readStore(key,fallback=[]){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch(error){return fallback;}}
function writeStore(key,value){localStorage.setItem(key,JSON.stringify(value));}
function getUserState(){return readStore("wiki-user-state",{});}
function getMyState(){const user=getCurrentUser();if(!user)return {favorites:[],history:[]};const all=getUserState();return all[user.id]||{favorites:[],history:[]};}
function saveMyState(state){const user=getCurrentUser();if(!user)return false;const all=getUserState();all[user.id]=state;writeStore("wiki-user-state",all);return true;}
function toggleFavorite(articleId){const state=getMyState();state.favorites=state.favorites||[];state.favorites=state.favorites.includes(articleId)?state.favorites.filter(id=>id!==articleId):[articleId,...state.favorites];saveMyState(state);return state.favorites.includes(articleId);}
function addReadingHistory(articleId){const user=getCurrentUser();if(!user)return;const state=getMyState();state.history=(state.history||[]).filter(item=>item.id!==articleId);state.history.unshift({id:articleId,viewedAt:new Date().toISOString()});state.history=state.history.slice(0,30);saveMyState(state);}
function getLogs(){return readStore("wiki-audit-logs",[]);}
function addLog(action,target){const user=getCurrentUser();const logs=getLogs();logs.unshift({id:Date.now(),action,target,user:user?.name||"系统",userId:user?.id||null,createdAt:new Date().toISOString()});writeStore("wiki-audit-logs",logs.slice(0,200));}
function getTrash(){return readStore("wiki-trash",[]);}
function saveTrash(items){writeStore("wiki-trash",items);}
function getSuggestions(){return readStore("wiki-suggestions",[]);}
function saveSuggestions(items){writeStore("wiki-suggestions",items);}
function getSearchGaps(){return readStore("wiki-search-gaps",[]);}
function wikiApiUrl(path){return `${location.protocol==="file:"?"http://127.0.0.1:3000":""}${path}`;}
async function syncUsersWithProject(){try{const local=getUsers(),migration=location.protocol==="file:",user=getCurrentUser(),admin=user&&["admin","super_admin"].includes(user.role);if(!migration&&!admin)return local;const response=await fetch(wikiApiUrl(migration?"/api/users/import":"/api/users"),{method:migration?"POST":"GET",headers:apiHeaders(),body:migration?JSON.stringify({users:local}):undefined});if(!response.ok)return local;const data=await response.json();if(Array.isArray(data.users))localStorage.setItem("wiki-users",JSON.stringify(data.users));return data.users||local;}catch(error){return getUsers();}}
async function syncArticlesWithProject(){try{const response=await fetch(wikiApiUrl("/api/articles"),{headers:apiHeaders()});const data=await response.json();if(Array.isArray(data.items)&&data.items.length){const merged=data.items.map(normalizeArticle),ids=new Set(merged.map(item=>Number(item.id)));ALL_DEFAULT_ARTICLES.forEach(item=>{if(!ids.has(Number(item.id)))merged.push(normalizeArticle(item));});const clean=merged.sort(articleSort);localStorage.setItem("wiki-articles",JSON.stringify(clean));if(clean.length!==data.items.length&&localStorage.getItem("wiki-auth-token"))saveArticles(clean);return clean;}const local=getArticles();if(localStorage.getItem("wiki-auth-token"))saveArticles(local);return local;}catch{return getArticles();}}
function saveSearchGaps(items){writeStore("wiki-search-gaps",items);const user=getCurrentUser(),admin=user&&["admin","super_admin"].includes(user.role);fetch(wikiApiUrl(admin?"/api/search-gaps":"/api/search-gaps/report"),{method:admin?"PUT":"POST",headers:apiHeaders(),body:JSON.stringify(admin?{items}:{item:items[0]})}).catch(()=>{});}
async function syncSearchGapsWithProject(){try{const local=getSearchGaps(),user=getCurrentUser(),admin=user&&["admin","super_admin"].includes(user.role);const migration=location.protocol==="file:";if(!migration&&!admin)return local;const response=await fetch(wikiApiUrl(migration?"/api/search-gaps/import":"/api/search-gaps"),{method:migration?"POST":"GET",headers:apiHeaders(),body:migration?JSON.stringify({items:local}):undefined});if(!response.ok)return local;const data=await response.json();if(Array.isArray(data.items))writeStore("wiki-search-gaps",data.items);return data.items||local;}catch(error){return getSearchGaps();}}
function reportSearchGap(keyword){const query=String(keyword||"").trim().replace(/\s+/g," ");if(query.length<2)return null;const items=getSearchGaps();const key=query.toLocaleLowerCase();let item=items.find(entry=>entry.key===key&&entry.status!=="resolved");const user=getCurrentUser();const now=new Date().toISOString();if(item){item.count=(item.count||1)+1;item.lastSearchedAt=now;if(user&&!item.users?.some(entry=>entry.id===user.id)){item.users=[...(item.users||[]),{id:user.id,name:user.name}].slice(-10);}}else{item={id:Date.now(),key,keyword:query,count:1,status:"open",firstSearchedAt:now,lastSearchedAt:now,users:user?[{id:user.id,name:user.name}]:[]};items.unshift(item);}saveSearchGaps(items.slice(0,300));return item;}
function getVersions(){return readStore("wiki-versions",{});}
function addArticleVersion(article){const versions=getVersions();versions[article.id]=versions[article.id]||[];versions[article.id].unshift({...article,versionSavedAt:new Date().toISOString()});versions[article.id]=versions[article.id].slice(0,20);writeStore("wiki-versions",versions);}
function exportWikiData(){return {format:"smart-wiki-backup",version:1,exportedAt:new Date().toISOString(),articles:getArticles(),users:getUsers().map(({password,...user})=>user),userState:getUserState(),logs:getLogs(),trash:getTrash(),suggestions:getSuggestions(),searchGaps:getSearchGaps(),versions:getVersions()};}
function importWikiData(data){if(!data||data.format!=="smart-wiki-backup"||!Array.isArray(data.articles))throw new Error("备份文件格式不正确");saveArticles(data.articles);writeStore("wiki-user-state",data.userState||{});writeStore("wiki-audit-logs",data.logs||[]);writeStore("wiki-trash",data.trash||[]);writeStore("wiki-suggestions",data.suggestions||[]);writeStore("wiki-search-gaps",data.searchGaps||[]);writeStore("wiki-versions",data.versions||{});}
async function initGlobalMessages(){const user=getCurrentUser();if(!user||!localStorage.getItem("wiki-auth-token")||document.querySelector(".message-fab"))return;try{const response=await fetch(wikiApiUrl("/api/notifications"),{headers:apiHeaders()}),data=await response.json();if(!response.ok||!data.unread)return;document.body.insertAdjacentHTML("beforeend",`<a class="message-fab" href="messages.html" aria-label="${data.unread} 条未读消息">✉<b>${data.unread>99?"99+":data.unread}</b></a>`);const popupKey=`wiki-unread-popup-${user.id}-${data.items?.[0]?.id||data.unread}`;if(!sessionStorage.getItem(popupKey)){const first=(data.items||[]).find(item=>!item.read);document.body.insertAdjacentHTML("beforeend",`<a class="unread-popup" href="messages.html"><strong>${first?.title||"你有新的站内消息"}</strong><span>${first?.content||`当前共有 ${data.unread} 条未读消息`}</span></a>`);sessionStorage.setItem(popupKey,"1");setTimeout(()=>document.querySelector(".unread-popup")?.remove(),5500);}}catch{}}
function initSiteVersion(){if(document.querySelector(".site-version")||document.querySelector("footer"))return;document.body.insertAdjacentHTML("beforeend",'<div class="site-version">Smart Wiki · Version 1.0.2</div>');}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{initSiteVersion();initGlobalMessages();});else{initSiteVersion();initGlobalMessages();}
