import {createServer} from "node:http";
import {randomBytes,scrypt,timingSafeEqual} from "node:crypto";
import {mkdir,readFile,stat,writeFile} from "node:fs/promises";
import {extname,join,normalize} from "node:path";
import {fileURLToPath} from "node:url";
import {networkInterfaces} from "node:os";

const root=fileURLToPath(new URL("./",import.meta.url));
const port=Number(process.env.PORT||3000);
const mime={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8",".svg":"image/svg+xml",".png":"image/png",".ico":"image/x-icon"};
const publicExtensions=new Set(Object.keys(mime));
const dataDirectory=process.env.SMART_WIKI_DATA_DIR||join(root,"data");
const searchGapsFile=join(dataDirectory,"search-gaps.json");
const usersFile=join(dataDirectory,"users.json");
const articlesFile=join(dataDirectory,"articles.json");
const leaderboardFile=join(dataDirectory,"game-leaderboard.json");
const sessionsFile=join(dataDirectory,"sessions.json");
const pythonProgressFile=join(dataDirectory,"python-progress.json");
const commentsFile=join(dataDirectory,"comments.json");
const notificationsFile=join(dataDirectory,"notifications.json");
const directMessagesFile=join(dataDirectory,"direct-messages.json");
const followsFile=join(dataDirectory,"follows.json");
const articleStatsFile=join(dataDirectory,"article-stats.json");
const siteSettingsFile=join(dataDirectory,"site-settings.json");
const defaultSiteSettings={version:"1.0.2",releaseNotes:"Smart Wiki 功能与稳定性更新",updatedAt:null};
const sessions=new Map();
const fileWriteQueues=new Map();
const startedAt=Date.now();
const recentViewKeys=new Map();
const onlineDevices=new Map();
let featuredCache={expiresAt:0,generatedAt:null,items:[]};
const autoPublishIntervalMs=10*60*1000;
let autoPublishRunning=false;
let autoPublishStatus={enabled:true,intervalMinutes:10,lastRunAt:null,lastResult:null,nextRunAt:null};
try{const savedSessions=JSON.parse(await readFile(sessionsFile,"utf8"));for(const item of Array.isArray(savedSessions)?savedSessions:[])if(item?.token&&item.expiresAt>Date.now())sessions.set(item.token,{userId:item.userId,expiresAt:item.expiresAt});}catch(error){if(error.code!=="ENOENT")console.error("读取登录会话失败",error);}

function sendJson(response,status,data){response.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});response.end(JSON.stringify(data));}
async function writeJsonFile(file,value){
  const content=JSON.stringify(value,null,2);
  const previous=fileWriteQueues.get(file)||Promise.resolve();
  const task=previous.catch(()=>{}).then(async()=>{
    await mkdir(dataDirectory,{recursive:true});
    let lastError;
    for(let attempt=0;attempt<5;attempt++){
      try{await writeFile(file,content,"utf8");return value;}
      catch(error){lastError=error;await new Promise(resolve=>setTimeout(resolve,100*(attempt+1)));}
    }
    throw lastError;
  });
  fileWriteQueues.set(file,task);
  try{return await task;}finally{if(fileWriteQueues.get(file)===task)fileWriteQueues.delete(file);}
}
function cookieValue(request,name){const match=String(request.headers.cookie||"").match(new RegExp(`(?:^|;\\s*)${name}=([^;]+)`));return match?decodeURIComponent(match[1]):"";}
async function bodyJson(request){let body="";for await(const chunk of request){body+=chunk;if(body.length>5000000)throw new Error("请求内容过大");}return JSON.parse(body||"{}");}
async function readSearchGapsFile(){try{const items=JSON.parse(await readFile(searchGapsFile,"utf8"));return Array.isArray(items)?items:[];}catch(error){if(error.code==="ENOENT")return [];throw error;}}
async function writeSearchGapsFile(items){const clean=Array.isArray(items)?items.slice(0,300):[];return writeJsonFile(searchGapsFile,clean);}
function mergeSearchGaps(serverItems,localItems){const merged=[...serverItems];for(const incoming of localItems||[]){if(!incoming?.keyword)continue;const key=String(incoming.key||incoming.keyword).toLocaleLowerCase();const existing=merged.find(item=>String(item.key||item.keyword).toLocaleLowerCase()===key);if(!existing)merged.push({...incoming,key});else if(new Date(incoming.lastSearchedAt||0)>=new Date(existing.lastSearchedAt||0))Object.assign(existing,{...incoming,key,count:Math.max(existing.count||1,incoming.count||1)});}return merged.sort((a,b)=>new Date(b.lastSearchedAt||0)-new Date(a.lastSearchedAt||0)).slice(0,300);}
async function readUsersFile(){try{const users=JSON.parse(await readFile(usersFile,"utf8"));return Array.isArray(users)?users:[];}catch(error){if(error.code==="ENOENT")return [];throw error;}}
async function writeUsersFile(users){return writeJsonFile(usersFile,users);}
function derivePassword(password,salt){return new Promise((resolve,reject)=>scrypt(password,salt,64,(error,key)=>error?reject(error):resolve(key)));}
async function passwordRecord(password){const salt=randomBytes(16).toString("hex"),passwordHash=(await derivePassword(password,salt)).toString("hex");return {salt,passwordHash};}
async function passwordMatches(password,user){try{const saved=Buffer.from(user.passwordHash,"hex"),derived=await derivePassword(password,user.salt);return saved.length===derived.length&&timingSafeEqual(saved,derived);}catch{return false;}}
function publicUser(user){const {password,passwordHash,salt,...safe}=user;return safe;}
function ensureSuperAdmin(users){if(users.length&&!users.some(user=>user.role==="super_admin"))users.sort((a,b)=>Number(a.id)-Number(b.id))[0].role="super_admin";return users;}
async function readArticlesFile(){try{const items=JSON.parse(await readFile(articlesFile,"utf8"));return Array.isArray(items)?items:[];}catch(error){if(error.code==="ENOENT")return [];throw error;}}
async function writeArticlesFile(items){const clean=Array.isArray(items)?items.slice(0,1000):[];return writeJsonFile(articlesFile,clean);}
async function readLeaderboardFile(){try{const items=JSON.parse(await readFile(leaderboardFile,"utf8"));return Array.isArray(items)?items:[];}catch(error){if(error.code==="ENOENT")return [];throw error;}}
async function writeLeaderboardFile(items){const clean=Array.isArray(items)?items.sort((a,b)=>b.score-a.score||new Date(a.achievedAt)-new Date(b.achievedAt)).slice(0,100):[];return writeJsonFile(leaderboardFile,clean);}
async function readPythonProgress(){try{const items=JSON.parse(await readFile(pythonProgressFile,"utf8"));return Array.isArray(items)?items:[];}catch(error){if(error.code==="ENOENT")return [];throw error;}}
async function writePythonProgress(items){return writeJsonFile(pythonProgressFile,items);}
async function readDataList(file){try{const items=JSON.parse(await readFile(file,"utf8"));return Array.isArray(items)?items:[];}catch(error){if(error.code==="ENOENT")return [];throw error;}}
async function writeDataList(file,items,limit=5000){const clean=Array.isArray(items)?items.slice(0,limit):[];return writeJsonFile(file,clean);}
async function readSiteSettings(){try{return {...defaultSiteSettings,...JSON.parse(await readFile(siteSettingsFile,"utf8"))};}catch(error){if(error.code==="ENOENT")return defaultSiteSettings;throw error;}}
async function publishSiteVersion(version,releaseNotes){
  const settings={version,releaseNotes,updatedAt:new Date().toISOString()};await writeJsonFile(siteSettingsFile,settings);
  const [users,items]=await Promise.all([readUsersFile(),readDataList(notificationsFile)]);
  for(const user of users){if(items.some(item=>item.userId===user.id&&item.type==="version_update"&&item.version===version))continue;items.unshift({id:Date.now()+Number(user.id)%100000,userId:user.id,type:"version_update",version,title:`Smart Wiki ${version} 已更新`,content:releaseNotes,read:false,createdAt:new Date().toISOString()});}
  await writeDataList(notificationsFile,items);return settings;
}
async function featuredArticles(){if(featuredCache.expiresAt>Date.now()&&featuredCache.items.length)return featuredCache;const [articles,stats]=await Promise.all([readArticlesFile(),readDataList(articleStatsFile)]),now=Date.now(),day=86400000,week=day*7,statMap=new Map(stats.map(item=>[Number(item.articleId),item]));const published=articles.filter(item=>item.status==="published");const ranked=published.map(item=>{const stat=statMap.get(Number(item.id))||{},times=(stat.recentViews||[]).map(Number).filter(Boolean),dayViews=times.filter(time=>now-time<day).length,weekViews=times.filter(time=>now-time<week).length,total=Number(stat.views)||0,updated=new Date(item.updatedAt||0).getTime(),freshness=updated&&now-updated<30*day?Math.max(0,30-(now-updated)/day)/6:0;return {item,score:dayViews*8+weekViews*2+Math.log2(total+1)*3+freshness};}).sort((a,b)=>b.score-a.score||new Date(b.item.updatedAt||0)-new Date(a.item.updatedAt||0)||Number(a.item.id)-Number(b.item.id));const selected=[],categories=new Set();for(const entry of ranked){if(selected.length>=6)break;if(selected.length<3&&categories.has(entry.item.category)&&ranked.some(other=>!categories.has(other.item.category)&&!selected.includes(other.item)))continue;selected.push(entry.item);categories.add(entry.item.category);}for(const entry of ranked)if(selected.length<6&&!selected.includes(entry.item))selected.push(entry.item);featuredCache={expiresAt:now+3600000,generatedAt:new Date(now).toISOString(),items:selected};return featuredCache;}
async function autoPublishOnlineArticle(){try{const articles=await readArticlesFile(),latest=articles.filter(item=>item.autoImportedAt).sort((a,b)=>new Date(b.autoImportedAt)-new Date(a.autoImportedAt))[0];if(latest&&Date.now()-new Date(latest.autoImportedAt).getTime()<9*60*1000)return {skipped:true,reason:"本轮已经发布"};for(let attempt=0;attempt<5;attempt++){const api=new URL("https://zh.wikipedia.org/w/api.php");Object.entries({action:"query",format:"json",formatversion:"2",generator:"random",grnnamespace:"0",grnlimit:"1",grnfilterredir:"nonredirects",prop:"extracts|pageimages|info",exintro:"1",explaintext:"1",inprop:"url",piprop:"thumbnail",pithumbsize:"1200",variant:"zh-cn",converttitles:"1",uselang:"zh-cn",origin:"*"}).forEach(([key,value])=>api.searchParams.set(key,value));const response=await fetch(api,{headers:{"User-Agent":"SmartWiki/1.0.2 educational knowledge curator"},signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(`Wikipedia HTTP ${response.status}`);const page=(await response.json()).query?.pages?.[0],title=String(page?.title||"").trim(),extract=String(page?.extract||"").trim().replace(/\n{3,}/g,"\n\n");if(!title||extract.length<180||articles.some(item=>item.title===title))continue;const summary=(extract.split(/\n|。/)[0]||extract).trim().slice(0,150)+(extract.length>150?"。":""),content=extract.slice(0,1800),now=new Date().toISOString(),id=Math.max(0,...articles.map(item=>Number(item.id)||0))+1;articles.push({id,title,category:"生活常识",summary,content,icon:"🌐",color:"blue",tags:["网络精选","维基百科","每10分钟更新"],status:"published",updatedAt:now,autoImportedAt:now,image:page.thumbnail?.source||"",keyPoints:[`快速了解“${title}”的基本概念与背景`,`内容来自公开百科资料，并保留原始来源供进一步核对`,`自动收录内容建议结合来源页面与其他资料交叉验证`],sources:[{title:`维基百科：${title}`,url:page.fullurl||`https://zh.wikipedia.org/wiki/${encodeURIComponent(title)}`}],license:"CC BY-SA",sourceProvider:"中文维基百科"});await writeArticlesFile(articles);featuredCache.expiresAt=0;console.log(`每10分钟网络精选已发布：${title}`);return {ok:true,id,title};}return {skipped:true,reason:"未找到合适且未重复的条目"};}catch(error){console.error("每10分钟网络精选获取失败",error.message);return {ok:false,error:error.message};}}
async function runAutoPublish(){if(autoPublishRunning)return {skipped:true,reason:"上一轮仍在运行"};autoPublishRunning=true;autoPublishStatus.lastRunAt=new Date().toISOString();try{autoPublishStatus.lastResult=await autoPublishOnlineArticle();return autoPublishStatus.lastResult;}finally{autoPublishRunning=false;autoPublishStatus.nextRunAt=new Date(Date.now()+autoPublishIntervalMs).toISOString();}}
async function seedVersionNotification(){const users=await readUsersFile(),items=await readDataList(notificationsFile),version="1.0.2";let changed=false;for(const user of users){if(items.some(item=>item.userId===user.id&&item.type==="version_update"&&item.version===version))continue;items.unshift({id:Date.now()+Number(user.id)%100000,userId:user.id,type:"version_update",version,title:`Smart Wiki ${version} 已更新`,content:"本次升级新增每小时网络精选、阅读热度推荐、文章配图与回到顶部、消息分类清理、简体中文自动收录、Edge 后台固定侧栏，并完成项目目录分类与服务器稳定性优化。",read:false,createdAt:new Date().toISOString()});changed=true;}if(changed)await writeDataList(notificationsFile,items);}
await seedVersionNotification();
async function persistSessions(){const items=[...sessions].filter(([,session])=>session.expiresAt>Date.now()).map(([token,session])=>({token,...session}));await writeJsonFile(sessionsFile,items);}
async function createSession(user){const token=randomBytes(32).toString("hex");sessions.set(token,{userId:user.id,expiresAt:Date.now()+604800000});await persistSessions();return token;}
async function requestUser(request){const token=String(request.headers.authorization||"").replace(/^Bearer\s+/i,"");const session=sessions.get(token);if(!session||session.expiresAt<Date.now()){if(session){sessions.delete(token);persistSessions().catch(()=>{});}return null;}return (await readUsersFile()).find(user=>user.id===session.userId)||null;}
async function requireAdmin(request,response,superOnly=false){const user=await requestUser(request);if(!user||(superOnly?user.role!=="super_admin":!["admin","super_admin"].includes(user.role))){sendJson(response,403,{error:"需要管理员权限，请重新登录"});return null;}return user;}
function lanAddresses(){const values=[];for(const entries of Object.values(networkInterfaces()))for(const item of entries||[])if(item.family==="IPv4"&&!item.internal)values.push(`http://${item.address}:${port}`);return [...new Set(values)];}
function isLocalRequest(request){const address=request.socket.remoteAddress||"";return address==="127.0.0.1"||address==="::1"||address.endsWith("127.0.0.1");}
function deviceInfo(userAgent=""){
  const ua=String(userAgent),android=ua.match(/Android[^;)]*;\s*([^;)]+?)(?:\s+Build\/|[;)])/i);
  const type=/iPad|Tablet/i.test(ua)?"平板":/Mobile|Android|iPhone/i.test(ua)?"手机":"电脑";
  const model=/iPhone/i.test(ua)?"iPhone":/iPad/i.test(ua)?"iPad":android?.[1]?.trim()||(/Windows/i.test(ua)?"Windows 电脑":/Macintosh/i.test(ua)?"Mac":/Linux/i.test(ua)?"Linux 设备":"未知设备");
  const browser=/Edg\//i.test(ua)?"Edge":/OPR\//i.test(ua)?"Opera":/Chrome\//i.test(ua)?"Chrome":/Firefox\//i.test(ua)?"Firefox":/Safari\//i.test(ua)?"Safari":/PowerShell/i.test(ua)?"服务检测":"其他浏览器";
  return {type,model,browser};
}
function trackOnlineDevice(request,url){
  if(url.pathname==="/api/online-devices"||url.pathname==="/api/health")return;
  const raw=request.socket.remoteAddress||"unknown",ip=raw.replace(/^::ffff:/,""),userAgent=String(request.headers["user-agent"]||"").slice(0,500),key=`${ip}|${userAgent}`,now=Date.now(),existing=onlineDevices.get(key),info=deviceInfo(userAgent);
  onlineDevices.set(key,{id:key,ip,...info,firstSeenAt:existing?.firstSeenAt||new Date(now).toISOString(),lastSeenAt:new Date(now).toISOString(),requests:(existing?.requests||0)+1});
  for(const [deviceKey,item]of onlineDevices)if(now-new Date(item.lastSeenAt).getTime()>5*60*1000)onlineDevices.delete(deviceKey);
}

const server=createServer(async(request,response)=>{
  try{
    const url=new URL(request.url,"http://localhost");
    trackOnlineDevice(request,url);
    const requestId=randomBytes(6).toString("hex");
    response.setHeader("X-Request-Id",requestId);
    response.setHeader("X-Content-Type-Options","nosniff");
    response.setHeader("Referrer-Policy","same-origin");
    response.setHeader("Permissions-Policy","camera=(), microphone=(), geolocation=()");
    response.setHeader("Cross-Origin-Resource-Policy","same-origin");
    const origin=request.headers.origin;let allowedOrigin=!origin||origin==="null";if(origin){try{const host=new URL(origin).hostname;allowedOrigin=["localhost","127.0.0.1"].includes(host)||/^10\.|^192\.168\.|^172\.(1[6-9]|2\d|3[01])\./.test(host);}catch{allowedOrigin=false;}}if(url.pathname.startsWith("/api/")&&!allowedOrigin)return sendJson(response,403,{error:"禁止跨站访问"});if(origin){response.setHeader("Access-Control-Allow-Origin",origin);response.setHeader("Vary","Origin");}if(request.method==="OPTIONS"){response.writeHead(204,{"Access-Control-Allow-Methods":"GET,POST,PUT,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"});return response.end();}
    if(request.method==="GET"&&url.pathname==="/api/health"){const settings=await readSiteSettings();return sendJson(response,200,{ok:true,name:"Smart Wiki",version:settings.version,uptimeSeconds:Math.floor((Date.now()-startedAt)/1000),time:new Date().toISOString()});}
    if(request.method==="GET"&&url.pathname==="/api/site-version")return sendJson(response,200,await readSiteSettings());
    if(request.method==="POST"&&url.pathname==="/api/site-version"){
      if(!isLocalRequest(request))return sendJson(response,403,{error:"只能在服务器电脑上修改版本"});
      const body=await bodyJson(request),version=String(body.version||"").trim(),releaseNotes=String(body.releaseNotes||"").trim();
      if(!/^\d+\.\d+\.\d+(?:[-+][a-z0-9.-]+)?$/i.test(version))return sendJson(response,400,{error:"版本号格式应类似 1.0.3"});
      if(releaseNotes.length<2||releaseNotes.length>1000)return sendJson(response,400,{error:"请填写 2–1000 字的更新说明"});
      return sendJson(response,200,{ok:true,settings:await publishSiteVersion(version,releaseNotes)});
    }
    if(request.method==="GET"&&url.pathname==="/api/auto-publish/status")return sendJson(response,200,autoPublishStatus);
    if(request.method==="GET"&&url.pathname==="/api/online-devices"){if(!isLocalRequest(request))return sendJson(response,403,{error:"仅允许在服务器电脑上查看在线设备"});const now=Date.now(),items=[...onlineDevices.values()].filter(item=>now-new Date(item.lastSeenAt).getTime()<=5*60*1000).sort((a,b)=>new Date(b.lastSeenAt)-new Date(a.lastSeenAt));return sendJson(response,200,{count:items.length,windowMinutes:5,items});}
    if(request.method==="POST"&&url.pathname==="/api/server/shutdown"){if(!isLocalRequest(request))return sendJson(response,403,{error:"仅允许在服务器电脑上关闭服务"});sendJson(response,200,{ok:true});setTimeout(()=>server.close(()=>process.exit(0)),120).unref();return;}
    if(request.method==="GET"&&url.pathname==="/api/network-info")return sendJson(response,200,{name:"Smart Wiki",port,addresses:lanAddresses()});
    if(request.method==="GET"&&url.pathname==="/api/featured"){const featured=await featuredArticles();return sendJson(response,200,{items:featured.items,generatedAt:featured.generatedAt,refreshAt:new Date(featured.expiresAt).toISOString(),strategy:"recent-and-total-views"});}
    const articleViewMatch=url.pathname.match(/^\/api\/articles\/(\d+)\/view$/);
    if(request.method==="POST"&&articleViewMatch){const articleId=Number(articleViewMatch[1]),articles=await readArticlesFile();if(!articles.some(item=>Number(item.id)===articleId&&item.status==="published"))return sendJson(response,404,{error:"文章不存在"});const address=request.socket.remoteAddress||"unknown",key=`${address}:${articleId}`,last=recentViewKeys.get(key)||0;if(Date.now()-last<1800000)return sendJson(response,200,{ok:true,counted:false});recentViewKeys.set(key,Date.now());for(const [viewKey,time] of recentViewKeys)if(Date.now()-time>1800000)recentViewKeys.delete(viewKey);const stats=await readDataList(articleStatsFile);let record=stats.find(item=>Number(item.articleId)===articleId);if(!record){record={articleId,views:0,recentViews:[]};stats.push(record);}record.views=(Number(record.views)||0)+1;record.recentViews=[Date.now(),...(record.recentViews||[]).filter(time=>Date.now()-Number(time)<604800000)].slice(0,1000);record.lastViewedAt=new Date().toISOString();await writeDataList(articleStatsFile,stats,2000);return sendJson(response,200,{ok:true,counted:true,views:record.views});}
    if(request.method==="GET"&&url.pathname==="/api/game/leaderboard"){const game=/^[a-z0-9-]{1,30}$/.test(url.searchParams.get("game")||"")?url.searchParams.get("game"):"knowledge-run",stored=await readLeaderboardFile(),registered=stored.filter(item=>!String(item.userId).startsWith("guest:"));if(registered.length!==stored.length)await writeLeaderboardFile(registered);const items=registered.filter(item=>(item.game||"knowledge-run")===game).slice(0,50).map(({userId,name,score,level,achievedAt})=>({userId,name,score,level,achievedAt}));return sendJson(response,200,{game,items});}
    if(request.method==="POST"&&url.pathname==="/api/game/score"){const account=await requestUser(request);if(!account)return sendJson(response,401,{error:"登录后成绩才会进入排行榜"});const body=await bodyJson(request),score=Number(body.score),level=Number(body.level),game=/^[a-z0-9-]{1,30}$/.test(body.game||"")?body.game:"knowledge-run";if(!Number.isInteger(score)||score<0||score>1000000||!Number.isInteger(level)||level<1||level>1000)return sendJson(response,400,{error:"成绩数据无效"});const playerId=account.id,playerName=account.name,items=await readLeaderboardFile(),existing=items.find(item=>String(item.userId)===String(playerId)&&(item.game||"knowledge-run")===game);let isNewBest=false;if(!existing){items.push({game,userId:playerId,name:playerName,score,level,achievedAt:new Date().toISOString()});isNewBest=true;}else{existing.name=playerName;if(score>existing.score){Object.assign(existing,{score,level,achievedAt:new Date().toISOString()});isNewBest=true;}}await writeLeaderboardFile(items.filter(item=>!String(item.userId).startsWith("guest:")));const board=(await readLeaderboardFile()).filter(item=>(item.game||"knowledge-run")===game),rank=board.findIndex(item=>String(item.userId)===String(playerId))+1,best=board.find(item=>String(item.userId)===String(playerId));return sendJson(response,200,{ok:true,isNewBest,rank,bestScore:best?.score||score,playerId,game});}
    if(request.method==="GET"&&url.pathname==="/api/articles")return sendJson(response,200,{items:await readArticlesFile()});
    if(request.method==="GET"&&url.pathname==="/api/comments"){const articleId=Number(url.searchParams.get("articleId"));if(!Number.isFinite(articleId))return sendJson(response,400,{error:"缺少文章编号"});const users=await readUsersFile(),avatars=new Map(users.map(user=>[Number(user.id),user.avatar||""]));const items=(await readDataList(commentsFile)).filter(item=>item.articleId===articleId).map(item=>({...item,userAvatar:avatars.get(Number(item.userId))||""}));return sendJson(response,200,{items});}
    if(request.method==="POST"&&url.pathname==="/api/comments"){const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录后才能发表评论"});const body=await bodyJson(request),articleId=Number(body.articleId),parentId=body.parentId==null?null:Number(body.parentId),content=String(body.content||"").trim().replace(/\s+/g," ").slice(0,500);if(!Number.isFinite(articleId)||content.length<1)return sendJson(response,400,{error:"评论内容不能为空"});const comments=await readDataList(commentsFile),parent=parentId==null?null:comments.find(item=>item.id===parentId&&item.articleId===articleId);if(parentId!=null&&!parent)return sendJson(response,404,{error:"要回复的评论不存在"});const item={id:Date.now(),articleId,parentId:parent?.id||null,userId:user.id,userName:user.name,content,createdAt:new Date().toISOString()};comments.unshift(item);await writeDataList(commentsFile,comments);if(parent&&parent.userId!==user.id){const notifications=await readDataList(notificationsFile);notifications.unshift({id:Date.now()+1,userId:parent.userId,type:"comment_reply",title:`${user.name} 回复了你的评论`,content,articleId,commentId:item.id,read:false,createdAt:item.createdAt});await writeDataList(notificationsFile,notifications);}return sendJson(response,201,{item});}
    if(request.method==="GET"&&url.pathname==="/api/notifications"){const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录后才能查看消息"});const items=(await readDataList(notificationsFile)).filter(item=>item.userId===user.id).slice(0,200);return sendJson(response,200,{items,unread:items.filter(item=>!item.read).length});}
    if(request.method==="PUT"&&url.pathname==="/api/notifications/read"){const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录后才能处理消息"});const body=await bodyJson(request),ids=Array.isArray(body.ids)?new Set(body.ids.map(Number)):null,items=await readDataList(notificationsFile);items.forEach(item=>{if(item.userId===user.id&&(!ids||ids.has(item.id)))item.read=true;});await writeDataList(notificationsFile,items);return sendJson(response,200,{ok:true});}
    if(request.method==="DELETE"&&url.pathname==="/api/notifications"){const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录后才能清理通知"});const scope=url.searchParams.get("scope")==="read"?"read":"system",items=await readDataList(notificationsFile);let removed=0;const kept=items.filter(item=>{const matches=scope==="read"?item.read:item.type!=="direct_message";if(item.userId===user.id&&matches){removed++;return false;}return true;});await writeDataList(notificationsFile,kept);return sendJson(response,200,{ok:true,removed,scope});}
    if(request.method==="POST"&&url.pathname==="/api/admin/push"){const admin=await requireAdmin(request,response);if(!admin)return;const body=await bodyJson(request),mode=body.mode==="direct_message"?"direct_message":"system",title=String(body.title||"").trim().slice(0,80),content=String(body.content||"").trim().replace(/\s+/g," ").slice(0,1000),allUsers=await readUsersFile(),requested=Array.isArray(body.userIds)?new Set(body.userIds.map(Number)):null,recipients=(body.audience==="all"?allUsers:allUsers.filter(user=>requested?.has(user.id))).filter(user=>user.id!==admin.id);if(!content||!recipients.length)return sendJson(response,400,{error:"请选择收件人并填写内容"});const now=new Date().toISOString();if(mode==="direct_message"){const items=await readDataList(directMessagesFile);for(const user of recipients)items.unshift({id:Date.now()+Number(user.id)%100000,senderId:admin.id,senderName:`管理员 · ${admin.name}`,recipientId:user.id,recipientName:user.name,content,createdAt:now,read:false});await writeDataList(directMessagesFile,items);}const notifications=await readDataList(notificationsFile);for(const user of recipients){const notice={id:Date.now()+Number(user.id)%100000,userId:user.id,type:mode,title:title||(mode==="direct_message"?`${admin.name} 给你发来管理员私信`:"Smart Wiki 系统通知"),content,read:false,createdAt:now};if(mode==="direct_message")Object.assign(notice,{actorUserId:admin.id,actorName:admin.name});notifications.unshift(notice);}await writeDataList(notificationsFile,notifications);return sendJson(response,200,{ok:true,count:recipients.length});}
    if(request.method==="GET"&&url.pathname==="/api/direct-messages"){const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录后才能查看私信"});const users=await readUsersFile(),userMap=new Map(users.map(item=>[Number(item.id),item]));const items=(await readDataList(directMessagesFile)).filter(item=>(item.senderId===user.id||item.recipientId===user.id)&&!(item.deletedFor||[]).includes(user.id)).slice(0,500).map(item=>({...item,senderAvatar:userMap.get(Number(item.senderId))?.avatar||"",recipientAvatar:userMap.get(Number(item.recipientId))?.avatar||""}));return sendJson(response,200,{items});}
    if(request.method==="DELETE"&&url.pathname==="/api/direct-messages"){const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录后才能清理私信"});const items=await readDataList(directMessagesFile);let removed=0;for(const item of items)if((item.senderId===user.id||item.recipientId===user.id)&&!(item.deletedFor||[]).includes(user.id)){item.deletedFor=[...new Set([...(item.deletedFor||[]),user.id])];removed++;}await writeDataList(directMessagesFile,items);const notices=await readDataList(notificationsFile);await writeDataList(notificationsFile,notices.filter(item=>!(item.userId===user.id&&item.type==="direct_message")));return sendJson(response,200,{ok:true,removed});}
    if(request.method==="POST"&&url.pathname==="/api/direct-messages"){const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录后才能发送私信"});const body=await bodyJson(request),recipientId=Number(body.recipientId),content=String(body.content||"").trim().replace(/\s+/g," ").slice(0,1000),users=await readUsersFile(),recipient=users.find(item=>item.id===recipientId);if(!recipient||recipient.id===user.id)return sendJson(response,400,{error:"收件人无效"});if(!content)return sendJson(response,400,{error:"私信内容不能为空"});const items=await readDataList(directMessagesFile),follows=await readDataList(followsFile),mutual=follows.some(item=>item.followerId===user.id&&item.followingId===recipientId)&&follows.some(item=>item.followerId===recipientId&&item.followingId===user.id),sentCount=items.filter(item=>item.senderId===user.id&&item.recipientId===recipientId).length;if(!mutual&&sentCount>=2)return sendJson(response,429,{error:"未互相关注时最多只能向同一用户发送 2 条私信，请等待对方回关后继续",limit:2,sentCount});const item={id:Date.now(),senderId:user.id,senderName:user.name,recipientId:recipient.id,recipientName:recipient.name,content,createdAt:new Date().toISOString(),read:false};items.unshift(item);await writeDataList(directMessagesFile,items);const notifications=await readDataList(notificationsFile);notifications.unshift({id:Date.now()+1,userId:recipient.id,type:"direct_message",title:`${user.name} 给你发来私信`,content,actorUserId:user.id,actorName:user.name,read:false,createdAt:item.createdAt});await writeDataList(notificationsFile,notifications);return sendJson(response,201,{item,mutual,remaining:mutual?null:Math.max(0,1-sentCount)});}
    if(request.method==="GET"&&url.pathname==="/api/follows"){const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录后才能查看关注关系"});const follows=await readDataList(followsFile),following=follows.filter(item=>item.followerId===user.id).map(item=>item.followingId),followers=follows.filter(item=>item.followingId===user.id).map(item=>item.followerId);return sendJson(response,200,{following,followers,mutual:following.filter(id=>followers.includes(id))});}
    const followMatch=url.pathname.match(/^\/api\/follows\/(\d+)$/);
    if(request.method==="POST"&&followMatch){const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录后才能关注用户"});const targetId=Number(followMatch[1]),users=await readUsersFile(),target=users.find(item=>item.id===targetId);if(!target||target.id===user.id)return sendJson(response,400,{error:"关注对象无效"});const follows=await readDataList(followsFile);let following=follows.some(item=>item.followerId===user.id&&item.followingId===targetId);if(following){await writeDataList(followsFile,follows.filter(item=>!(item.followerId===user.id&&item.followingId===targetId)));following=false;}else{follows.unshift({id:Date.now(),followerId:user.id,followerName:user.name,followingId:target.id,followingName:target.name,createdAt:new Date().toISOString()});await writeDataList(followsFile,follows);following=true;const notifications=await readDataList(notificationsFile);notifications.unshift({id:Date.now()+1,userId:target.id,type:"follow",title:`${user.name} 关注了你`,content:"你可以回关并开始站内交流",actorUserId:user.id,actorName:user.name,read:false,createdAt:new Date().toISOString()});await writeDataList(notificationsFile,notifications);}const current=await readDataList(followsFile),mutual=current.some(item=>item.followerId===targetId&&item.followingId===user.id)&&following;return sendJson(response,200,{following,mutual});}
    if(request.method==="GET"&&url.pathname==="/api/python/progress"){const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录后才能读取云端学习记录"});const record=(await readPythonProgress()).find(item=>item.userId===user.id);return sendJson(response,200,{record:record||{userId:user.id,completed:[],history:[]}});}
    if(request.method==="DELETE"&&url.pathname.startsWith("/api/python/progress/history/")){const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录后才能删除云端历史"});const historyId=Number(url.pathname.split("/").at(-1));if(!Number.isFinite(historyId))return sendJson(response,400,{error:"无效的历史记录"});const items=await readPythonProgress(),record=items.find(item=>item.userId===user.id);if(!record)return sendJson(response,404,{error:"没有找到学习记录"});const before=(record.history||[]).length;record.history=(record.history||[]).filter(item=>Number(item.id)!==historyId);if(record.history.length===before)return sendJson(response,404,{error:"这条历史记录不存在"});record.updatedAt=new Date().toISOString();await writePythonProgress(items);return sendJson(response,200,{record});}
    if(request.method==="PUT"&&url.pathname==="/api/python/progress"){const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录后才能保存到服务器"});const body=await bodyJson(request),code=String(body.code||"").slice(0,100000),output=String(body.output||"").slice(0,20000),lessonIndex=Math.max(0,Math.min(99,Number(body.lessonIndex)||0)),completed=[...new Set((Array.isArray(body.completed)?body.completed:[]).map(Number).filter(value=>value>=0&&value<100))],items=await readPythonProgress();let record=items.find(item=>item.userId===user.id);if(!record){record={userId:user.id,completed:[],history:[]};items.push(record);}record.completed=[...new Set([...(record.completed||[]),...completed])];record.updatedAt=new Date().toISOString();if(body.saveSnapshot!==false)record.history=[{id:Date.now(),lessonIndex,code,output,savedAt:record.updatedAt},...(record.history||[])].slice(0,50);await writePythonProgress(items);return sendJson(response,200,{record});}
    if(request.method==="PUT"&&url.pathname==="/api/articles"){if(!await requireAdmin(request,response))return;const {items}=await bodyJson(request);return sendJson(response,200,{items:await writeArticlesFile(items)});}
    if(request.method==="GET"&&url.pathname==="/api/search-gaps"){if(!await requireAdmin(request,response))return;return sendJson(response,200,{items:await readSearchGapsFile()});}
    if(request.method==="PUT"&&url.pathname==="/api/search-gaps"){if(!await requireAdmin(request,response))return;const {items}=await bodyJson(request);return sendJson(response,200,{items:await writeSearchGapsFile(items)});}
    if(request.method==="POST"&&url.pathname==="/api/search-gaps/report"){const {item}=await bodyJson(request);const merged=mergeSearchGaps(await readSearchGapsFile(),item?[item]:[]);return sendJson(response,200,{ok:true,items:await writeSearchGapsFile(merged)});}
    if(request.method==="POST"&&url.pathname==="/api/search-gaps/import"){if(!isLocalRequest(request))return sendJson(response,403,{error:"迁移仅允许在服务器电脑执行"});const {items}=await bodyJson(request);const merged=mergeSearchGaps(await readSearchGapsFile(),Array.isArray(items)?items:[]);return sendJson(response,200,{items:await writeSearchGapsFile(merged)});}
    if(request.method==="GET"&&url.pathname==="/api/users"){if(!await requireAdmin(request,response))return;return sendJson(response,200,{users:(await readUsersFile()).map(publicUser)});}
    if(request.method==="POST"&&url.pathname==="/api/users/import"){
      if(!isLocalRequest(request))return sendJson(response,403,{error:"迁移仅允许在服务器电脑执行"});const {users:incoming}=await bodyJson(request);const stored=await readUsersFile();for(const user of Array.isArray(incoming)?incoming:[]){if(!user?.email||stored.some(item=>item.email===String(user.email).toLowerCase()))continue;const password=String(user.password||"");if(password.length<6)continue;stored.push({...publicUser(user),email:String(user.email).toLowerCase(),...await passwordRecord(password)});}ensureSuperAdmin(stored);await writeUsersFile(stored);return sendJson(response,200,{users:stored.map(publicUser)});
    }
    if(request.method==="PUT"&&url.pathname==="/api/users"){
      if(!await requireAdmin(request,response,true))return;const {users:incoming}=await bodyJson(request);const stored=await readUsersFile();const requested=Array.isArray(incoming)?incoming:[];const updated=requested.map(user=>{const existing=stored.find(item=>item.id===user.id||item.email===user.email);return existing?{...existing,name:user.name||existing.name,email:user.email||existing.email,role:user.role||existing.role}:null;}).filter(Boolean);ensureSuperAdmin(updated);await writeUsersFile(updated);return sendJson(response,200,{users:updated.map(publicUser)});
    }
    if(request.method==="POST"&&url.pathname==="/api/auth/register"){
      const {name,email,password}=await bodyJson(request);const cleanEmail=String(email||"").trim().toLowerCase();const users=await readUsersFile();if(users.some(user=>user.email===cleanEmail))return sendJson(response,409,{error:"这个邮箱已经注册过了，请直接登录"});if(String(name||"").trim().length<2||String(password||"").length<6)return sendJson(response,400,{error:"昵称或密码不符合要求"});const user={id:Date.now(),name:String(name).trim(),email:cleanEmail,role:users.length?"user":"super_admin",...await passwordRecord(String(password))};users.push(user);await writeUsersFile(users);const notifications=await readDataList(notificationsFile);notifications.unshift({id:Date.now()+1,userId:user.id,type:"welcome",title:`欢迎加入 Smart Wiki，${user.name}！`,content:"你可以从知识库开始探索，也可以使用工具箱、游戏中心和 Python 学习中心。",read:false,createdAt:new Date().toISOString()});await writeDataList(notificationsFile,notifications);return sendJson(response,201,{user:publicUser(user),token:await createSession(user)});
    }
    if(request.method==="POST"&&url.pathname==="/api/auth/login"){
      const {email,password}=await bodyJson(request),cleanEmail=String(email||"").trim().toLowerCase(),cleanPassword=String(password||"");if(!cleanEmail||cleanEmail.length>254||!cleanPassword||cleanPassword.length>256)return sendJson(response,400,{error:"请输入有效的邮箱和密码"});const user=(await readUsersFile()).find(item=>item.email===cleanEmail);if(!user||!await passwordMatches(cleanPassword,user))return sendJson(response,401,{error:"邮箱或密码不正确"});return sendJson(response,200,{user:publicUser(user),token:await createSession(user)});
    }
    if(request.method==="GET"&&url.pathname==="/api/auth/me"){const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录已过期，请重新登录"});return sendJson(response,200,{user:publicUser(user)});}
    if(request.method==="POST"&&url.pathname==="/api/auth/avatar"){
      const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录已过期，请重新登录"});
      const body=await bodyJson(request),avatar=String(body.avatar||"");
      const preset=/^\/assets\/avatars\/avatar-[1-8]\.svg$/.test(avatar),upload=/^data:image\/(?:png|jpeg);base64,[a-z0-9+/=]+$/i.test(avatar)&&avatar.length<=450000;
      if(!preset&&!upload)return sendJson(response,400,{error:"请选择预设头像，或上传有效的 JPG/PNG 图片"});
      const users=await readUsersFile(),stored=users.find(item=>item.id===user.id);stored.avatar=avatar;stored.avatarUpdatedAt=new Date().toISOString();await writeUsersFile(users);return sendJson(response,200,{user:publicUser(stored)});
    }
    const resetMatch=url.pathname.match(/^\/api\/users\/(\d+)\/reset-password$/);
    if(request.method==="POST"&&resetMatch){const admin=await requireAdmin(request,response,true);if(!admin)return;const users=await readUsersFile(),user=users.find(item=>item.id===Number(resetMatch[1]));if(!user)return sendJson(response,404,{error:"用户不存在"});if(user.role==="super_admin")return sendJson(response,400,{error:"不能通过后台重置超级管理员密码"});Object.assign(user,await passwordRecord("123456"),{mustChangePassword:true,passwordResetAt:new Date().toISOString(),passwordResetBy:admin.id});await writeUsersFile(users);return sendJson(response,200,{user:publicUser(user),temporaryPassword:"123456"});}
    if(request.method==="POST"&&url.pathname==="/api/auth/change-password"){const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录已过期，请重新登录"});const {oldPassword,newPassword}=await bodyJson(request);if(!await passwordMatches(String(oldPassword||""),user))return sendJson(response,400,{error:"旧密码或临时密码不正确"});if(String(newPassword||"").length<8)return sendJson(response,400,{error:"新密码至少需要 8 个字符"});if(String(newPassword)===String(oldPassword))return sendJson(response,400,{error:"新密码不能与旧密码相同"});const users=await readUsersFile(),stored=users.find(item=>item.id===user.id);Object.assign(stored,await passwordRecord(String(newPassword)),{mustChangePassword:false,passwordChangedAt:new Date().toISOString()});delete stored.passwordResetAt;delete stored.passwordResetBy;await writeUsersFile(users);for(const [token,session] of sessions)if(session.userId===user.id)sessions.delete(token);await persistSessions();return sendJson(response,200,{user:publicUser(stored),loggedOut:true});}
    if(request.method==="POST"&&url.pathname==="/api/auth/change-name"){const user=await requestUser(request);if(!user)return sendJson(response,401,{error:"登录已过期，请重新登录"});const {name}=await bodyJson(request),cleanName=String(name||"").trim().replace(/\s+/g," ");if(cleanName.length<2||cleanName.length>24)return sendJson(response,400,{error:"昵称需要 2–24 个字符"});if(cleanName===user.name)return sendJson(response,400,{error:"新昵称不能与当前昵称相同"});const lastTime=new Date(user.lastNameChangedAt||0).getTime(),nextTime=lastTime+86400000;if(lastTime&&Date.now()<nextTime)return sendJson(response,429,{error:`每 24 小时只能修改一次昵称，下次可修改时间：${new Date(nextTime).toLocaleString("zh-CN")}`,nextAllowedAt:new Date(nextTime).toISOString()});const users=await readUsersFile(),stored=users.find(item=>item.id===user.id);stored.name=cleanName;stored.lastNameChangedAt=new Date().toISOString();await writeUsersFile(users);return sendJson(response,200,{user:publicUser(stored),nextAllowedAt:new Date(Date.now()+86400000).toISOString()});}
    if(request.method!=="GET"&&request.method!=="HEAD")return sendJson(response,405,{error:"不支持的请求方法"});
    let pathname=decodeURIComponent(url.pathname);if(pathname==="/")pathname="/index.html";if(pathname.split(/[\\/]/).some(part=>part.startsWith(".")))return sendJson(response,403,{error:"禁止访问"});const requestedExtension=extname(pathname).toLowerCase(),isRootAsset=pathname.lastIndexOf("/")===0,name=pathname.slice(1);if(isRootAsset&&requestedExtension===".html"&&name!=="index.html")pathname=`/pages/${name}`;else if(isRootAsset&&requestedExtension===".css")pathname=`/css/${name}`;else if(isRootAsset&&requestedExtension===".js")pathname=`/js/${name}`;const safePath=normalize(pathname).replace(/^(\.\.[\\/])+/,"");const filePath=join(root,safePath);if(!filePath.startsWith(root)||!publicExtensions.has(extname(filePath).toLowerCase()))return sendJson(response,403,{error:"禁止访问"});
    const fileStat=await stat(filePath);if(!fileStat.isFile())throw new Error("NOT_FOUND");let content=await readFile(filePath),extension=extname(filePath).toLowerCase(),liveAsset=[".html",".css",".js"].includes(extension);if(extension===".html"||extension===".js"){const settings=await readSiteSettings();content=Buffer.from(content.toString("utf8").replace(/Version\s+\d+\.\d+\.\d+(?:[-+][a-z0-9.-]+)?/gi,`Version ${settings.version}`));}response.writeHead(200,{"Content-Type":mime[extension]||"application/octet-stream","Cache-Control":liveAsset?"no-cache":"public, max-age=3600"});if(request.method==="HEAD")response.end();else response.end(content);
  }catch(error){if(error.code==="ENOENT"||error.message==="NOT_FOUND")sendJson(response,404,{error:"页面不存在"});else if(error instanceof SyntaxError)sendJson(response,400,{error:"请求数据格式不正确"});else{console.error("请求处理失败",error);sendJson(response,500,{error:"服务器暂时无法处理请求，请稍后重试"});}}
});
server.keepAliveTimeout=65000;
server.headersTimeout=66000;
server.listen(port,"0.0.0.0",()=>{console.log(`Smart Wiki 本机地址: http://127.0.0.1:${port}`);for(const address of lanAddresses())console.log(`Smart Wiki 局域网地址: ${address}`);console.log(`局域网入口与二维码: http://127.0.0.1:${port}/lan.html`);});
autoPublishStatus.nextRunAt=new Date(Date.now()+autoPublishIntervalMs).toISOString();
setTimeout(runAutoPublish,autoPublishIntervalMs).unref();
setInterval(runAutoPublish,autoPublishIntervalMs).unref();
